Repository powsybl/powsybl-core, pull requests merged in 2019-09, with the labels that each got.

#835 Loadflow api v2
  action/action-simulator/src/main/java/com/powsybl/action/simulator/loadflow/LoadFlowActionSimulator.java
  action/action-simulator/src/main/java/com/powsybl/action/simulator/loadflow/LoadFlowActionSimulatorConfig.java
  action/action-simulator/src/test/java/com/powsybl/action/simulator/AbstractLoadFlowRulesEngineTest.java
  action/action-simulator/src/test/java/com/powsybl/action/simulator/ContingencyOccurredTest.java
  action/action-simulator/src/test/java/com/powsybl/action/simulator/LoadFlowProviderMock.java
  action/action-simulator/src/test/java/com/powsybl/action/simulator/loadflow/LoadFlowActionSimulatorConfigTest.java
  action/action-simulator/src/test/java/com/powsybl/action/simulator/loadflow/LoadFlowActionSimulatorTest.java
  action/action-util/src/main/java/com/powsybl/action/util/LoadFlowBasedPhaseShifterOptimizer.java
  action/action-util/src/main/java/com/powsybl/action/util/LoadFlowBasedPhaseShifterOptimizerConfig.java
  action/action-util/src/test/java/com/powsybl/action/util/LoadFlowBasedPhaseShifterOptimizerConfigTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/ConversionTester.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/CgmesConformity1ConversionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
  commons/src/main/java/com/powsybl/commons/config/InMemoryPlatformConfig.java
  commons/src/main/java/com/powsybl/commons/config/MapModuleConfig.java
  commons/src/main/java/com/powsybl/commons/config/PlatformConfig.java
  loadflow/loadflow-api/src/main/groovy/com/powsybl/loadflow/LoadFlowGroovyScriptExtension.groovy
  loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlow.java
  loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowFactory.java
  loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowProvider.java
  loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowProviderPluginInfo.java
  loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/mock/LoadFlowFactoryMock.java
  loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/tools/RunLoadFlowTool.java
  loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/AnotherLoadFlowProviderMock.java
  loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowExtensionGroovyScriptTest.java
  loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowProviderMock.java
  loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowTest.java
  loadflow/loadflow-results-completion/src/test/java/com/powsybl/loadflow/resultscompletion/LoadFlowResultsCompletionZ0FlowsTest.java
  loadflow/loadflow-validation/readme.md
  loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/LoadFlowComputation.java
  loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/ValidationConfig.java
  loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/ValidationTool.java
  loadflow/loadflow-validation/src/test/java/com/powsybl/loadflow/validation/AbstractValidationTest.java
  loadflow/loadflow-validation/src/test/java/com/powsybl/loadflow/validation/CandidateComputationsTest.java
  loadflow/loadflow-validation/src/test/java/com/powsybl/loadflow/validation/FlowsValidationTest.java
  loadflow/loadflow-validation/src/test/java/com/powsybl/loadflow/validation/LoadFlowProviderMock.java
  loadflow/loadflow-validation/src/test/java/com/powsybl/loadflow/validation/ValidationConfigTest.java
  loadflow/loadflow-validation/src/test/java/com/powsybl/loadflow/validation/io/ValidationWritersTest.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/SecurityAnalysisFactoryImpl.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/SecurityAnalysisImpl.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/LoadFlowProviderMock.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/SecurityAnalysisTest.java
Labels: Breaking Change, Doc needed

#901 Import qPercent (coordinated reactive control) for synchronous machines
  cgmes/cgmes-conversion/pom.xml
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SynchronousMachineConversion.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/network/compare/Comparison.java
  cgmes/cgmes-model/src/main/resources/CIM16.sparql
Labels: :thumbsup: Ready For Merge, CGMES

#910 iidm notify update on SubstationImpl.GeographicalTags
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SubstationImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/SubstationTest.java
Labels: :thumbsup: Ready For Merge

#912 iidm notify update on TieLineImpl.HalfLineImpl changes
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractConnectable.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TieLineImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/LineTest.java
Labels: :thumbsup: Ready For Merge

#909 Refactor merged line creation in UcteImporter to solve inconsistent data
  ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteImporter.java
Labels: :thumbsup: Ready For Merge

#917 CGMES correction: rho and alpha of PTC depend on the side where the PTC is
  cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1ModifiedCatalog.java
  cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_ptc_side_2/MicroGridTestConfiguration_BC_BE_EQ_V2.xml
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/PhaseTapChangerConversion.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
Labels: CGMES

#895 IIDM : add missing notifications
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/RatioTapChanger.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/TapChanger.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractBranch.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractConnectable.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractIdentifiable.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractTapChanger.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusBreakerVoltageLevel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/DanglingLineImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/GeneratorImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/PhaseTapChangerImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/RatioTapChangerImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ReactiveLimitsHolderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ThreeWindingsTransformerImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TieLineAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TieLineImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TwoWindingsTransformerImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/TapChangerTest.java
Labels: :thumbsup: Ready For Merge

#919 In loadflow results completion, check that there is a bus in the busView
  loadflow/loadflow-results-completion/src/main/java/com/powsybl/loadflow/resultscompletion/LoadFlowResultsCompletion.java
Labels: PR: ready-to-be-merged

#924 Travis
  .travis.yml
Labels: PR: not-assigned

#931 travis: restore sonar on push events
  .travis.yml
Labels: PR: not-assigned, Travis

#929 Add methods to retrieve the HVDCLine from the converter stations
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/HvdcConverterStation.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/HvdcLine.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractHvdcConverterStation.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/HvdcLineImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/LccTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/VscTest.java
Labels: PR: ready-to-be-merged

#930 Update powsybl-math-native version to 1.0.1 (MacOS support)
  math/src/main/java/com/powsybl/math/matrix/SparseMatrix.java
  math/src/test/java/com/powsybl/math/matrix/SparseMatrixTest.java
  pom.xml
Labels: PR: ready-to-be-merged

#933 Add automatic module name in iidm-extensions
  iidm/iidm-extensions/pom.xml
Labels: PR: ready-to-be-merged

#935 Correct automatic module name of sensitivity-api
  sensitivity-api/pom.xml
Labels: PR: ready-to-be-merged

#911 Replace Identifiable.getProperties by getProperty & setProperty
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/TopologyTester.java
  iidm/iidm-api/src/main/groovy/com/powsybl/iidm/network/IdentifiableExtension.groovy
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Identifiable.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractIdentifiable.java
  iidm/iidm-impl/src/test/groovy/com/powsybl/iidm/network/impl/IdentifiableExtensionGroovyTest.groovy
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/NetworkTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/VariantManagerImplTest.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/PropertiesXml.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/NetworkXmlTest.java
  loadflow/loadflow-validation/src/test/java/com/powsybl/loadflow/validation/ShuntCompensatorsValidationTest.java
  ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteExporter.java
  ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteImporter.java
  ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/UcteImporterTest.java
Labels: Breaking Change, Deprecated, PR: ready-to-be-merged

#908 Correct handling of missing attributes in EI during CGMES import
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EquivalentInjectionConversion.java
Labels: CGMES, PR: ready-to-be-merged

#872 Use ssh values instead of sv values if they are present
  cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1ModifiedCatalog.java
  cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1NetworkCatalog.java
  cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_rtc_ptc_enabled_in_ssh_data/MicroGridTestConfiguration_BC_BE_SSH_V2.xml
  cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_rtc_ptc_tabular/MicroGridTestConfiguration_BC_BE_SSH_V2.xml
  cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_rtc_ptc_tabular/MicroGridTestConfiguration_BC_BE_SV_V2.xml
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMapping.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractConductingEquipmentConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EnergyConsumerConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/PhaseTapChangerConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/RatioTapChangerConversion.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/CgmesConformity1ConversionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
  cgmes/cgmes-model/src/main/resources/CIM16.sparql
Labels: CGMES, PR: ready-to-be-merged

#852 Convert sv injections during CGMES import
  cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1ModifiedCatalog.java
  cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_invalid_sv_injection/MicroGridTestConfiguration_BC_BE_SV_V2.xml
  cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_with_sv_injection/MicroGridTestConfiguration_BC_BE_EQ_V2.xml
  cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_with_sv_injection/MicroGridTestConfiguration_BC_BE_SV_V2.xml
  cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_with_sv_injection/MicroGridTestConfiguration_BC_BE_TP_V2.xml
  cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MiniGrid/NodeBreaker/BaseCase_Complete_v3_sv_injection/MiniGridTestConfiguration_BC_SV_v3.0.0.xml
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/NodeMapping.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/TerminalMapping.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ACLineSegmentConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractConductingEquipmentConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ShuntConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SvInjectionConversion.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesModel.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/triplestore/CgmesModelTripleStore.java
  cgmes/cgmes-model/src/main/resources/CIM14.sparql
  cgmes/cgmes-model/src/main/resources/CIM16.sparql
  cgmes/cgmes-model/src/test/java/com/powsybl/cgmes/model/test/FakeCgmesModel.java
Labels: CGMES, PR: ready-to-be-merged

#942 Fix setProperty return type
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Identifiable.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractIdentifiable.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/VariantManagerImplTest.java
Labels: Breaking Change, Refactoring

#937 Increase code coverage in XML converter
  iidm/iidm-reducer/pom.xml
  iidm/iidm-reducer/src/test/java/com/powsybl/iidm/reducer/DefaultNetworkReducerTest.java
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/EurostagTutorialExample1Factory.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/TieLineXml.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/DanglingLineXmlTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/EurostagXmlTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/TieLineXmlTest.java
  iidm/iidm-xml-converter/src/test/resources/danglingLine.xml
  iidm/iidm-xml-converter/src/test/resources/eurostag-tutorial1-lf.xml
  iidm/iidm-xml-converter/src/test/resources/tieline.xml
Labels: IIDM, PR: ready-to-be-merged, bug, unit test

#946 generic mechanism for naming the tap changer attribute in transformers
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/PhaseTapChangerImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/RatioTapChangerImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ThreeWindingsTransformerImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TwoWindingsTransformerImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/TapChangerAttributeTest.java
Labels: IIDM

#949 Regression fix : long task computation manager is used for security analysis sub-tasks
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/tools/SecurityAnalysisTool.java
Labels: PR: ready-to-be-merged

#953 ClassicPlatformConfigProvider: use user.home when powsybl-config-dir is the empty string.
  config-classic/src/main/java/com/powsybl/config/classic/ClassicPlatformConfigProvider.java
  config-classic/src/test/java/com/powsybl/config/classic/ClassicPlatformConfigProviderTest.java
Labels: PR: ready-to-be-merged

#950 pom.xml: restore checks on java11 normal maven executions
  distribution-core/pom.xml
  pom.xml
Labels: PR: ready-to-be-merged

#947 Implementation of Identifiable::getNetwork()
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Identifiable.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractBus.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractConnectable.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractIdentifiable.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/MergedBus.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SwitchImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/BusTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/CalculatedTopologyTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/NetworkTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/VariantManagerImplTest.java
Labels: Breaking Change, PR: review-ongoing

#955 Adding container notification implementation
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/NetworkListener.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractIdentifiable.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkListenerList.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SubstationImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/NetworkTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/SubstationTest.java
Labels: PR: waiting-for-review
