Repository powsybl/powsybl-core, pull requests merged in 2019-05, with the labels that each got.

#779 Add getBus(id) method
  ampl-converter/src/test/java/com/powsybl/ampl/converter/AmplNetworkReaderTest.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Network.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/BusTest.java
Labels: :thumbsup: Ready For Merge

#658 Tests independent of local TableFormatterConfig
  action/action-simulator/src/main/java/com/powsybl/action/simulator/loadflow/LoadFlowActionSimulator.java
  action/action-simulator/src/test/java/com/powsybl/action/simulator/AbstractLoadFlowRulesEngineTest.java
  action/action-simulator/src/test/java/com/powsybl/action/simulator/ContingencyOccurredTest.java
  action/action-simulator/src/test/java/com/powsybl/action/simulator/loadflow/LoadFlowActionSimulatorTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/ConversionTester.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/Networks.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/NetworksTest.java
  loadflow/loadflow-results-completion/src/test/java/com/powsybl/loadflow/resultscompletion/LoadFlowResultsCompletionZ0FlowsTest.java
  loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/AbstractTransformersValidation.java
  loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/BusesValidation.java
  loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/FlowsValidation.java
  loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/GeneratorsValidation.java
  loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/ShuntCompensatorsValidation.java
  loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/StaticVarCompensatorsValidation.java
  loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/Transformers3WValidation.java
  loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/TransformersValidation.java
  loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/ValidationType.java
  loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/ValidationUtils.java
  loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/io/ValidationFormatterCsvMultilineWriterFactory.java
  loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/io/ValidationFormatterCsvWriterFactory.java
  loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/io/ValidationWriterFactory.java
  loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/io/ValidationWriters.java
  loadflow/loadflow-validation/src/test/java/com/powsybl/loadflow/validation/AbstractValidationTest.java
  loadflow/loadflow-validation/src/test/java/com/powsybl/loadflow/validation/BusesValidationTest.java
  loadflow/loadflow-validation/src/test/java/com/powsybl/loadflow/validation/FlowsValidationTest.java
  loadflow/loadflow-validation/src/test/java/com/powsybl/loadflow/validation/GeneratorsValidationTest.java
  loadflow/loadflow-validation/src/test/java/com/powsybl/loadflow/validation/ShuntCompensatorsValidationTest.java
  loadflow/loadflow-validation/src/test/java/com/powsybl/loadflow/validation/StaticVarCompensatorsValidationTest.java
  loadflow/loadflow-validation/src/test/java/com/powsybl/loadflow/validation/Transformers3WValidationTest.java
  loadflow/loadflow-validation/src/test/java/com/powsybl/loadflow/validation/TransformersValidationTest.java
  loadflow/loadflow-validation/src/test/java/com/powsybl/loadflow/validation/io/ValidationFormatterCsvMultilineWriterTest.java
  loadflow/loadflow-validation/src/test/java/com/powsybl/loadflow/validation/io/ValidationFormatterCsvWriterTest.java
  loadflow/loadflow-validation/src/test/java/com/powsybl/loadflow/validation/io/ValidationWritersTest.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/SecurityAnalysisTool.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/SecurityAnalysisToolConstants.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/comparator/LimitViolationsResultEquivalence.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/comparator/SecurityAnalysisResultComparisonWriter.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/comparator/SecurityAnalysisResultEquivalence.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/SecurityAnalysisToolTest.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/comparator/LimitViolationsResultEquivalenceTest.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/comparator/SecurityAnalysisResultComparisonWriterTest.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/comparator/SecurityAnalysisResultEquivalenceTest.java
Labels: Breaking Change, Configuration

#788 Matrix renaming + javadoc fixes
  math/src/main/java/com/powsybl/math/matrix/AbstractMatrix.java
  math/src/main/java/com/powsybl/math/matrix/DenseMatrix.java
  math/src/main/java/com/powsybl/math/matrix/DenseMatrixFactory.java
  math/src/main/java/com/powsybl/math/matrix/Matrix.java
  math/src/main/java/com/powsybl/math/matrix/MatrixFactory.java
  math/src/main/java/com/powsybl/math/matrix/SparseLUDecomposition.java
  math/src/main/java/com/powsybl/math/matrix/SparseMatrix.java
  math/src/main/java/com/powsybl/math/matrix/SparseMatrixFactory.java
  math/src/test/java/com/powsybl/math/matrix/AbstractMatrixTest.java
  math/src/test/java/com/powsybl/math/matrix/DenseMatrixTest.java
  math/src/test/java/com/powsybl/math/matrix/SparseMatrixTest.java
Labels: Breaking Change, Javadoc, Math

#712 Optional country for IIDM substations
  ampl-converter/src/main/java/com/powsybl/ampl/converter/AmplNetworkWriter.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CountryConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SubstationConversion.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/cim14/Cim14SmallCasesNetworkCatalog.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/CgmesConformity1ConversionTest.java
  cgmes/cgmes-conversion/src/test/resources/cim14/7buses.xiidm
  cgmes/cgmes-conversion/src/test/resources/cim14/ieee14.xiidm
  cgmes/cgmes-conversion/src/test/resources/cim14/tx-from-microBE-adapted.xiidm
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Network.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Substation.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/Boundary.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SubstationAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SubstationImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/Substations.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ValidationUtil.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/NetworkTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/SubstationTest.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/SubstationXml.java
  iidm/iidm-xml-converter/src/main/resources/xsd/iidm.xsd
  security-analysis/security-analysis-afs/src/main/java/com/powsybl/security/afs/SubjectInfoInterceptor.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/LimitViolationFilter.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/LimitViolationHelper.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/Security.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/LimitViolationFilterTest.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/LimitViolationTest.java
  ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteImporter.java
  ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/UcteImporterTest.java
Labels: Breaking Change, IIDM

#792 Add javadoc to the Graph API
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusBreakerVoltageLevel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java
  math/src/main/java/com/powsybl/math/graph/UndirectedGraph.java
  math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java
Labels: Javadoc

#790 Variant can now be copied into an already existing Variant
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VariantManager.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VariantManagerImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/VariantManagerImplTest.java
Labels: Breaking Change

#773 Cgmes regulation control
  cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1ModifiedCatalog.java
  cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1NetworkCatalog.java
  cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_invalid_regulating_control/MicroGridTestConfiguration_BC_BE_EQ_V2.xml
  cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_invalid_regulating_control/MicroGridTestConfiguration_BC_BE_SSH_V2.xml
  cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_missing_regulating_control/MicroGridTestConfiguration_BC_BE_EQ_V2.xml
  cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_ptc_current_limiter/MicroGridTestConfiguration_BC_BE_EQ_V2.xml
  cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MiniGrid/BusBranch/BaseCase_v3_rtc_with_remote_regulation/MiniGridTestConfiguration_BC_EQ_v3.0.0.xml
  cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MiniGrid/BusBranch/BaseCase_v3_rtc_with_remote_regulation/MiniGridTestConfiguration_BC_SSH_v3.0.0.xml
  cgmes/cgmes-conformity/src/test/resources/conformity-modified/cas-1.1.3-data-4.0.3/MiniGrid/BusBranch/BaseCase_v3_rtc_with_remote_regulation/MiniGridTestConfiguration_BC_TP_v3.0.0.xml
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMapping.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/TapChangerTransformers.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ExternalNetworkInjectionConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/PhaseTapChangerConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/RatioTapChangerConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/RegulatingControlConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SynchronousMachineConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ThreeWindingsTransformerConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/TwoWindingsTransformerConversion.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/CgmesConformity1ConversionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/network/compare/Comparison.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesModel.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/triplestore/CgmesModelTripleStore.java
  cgmes/cgmes-model/src/main/resources/CIM14.sparql
  cgmes/cgmes-model/src/main/resources/CIM16.sparql
  cgmes/cgmes-model/src/test/java/com/powsybl/cgmes/model/test/FakeCgmesModel.java
Labels: CGMES, Refactoring

#814 IIDM network import using alternative IIDM implementation
  action/action-simulator/src/test/java/com/powsybl/action/simulator/loadflow/CaseExporterTest.java
  action/action-util/src/test/java/com/powsybl/action/util/ScalableTestNetwork.java
  afs/afs-ext-base/src/test/java/com/powsybl/afs/ext/base/ImportedCaseTest.java
  cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1NetworkCatalog.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/cim14/Cim14SmallCasesNetworkCatalog.java
  contingency/contingency-api/src/test/java/com/powsybl/contingency/tasks/ContingencyTopologyTraverserTest.java
  entsoe-util/src/test/java/com/powsybl/entsoe/util/EntsoeAreaXmlSerializerTest.java
  entsoe-util/src/test/java/com/powsybl/entsoe/util/MergedXnodeXmlSerializerTest.java
  entsoe-util/src/test/java/com/powsybl/entsoe/util/XnodeXmlSerializerTest.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Network.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/NetworkFactory.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/NetworkFactoryConstants.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/NetworkFactoryService.java
  iidm/iidm-converter-api/src/main/java/com/powsybl/iidm/import_/Importer.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkFactoryImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkFactoryServiceImpl.java
  iidm/iidm-impl/src/main/resources/META-INF/services/com.powsybl.iidm.network.NetworkFactoryService
  iidm/iidm-impl/src/test/groovy/com/powsybl/iidm/network/impl/IdentifiableExtensionGroovyTest.groovy
  iidm/iidm-impl/src/test/groovy/com/powsybl/iidm/network/impl/NetworkExtensionTest.groovy
  iidm/iidm-impl/src/test/groovy/com/powsybl/iidm/network/impl/SubstationExtensionTest.groovy
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/BusTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/CalculatedTopologyTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/ConnectedComponentWithTieLineBugTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/CurrentLimitsTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/DanglingLineTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/EmptyCalculatedBusBugTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/NetworkTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/NodeBreakerDisconnectionDoublePathBugTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/NodeBreakerInternalConnectionsTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/NodeBreakerTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/NullPointerWhenRemovingMergedLineBugTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/SubstationTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/SwitchOpenCloseNodeBreakerTopoTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/SwitchSetRetainedTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/TopologyTraverserTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/VoltageLevelTest.java
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/BatteryNetworkFactory.java
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/DanglingLineNetworkFactory.java
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/EurostagTutorialExample1Factory.java
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/FictitiousSwitchFactory.java
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/HvdcTestNetwork.java
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/MultipleExtensionsTestNetworkFactory.java
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/NetworkTest1Factory.java
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/NoEquipmentNetworkFactory.java
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/PhaseShifterTestCaseFactory.java
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/ReactiveLimitsTestNetworkFactory.java
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/SvcTestCaseFactory.java
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/ThreeWindingsTransformerNetworkFactory.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NetworkXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/XMLImporter.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/NodeBreakerInternalConnectionsTest.java
  loadflow/loadflow-results-completion/src/test/java/com/powsybl/loadflow/resultscompletion/LoadFlowResultsCompletionZ0FlowsTest.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/TestingNetworkFactory.java
  ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteImporter.java
Labels: Deprecated
