Repository powsybl/powsybl-core, pull requests merged in 2020-02, with the labels that each got.

#1134 Switch to new Graphviz library
  iidm/iidm-api/pom.xml
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/GraphvizConnectivity.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusBreakerVoltageLevel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/VoltageLevelExportTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/util/GraphvizConnectivityTest.java
  iidm/iidm-impl/src/test/resources/eurostag-tutorial-example1-vlhv1.dot
  iidm/iidm-impl/src/test/resources/eurostag-tutorial-example1.dot
  iidm/iidm-impl/src/test/resources/fictitious-switch-c.dot
  pom.xml
Labels: PR: ready-to-be-merged, Quality

#1119 Allow to choose the name of the default iidm implementation instead o…
  action/action-dsl/pom.xml
  action/action-util/pom.xml
  commons/src/main/java/com/powsybl/commons/config/PlatformConfigNamedProvider.java
  commons/src/test/java/com/powsybl/commons/config/PlatformConfigNamedProviderTest.java
  contingency/contingency-api/pom.xml
  contingency/contingency-dsl/pom.xml
  dynamic-simulation/dynamic-simulation-api/src/main/java/com/powsybl/dynamicsimulation/DynamicSimulation.java
  dynamic-simulation/dynamic-simulation-api/src/main/java/com/powsybl/dynamicsimulation/DynamicSimulationProvider.java
  dynamic-simulation/dynamic-simulation-api/src/test/java/com/powsybl/dynamicsimulation/DynamicSimulationTest.java
  entsoe-util/pom.xml
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/NetworkFactory.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/NetworkFactoryService.java
  iidm/iidm-comparator/pom.xml
  iidm/iidm-converter-api/pom.xml
  iidm/iidm-extensions/pom.xml
  iidm/iidm-mergingview/pom.xml
  iidm/iidm-reducer/pom.xml
  iidm/iidm-util/pom.xml
  loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlow.java
  loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowProvider.java
  loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowTest.java
Labels: Configuration, Deprecated, Doc needed, IIDM, PR: ready-to-be-merged

#1085 spurious share/java/apache-jena-libs-3.0.0.pom file in itools distribution #753
  pom.xml
  triple-store/triple-store-impl-jena/pom.xml
Labels: PR: ready-to-be-merged

#1140 Fix LazyCreatedComputationManager
  computation/src/main/java/com/powsybl/computation/LazyCreatedComputationManager.java
Labels: Computation, PR: ready-to-be-merged, bug

#1146 Change ieeecdf format
  ieee-cdf/ieee-cdf-converter/src/main/java/com/powsybl/ieeecdf/converter/IeeeCdfImporter.java
  ieee-cdf/ieee-cdf-converter/src/test/java/com/powsybl/ieeecdf/converter/IeeeCdfImporterTest.java
  ieee-cdf/ieee-cdf-converter/src/test/resources/ieee118cdf.xiidm
  ieee-cdf/ieee-cdf-converter/src/test/resources/ieee14cdf-solved.xiidm
  ieee-cdf/ieee-cdf-converter/src/test/resources/ieee14cdf.xiidm
  ieee-cdf/ieee-cdf-converter/src/test/resources/ieee300cdf.xiidm
  ieee-cdf/ieee-cdf-converter/src/test/resources/ieee30cdf.xiidm
  ieee-cdf/ieee-cdf-converter/src/test/resources/ieee57cdf.xiidm
  ieee-cdf/ieee-cdf-converter/src/test/resources/ieee9cdf.xiidm
Labels: Breaking Change

#1135 Restore previous javadoc aggregate behavior for releases
  pom.xml
Labels: PR: not-assigned

#1157 InternalConnectionAdder should not inherit from IdentifiableAdder
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java
  iidm/iidm-tck/src/main/java/com/powsybl/iidm/network/tck/AbstractEmptyCalculatedBusBugTest.java
Labels: Breaking Change

#1147 Bug fix: ensure that traversers searching a terminal do no set back to null if a terminal is found
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/CalculatedBusImpl.java
Labels: PR: ready-to-be-merged, bug

#1130 Merging view step : MergedLine adapter implementation
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/DanglingLineAdderAdapter.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/HvdcLineAdderAdapter.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/LineAdderAdapter.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergedLine.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergingNetworkListener.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergingView.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergingViewIndex.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/VoltageLevelAdapter.java
  iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/DanglingLineAdapterTest.java
  iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/LineAdapterTest.java
  iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/MergingNetworkTest.java
Labels: PR: ready-to-be-merged

#1003 Add more accepted iidm extensions
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/XMLImporter.java
Labels: PR: ready-to-be-merged, XIIDM

#1158 Obtain voltage level from terminal through node-breaker or bus-branch node
  .gitignore
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/SubstationIdMapping.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractConductingEquipmentConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SvInjectionConversion.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/AbstractCgmesModel.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesModel.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesModelFactory.java
  cgmes/cgmes-model/src/test/java/com/powsybl/cgmes/model/test/FakeCgmesModel.java
Labels: CGMES, PR: ready-to-be-merged

#1166 Fix Ucte element order code rule
  ucte/ucte-network/src/main/java/com/powsybl/ucte/network/UcteElementId.java
Labels: PR: ready-to-be-merged, UCTE, bug

#1168 Javadoc jar for loadflow-scripting
  loadflow/loadflow-scripting/pom.xml
  pom.xml
Labels: PR: waiting-for-review

#1156 Handle switches missing equipment container in CGMES conversion
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SwitchConversion.java
Labels: CGMES, PR: ready-to-be-merged, bug

#1159 Loadflow validation. Fix static var compensator check. Extend to remote control
  loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/StaticVarCompensatorsValidation.java
  loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/io/AbstractValidationFormatterWriter.java
  loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/io/ValidationFormatterCsvMultilineWriter.java
  loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/io/ValidationFormatterCsvWriter.java
  loadflow/loadflow-validation/src/main/java/com/powsybl/loadflow/validation/io/ValidationWriter.java
  loadflow/loadflow-validation/src/test/java/com/powsybl/loadflow/validation/StaticVarCompensatorsValidationTest.java
  loadflow/loadflow-validation/src/test/java/com/powsybl/loadflow/validation/io/AbstractValidationFormatterWriterTest.java
  loadflow/loadflow-validation/src/test/java/com/powsybl/loadflow/validation/io/ValidationFormatterCsvMultilineWriterTest.java
  loadflow/loadflow-validation/src/test/java/com/powsybl/loadflow/validation/io/ValidationFormatterCsvWriterTest.java
Labels: Breaking Change, Doc needed, Loadflow validation, PR: ready-to-be-merged

#1175 Make iidm-tck a test-jar; fixes $ mvn compile
  iidm/iidm-impl/pom.xml
  iidm/iidm-tck/pom.xml
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractBatteryTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractBusTerminalTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractBusTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractCalculatedTopologyTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractConnectedComponentWithTieLineBugTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractCurrentLimitsTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractDanglingLineTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractEmptyCalculatedBusBugTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractExceptionIsThrownWhenRemoveVariantAndWorkingVariantIsNotSetTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractFictitiousSwitchTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractGeneratorTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractHvdcLineTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractIdentifiableExtensionTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractLccTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractLineTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractLoadTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractMainConnectedComponentWithSwitchTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractManipulationsOnVariantsTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractMergeNetworkTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractMinMaxReactiveLimitsTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractMultiVariantNetworkTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNetworkRemoveTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNetworkTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNetworksTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNodeBreakerDisconnectionDoublePathBugTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNodeBreakerInternalConnectionsTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNodeBreakerTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNullPointerWhenRemovingMergedLineBugTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractReactiveCapabilityCurveTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractShuntCompensatorTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractStaticVarCompensatorTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractSubstationTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractSwitchOpenCloseNodeBreakerTopoTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractSwitchSetRetainedTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractTapChangerTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractThreeWindingsTransformerTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractTopologyTraverserTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractTwoWindingsTransformerTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractVoltageLevelExportTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractVoltageLevelTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractVscTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/internal/AbstractTransformerTest.java
  iidm/iidm-tck/src/test/resources/eurostag-tutorial-example1-vlhv1.dot
  iidm/iidm-tck/src/test/resources/eurostag-tutorial-example1.dot
  iidm/iidm-tck/src/test/resources/fictitious-switch-c.dot
Labels: PR: waiting-for-review, Quality

#1138 Support writing IIDM-XML network extensions in previous versions
  commons/src/main/java/com/powsybl/commons/extensions/ExtensionXmlSerializer.java
  iidm/iidm-converter-api/src/main/java/com/powsybl/iidm/export/ExportOptions.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NetworkXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NetworkXmlWriterContext.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/XMLExporter.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/AbstractVersionableNetworkExtensionXmlSerializer.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/IdentifiableExtensionXmlSerializerTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/TerminalMockXmlSerializer.java
  iidm/iidm-xml-converter/src/test/resources/V1_1/eurostag-tutorial-example1-with-loadMockExt-1_1.xml
  iidm/iidm-xml-converter/src/test/resources/V1_1/eurostag-tutorial-example1-with-loadMockExt-1_2.xml
  iidm/iidm-xml-converter/src/test/resources/com/powsybl/config/test/config.yml
  iidm/iidm-xml-converter/src/test/resources/com/powsybl/config/test/filelist.txt
Labels: IIDM, PR: ready-to-be-merged, XIIDM, help wanted

#1176 Remove useless properties
  loadflow/loadflow-scripting/pom.xml
Labels: Configuration, PR: ready-to-be-merged

#1152 Allow to have different implementations of extensions
  commons/src/main/java/com/powsybl/commons/extensions/AbstractExtendable.java
  commons/src/main/java/com/powsybl/commons/extensions/AbstractExtensionAdder.java
  commons/src/main/java/com/powsybl/commons/extensions/Extendable.java
  commons/src/main/java/com/powsybl/commons/extensions/ExtensionAdder.java
  commons/src/main/java/com/powsybl/commons/extensions/ExtensionAdderProvider.java
  commons/src/main/java/com/powsybl/commons/extensions/ExtensionAdderProviders.java
  commons/src/test/java/com/powsybl/commons/extensions/ExtensionAdderProvidersTest.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/AbstractIdentifiableAdapter.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergedLine.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergingView.java
Labels: PR: ready-to-be-merged, extensions

#1178 add AbstractXmlConverterTest.getVersionedNetworkAsStream method in test
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/AbstractXmlConverterTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/IdentifiableExtensionXmlSerializerTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/OptionalLoadTypeBugTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/SimpleAnonymizerTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/StaticVarCompensatorXmlTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/ThreeWindingsTransformerXmlTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/TopologyLevelTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/XMLExporterTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/XMLImporterExporterBaseExtensionsTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/XMLImporterLimitsTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/XmlExporterBaseExtensionsTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/XmlExporterBaseOneExtensionPerFileTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/XmlExporterImporterBaseOneExtensionPerFileTest.java
Labels: PR: ready-to-be-merged, Quality, XIIDM

#1182 Add AbstractXmlConverterTest.getVersionedNetworkPath method
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/AbstractXmlConverterTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/BatteryXmlTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/EurostagXmlTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/FictitiousSwitchTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/HvdcXmlTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/IdentifiableExtensionXmlSerializerTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/NetworkXmlTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/NodeBreakerInternalConnectionsTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/PhaseShifterXmlTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/ReactiveLimitsXmlTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/SimpleAnonymizerTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/StaticVarCompensatorXmlTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/ThreeWindingsTransformerXmlTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/TopologyLevelTest.java
Labels: XIIDM, enhancement

#1189 Fix groovydoc attachment in powsybl-loadflow-scripting
  loadflow/loadflow-scripting/pom.xml
  pom.xml
Labels: PR: ready-to-be-merged, bug

#1170 Voltage and angle by bus in node/breaker topology
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/Networks.java
  iidm/iidm-api/src/test/java/com/powsybl/iidm/network/CoverageTest.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/BusbarSectionXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/VoltageLevelXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/util/IidmXmlUtil.java
  iidm/iidm-xml-converter/src/main/resources/xsd/iidm_V1_1.xsd
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/IidmXmlUtilTest.java
  iidm/iidm-xml-converter/src/test/resources/V1_1/LccRoundTripRef.xml
  iidm/iidm-xml-converter/src/test/resources/V1_1/fictitiousSwitchRef.xml
Labels: Breaking Change, PR: ready-to-be-merged, XIIDM

#1165 Extensionpowercontrol
  commons/src/main/java/com/powsybl/commons/extensions/Extension.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ActivePowerControl.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ActivePowerControlAdder.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ActivePowerControlAdderImpl.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ActivePowerControlAdderImplProvider.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ActivePowerControlImpl.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ActivePowerControlXmlSerializer.java
  iidm/iidm-extensions/src/test/java/com/powsybl/iidm/network/extensions/ActivePowerControlTest.java
  iidm/iidm-extensions/src/test/java/com/powsybl/iidm/network/extensions/ActivePowerControlXmlTest.java
Labels: Breaking Change, PR: ready-to-be-merged

#1188 Fix: do not throw exceptions anymore when unexpected new T3W attributes during XIIDM import + clean up of unused methods
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/ThreeWindingsTransformerXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/util/IidmXmlUtil.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/IidmXmlUtilTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/ThreeWindingsTransformerXmlTest.java
  iidm/iidm-xml-converter/src/test/resources/V1_1/faultyThreeWindingsTransformerRoundTripRef.xml
Labels: PR: waiting-for-review, XIIDM

#1191 Make ActivePowerControl extension and its adder public
  entsoe-util/src/main/java/com/powsybl/entsoe/util/Xnode.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ActivePowerControl.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ActivePowerControlAdder.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ActivePowerControlImpl.java
Labels: PR: waiting-for-review, bug

#1169 SecurityAnalysisImpl multithread fixes alternative implementations
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/SecurityAnalysisImpl.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/SecurityAnalysisTest.java
Labels: PR: corrected, PR: waiting-for-review, Security Analysis, bug
