Repository powsybl/powsybl-core, pull requests merged in 2021-07, with the labels that each got.

#1781 Add backward compatibility to Importer.importData(ReadOnlyDataSource, NetworkFactory, Properties, Reporter)
  iidm/iidm-converter-api/src/main/java/com/powsybl/iidm/import_/Importer.java
Labels: IIDM

#1765 Fix IEEE CDF nominal voltage import
  ieee-cdf/ieee-cdf-converter/src/main/java/com/powsybl/ieeecdf/converter/IeeeCdfImporter.java
  ieee-cdf/ieee-cdf-converter/src/main/java/com/powsybl/ieeecdf/converter/IeeeCdfNetworkFactory.java
  ieee-cdf/ieee-cdf-converter/src/test/resources/ieee118cdf.xiidm
  ieee-cdf/ieee-cdf-converter/src/test/resources/ieee14cdf.xiidm
  ieee-cdf/ieee-cdf-converter/src/test/resources/ieee300cdf.xiidm
  ieee-cdf/ieee-cdf-converter/src/test/resources/ieee30cdf.xiidm
  ieee-cdf/ieee-cdf-converter/src/test/resources/ieee9cdf.xiidm
Labels: PR: ready-to-be-merged

#1777 Clean code: control areas are now imported, method addCgmesSshControlAreas can be deleted
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
Labels: PR: waiting-for-review

#1780 Allow Xnodes connected to more than 2 Nodes to be imported correctly.
  ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteImporter.java
  ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/UcteExporterTest.java
  ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/UcteImporterTest.java
  ucte/ucte-converter/src/test/resources/xnodeOneClosedLine.uct
  ucte/ucte-converter/src/test/resources/xnodeThreeClosedLine.uct
  ucte/ucte-converter/src/test/resources/xnodeTwoClosedLine.uct
Labels: PR: ready-to-be-merged, UCTE

#1782 Add methods to get measurements by type
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/DiscreteMeasurements.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/Measurements.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/DiscreteMeasurementsImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/MeasurementsImpl.java
Labels: IIDM, PR: ready-to-be-merged

#1783 Reporter POC: fix deserialization with no specified dictionary
  commons/src/main/java/com/powsybl/commons/reporter/AbstractReporter.java
  commons/src/main/java/com/powsybl/commons/reporter/Report.java
  commons/src/main/java/com/powsybl/commons/reporter/ReportBuilder.java
  commons/src/main/java/com/powsybl/commons/reporter/Reporter.java
  commons/src/main/java/com/powsybl/commons/reporter/ReporterModel.java
  commons/src/main/java/com/powsybl/commons/reporter/ReporterModelDeserializer.java
  commons/src/main/java/com/powsybl/commons/reporter/ReporterModelJsonModule.java
  commons/src/main/java/com/powsybl/commons/reporter/ReporterModelSerializer.java
  commons/src/main/java/com/powsybl/commons/reporter/TypedValue.java
  commons/src/main/java/com/powsybl/commons/reporter/package-info.java
  ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/UcteImporterReporterTest.java
Labels: PR: ready-to-be-merged

#1791 Add backward compatibility to LoadFlowProvider.run and SensitivityAnalysisProvider.run with reporter
  loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowProvider.java
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityAnalysisProvider.java
Labels: PR: ready-to-be-merged

#1792 Fix report deserialize corner case
  commons/src/main/java/com/powsybl/commons/reporter/ReporterModelDeserializer.java
  ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/UcteImporterReporterTest.java
Labels: PR: ready-to-be-merged

#1786 Expose exporter parameters
  ampl-converter/src/main/java/com/powsybl/ampl/converter/AmplExporter.java
  ampl-converter/src/test/java/com/powsybl/ampl/converter/AmplNetworkWriterTest.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportContextTest.java
  iidm/iidm-converter-api/src/main/java/com/powsybl/iidm/export/Exporter.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/XMLExporter.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/XMLExporterTest.java
  ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteExporter.java
  ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/UcteExporterTest.java
Labels: PR: ready-to-be-merged
