Repository powsybl/powsybl-core, pull requests merged in 2022-12, with the labels that each got.

#2382 Refactoring: create TripleStoreUtils with method to query catalog (used in post processors)
  cgmes/cgmes-measurements/src/main/java/com/powsybl/cgmes/measurements/CgmesMeasurementsModel.java
  cgmes/cgmes-shortcircuit/src/main/java/com/powsybl/cgmes/shorcircuit/CgmesShortCircuitModel.java
  triple-store/triple-store-api/pom.xml
  triple-store/triple-store-api/src/main/java/com/powsybl/triplestore/api/TripleStoreUtils.java
  triple-store/triple-store-api/src/test/java/com/powsybl/triplestore/api/test/TripleStoreUtilsTest.java
Labels: Triplestore, PR: ready-to-be-merged

#2355 Allow to create feeder bays in a bus-breaker voltage level
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AbstractCreateConnectableFeederBays.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateBranchFeederBays.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateBranchFeederBaysBuilder.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateFeederBay.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateFeederBayBuilder.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ModificationReports.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/TopologyModificationUtils.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateBranchFeederBaysTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateFeederBayTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/RemoveFeederBayTest.java
  iidm/iidm-modification/src/test/resources/eurostag-create-line-feeder-bays.xml
  iidm/iidm-modification/src/test/resources/eurostag-create-load-feeder-bay.xml
  iidm/iidm-modification/src/test/resources/eurostag-create-twt-feeder-bays.xml
Labels: Deprecated, Modification

#2385 Feeders' names in ConnectablePosition are optional
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ConnectablePosition.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ConnectablePositionImpl.java
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-equipments-bbs1.xml
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-generator-bbs1.xml
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-internal-line.xml
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-line-order-used.xml
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-line.xml
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-load-bbs4.xml
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-twt-feeders-bbs.xml
  iidm/iidm-modification/src/test/resources/testNetworkNodeBreaker.xiidm
  iidm/iidm-modification/src/test/resources/testNetworkNodeBreakerWithCouplingDeviceDifferentSectionIndex.xml
  iidm/iidm-modification/src/test/resources/testNetworkNodeBreakerWithCouplingDeviceSameSectionIndex.xml
  iidm/iidm-modification/src/test/resources/testNetworkNodeBreakerWithoutExtensions.xiidm
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractNetworkExtensionsTest.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/ConnectablePositionXmlSerializer.java
  iidm/iidm-xml-converter/src/main/resources/xsd/connectablePosition_V1_0.xsd
  iidm/iidm-xml-converter/src/main/resources/xsd/connectablePosition_V1_1.xsd
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/extensions/ConnectablePositionXmlTest.java
  iidm/iidm-xml-converter/src/test/resources/connectablePositionRef_V1_0.xml
  iidm/iidm-xml-converter/src/test/resources/connectablePositionRef_V1_1.xml
Labels: Breaking Change, PR: ready-to-be-merged

#2284 [Network Modification] Move method returning feeder by connectable in TopologyModificationUtils from pypowsybl
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AbstractCreateConnectableFeederBays.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AbstractLineConnectionModification.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/TopologyModificationUtils.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/TopologyModificationUtilsTest.java
Labels: Modification

#2393 Import ignored ACLineSegment linked to boundary as dangling lines
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
Labels: CGMES, PR: next-release

#2389 If two dangling lines with the same Xnode are in the same geographical region in a CGMES file, they are not merged
  cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/CgmesConformity1ModifiedCatalog.java
  cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_unmerged_xnode/MicroGridTestConfiguration_BC_BE_EQ_V2.xml
  cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_unmerged_xnode/MicroGridTestConfiguration_BC_BE_TP_V2.xml
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractConductingEquipmentConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/BoundaryLine.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EquivalentInjectionConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/TopologyExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/EquipmentExportTest.java
Labels: CGMES, PR: ready-to-be-merged, PR: next-release

#2402 Active Power Control extension: add participationFactor
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ActivePowerControl.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ActivePowerControlAdder.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ActivePowerControlAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ActivePowerControlImpl.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractActivePowerControlTest.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/ActivePowerControlXmlSerializer.java
  iidm/iidm-xml-converter/src/main/resources/xsd/activePowerControl_V1_0.xsd
  iidm/iidm-xml-converter/src/main/resources/xsd/activePowerControl_V1_1.xsd
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/extensions/ActivePowerControlXmlTest.java
  iidm/iidm-xml-converter/src/test/resources/V1_5/activePowerControlRoundTripRef.xml
  iidm/iidm-xml-converter/src/test/resources/V1_6/activePowerControlRoundTripRef.xml
  iidm/iidm-xml-converter/src/test/resources/V1_7/activePowerControlRoundTripRef.xml
  iidm/iidm-xml-converter/src/test/resources/V1_8/activePowerControlRoundTripRef.xml
  loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java
Labels: PR: ready-to-be-merged

#2409 Compression - support zstd and xz formats
  commons/pom.xml
  commons/src/main/java/com/powsybl/commons/datasource/CompressionFormat.java
  commons/src/main/java/com/powsybl/commons/datasource/DataSourceUtil.java
  commons/src/main/java/com/powsybl/commons/datasource/GenericReadOnlyDataSource.java
  commons/src/main/java/com/powsybl/commons/datasource/XZFileDataSource.java
  commons/src/main/java/com/powsybl/commons/datasource/ZstdFileDataSource.java
  commons/src/test/java/com/powsybl/commons/datasource/CompressionFormatTest.java
  commons/src/test/java/com/powsybl/commons/datasource/XZFileDataSourceTest.java
  commons/src/test/java/com/powsybl/commons/datasource/ZstdFileDataSourceTest.java
  pom.xml
Labels: PR: ready-to-be-merged, PR: next-release

#2376 Import/Export CGMES Profiles IDs if present (EQ, TP, SSH, EQ_BD and TP_BD)
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/ModelDescriptionEq.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/ExportXmlCompare.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/StateVariablesExportTest.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesNamespace.java
Labels: CGMES, Breaking Change, PR: next-release

#2397 PSSE: Admit special characters
  psse/psse-converter/src/test/java/com/powsybl/psse/converter/PsseExporterTest.java
  psse/psse-converter/src/test/java/com/powsybl/psse/converter/PsseImporterTest.java
  psse/psse-converter/src/test/resources/RawCaseWithSpecialCharacters.raw
  psse/psse-converter/src/test/resources/RawCaseWithSpecialCharacters.xiidm
  psse/psse-converter/src/test/resources/RawCaseWithSpecialCharacters_exported.raw
  psse/psse-converter/src/test/resources/RawxCaseWithSpecialCharacters.rawx
  psse/psse-converter/src/test/resources/RawxCaseWithSpecialCharacters.xiidm
  psse/psse-converter/src/test/resources/RawxCaseWithSpecialCharacters_exported.rawx
  psse/psse-model/src/main/java/com/powsybl/psse/model/io/FileFormat.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/io/RecordGroupIOJson.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/io/RecordGroupIOLegacyText.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/pf/io/PowerFlowRawData32.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/pf/io/PowerFlowRawData33.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/pf/io/PowerFlowRawData35.java
Labels: PR: next-release

#2415 NetworkStateComparator: added three windings transformers comparison
  iidm/iidm-comparator/src/main/java/com/powsybl/iidm/comparator/NetworkStateComparator.java
  iidm/iidm-comparator/src/test/java/com/powsybl/iidm/comparator/NetworkStateComparatorTest.java
Labels: PR: next-release

#2410 Fix UCTE importer conventions of PST active power flow regulation
  ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteExporter.java
  ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteImporter.java
  ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/UcteExporterTest.java
  ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/UcteImporterTest.java
  ucte/ucte-converter/src/test/resources/phaseShifterActivePowerOn.uct
Labels: PR: ready-to-be-merged

#2416 Add bus contingency
  contingency/contingency-api/src/main/java/com/powsybl/contingency/BusContingency.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/Contingency.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/ContingencyBuilder.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/ContingencyElementType.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/json/ContingencyElementDeserializer.java
  contingency/contingency-api/src/test/java/com/powsybl/contingency/BusContingencyTest.java
  contingency/contingency-api/src/test/java/com/powsybl/contingency/json/ContingencyJsonTest.java
  contingency/contingency-api/src/test/java/com/powsybl/contingency/tasks/BusTrippingTest.java
  contingency/contingency-api/src/test/resources/contingency.json
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/tripping/BusTripping.java
Labels: PR: next-release

#2400 PSSE: Allow transformers with NOMV=0
  psse/psse-converter/src/test/java/com/powsybl/psse/converter/PsseImporterTest.java
  psse/psse-converter/src/test/resources/TransformersWithZeroNomV.raw
  psse/psse-converter/src/test/resources/TransformersWithZeroNomV.xiidm
  psse/psse-model/src/main/java/com/powsybl/psse/model/pf/PsseValidation.java
  psse/psse-model/src/test/resources/IEEE_14_bus_invalid.txt
Labels: PR: next-release

#2399 PSSE: Do not consider isolated buses with type 3 as slacks
  psse/psse-converter/src/main/java/com/powsybl/psse/converter/SlackConverter.java
  psse/psse-converter/src/test/java/com/powsybl/psse/converter/PsseImporterTest.java
  psse/psse-converter/src/test/resources/IsolatedSlackBus.raw
  psse/psse-converter/src/test/resources/IsolatedSlackBus.xiidm
Labels: PR: next-release

#2419 Vulnerabilities fixes
  pom.xml
Labels: PR: ready-to-be-merged, PR: next-release, Quality, vulnerability

#2420 Fix SVC bMin/bMax during CGMES if capacitive and/or inductive rating are undefined or 0
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/StaticVarCompensatorConversion.java
Labels: CGMES, PR: ready-to-be-merged, PR: next-release
