Repository powsybl/powsybl-core, pull requests merged in 2022-09, with the labels that each got.

#2236 Improve dense matrix multiplication and addition performance
  math/src/main/java/com/powsybl/math/matrix/AbstractMatrix.java
  math/src/main/java/com/powsybl/math/matrix/DenseMatrix.java
  math/src/main/java/com/powsybl/math/matrix/Matrix.java
  math/src/main/java/com/powsybl/math/matrix/SparseMatrix.java
  math/src/test/java/com/powsybl/math/matrix/AbstractMatrixTest.java
  math/src/test/java/com/powsybl/math/matrix/DenseMatrixTest.java
Labels: PR: next-release

#2251 fix lineConnectionAction deserializer
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/ActionDeserializer.java
Labels: bug

#2218 Proposition for network modification builder
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ConnectVoltageLevelOnLine.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ConnectVoltageLevelOnLineBuilder.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateLineOnLine.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateLineOnLineBuilder.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/ConnectVoltageLevelOnLineTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateLineOnLineTest.java
  iidm/iidm-modification/src/test/resources/fictitious-line-split-l-complete.xml
  iidm/iidm-modification/src/test/resources/fictitious-line-split-vl-complete.xml
Labels: Deprecated, PR: ready-to-be-merged, PR: next-release, Modification

#2186 Sensitivity analysis: add contingency status in the results
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityAnalysis.java
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityAnalysisProvider.java
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityAnalysisResult.java
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityAnalysisTool.java
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityResultCsvWriter.java
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityResultJsonWriter.java
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityResultModelWriter.java
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityResultWriter.java
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityValueJsonWriter.java
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/json/SensitivityAnalysisResultDeserializer.java
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/json/SensitivityAnalysisResultSerializer.java
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/json/SensitivityContingencyStatusJsonDeserializer.java
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/json/SensitivityContingencyStatusJsonSerializer.java
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/json/SensitivityJsonModule.java
  sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisParametersTest.java
  sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisProviderMock.java
  sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisResultTest.java
  sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisTest.java
  sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisToolTest.java
  sensitivity-analysis-api/src/test/resources/SensitivityAnalysisResultRefV1.json
  sensitivity-analysis-api/src/test/resources/contingencyStatusRef.json
Labels: PR: next-release

#2214 Network modification: create feeder bay
  iidm/iidm-modification/pom.xml
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/NetworkModification.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateFeederBay.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateFeederBayBuilder.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ModificationReports.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/TopologyModificationUtils.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateFeederBayTest.java
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-equipments-bbs1.xml
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-generator-bbs1.xml
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-load-bbs1.xml
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-load-vl1.xml
  iidm/iidm-modification/src/test/resources/testNetworkNodeBreaker.xiidm
  iidm/iidm-modification/src/test/resources/testNetworkNodeBreakerWithoutExtensions.xiidm
Labels: PR: ready-to-be-merged, PR: next-release

#2250 Move some classes from converter-api to xml-converter
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/EquipmentExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/StateVariablesExportTest.java
  iidm/iidm-converter-api/src/main/java/com/powsybl/iidm/IidmImportExportMode.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractConnectableXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractConverterContext.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractNetworkXmlContext.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractOptions.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/BusFilter.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/ExportOptions.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/ImportOptions.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NetworkXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NetworkXmlReaderContext.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NetworkXmlWriterContext.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/XMLExporter.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/XMLImporter.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/anonymizer/Anonymizer.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/anonymizer/FakeAnonymizer.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/anonymizer/SimpleAnonymizer.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/util/IidmXmlUtil.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/AbstractXmlConverterTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/DanglingLineXmlTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/EncodingTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/ExportOptionsTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/IdentifiableExtensionXmlSerializerTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/IidmXmlUtilTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/ImportOptionsTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/LoadingLimitsBugTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/LoadingLimitsXmlTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/NetworkXmlTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/ShuntCompensatorXmlTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/StaticVarCompensatorXmlTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/TopologyLevelTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/extensions/BranchObservabilityXmlTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/extensions/GeneratorStartupXmlTest.java
Labels: Breaking Change, PR: ready-to-be-merged

#2253 PreContingencyResult: correct method name
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/PreContingencyResultSerializer.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/results/PreContingencyResult.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/converter/ExporterTest.java
  security-analysis/security-analysis-default/src/test/java/com/powsybl/security/impl/SecurityAnalysisTest.java
Labels: Breaking Change, PR: ready-to-be-merged

#2254 Fix CreateFeederBayTest
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateFeederBayTest.java
Labels: PR: ready-to-be-merged, PR: next-release

#2239 Add convenient methods to retrieve bus-breaker buses from bus-branch bus ID
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusBreakerVoltageLevel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/BusBreakerVoltageLevelAdapter.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/NodeBreakerVoltageLevelAdapter.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractCalculatedTopologyTest.java
Labels: IIDM, PR: ready-to-be-merged, PR: next-release

#2256 Fix baseLoadTest
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateFeederBayTest.java
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-load-bbs1.xml
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-load-bbs4.xml
Labels: PR: ready-to-be-merged

#2255 Improve import/export parameters description
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/NamingStrategyFactory.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/CgmesImportPostProcessorTest.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesNamespace.java
  commons/src/main/java/com/powsybl/commons/parameters/Parameter.java
  commons/src/main/java/com/powsybl/commons/parameters/ParameterScope.java
  commons/src/test/java/com/powsybl/commons/parameters/ParameterTest.java
Labels: Configuration, PR: ready-to-be-merged, PR: next-release

#2252 Clean NetworkModification interface and implementations of complicated override methods
  action/action-dsl/src/main/java/com/powsybl/action/dsl/modification/ScriptNetworkModification.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/AbstractNetworkModification.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/CloseSwitch.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/ConnectGenerator.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/GeneratorModification.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/NetworkModification.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/NetworkModificationList.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/OpenSwitch.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/PhaseShifterOptimizeTap.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/PhaseShifterSetAsFixedTap.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/PhaseShifterShiftTap.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ConnectVoltageLevelOnLine.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateFeederBay.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateLineOnLine.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/tripping/AbstractTripping.java
  security-analysis/security-analysis-default/src/test/java/com/powsybl/security/impl/SecurityAnalysisTest.java
Labels: Breaking Change, PR: ready-to-be-merged, PR: next-release, Modification

#2248 PowerFactory: fix updates of voltages
  powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/VoltageAndAngle.java
  powerfactory/powerfactory-converter/src/test/java/com/powsybl/powerfactory/converter/PowerFactoryImporterTest.java
  powerfactory/powerfactory-converter/src/test/resources/Switches-missing-angle.dgs
  powerfactory/powerfactory-converter/src/test/resources/Switches-missing-angle.xiidm
  powerfactory/powerfactory-converter/src/test/resources/Switches-missing-voltage.dgs
  powerfactory/powerfactory-converter/src/test/resources/Switches-missing-voltage.xiidm
  powerfactory/powerfactory-converter/src/test/resources/Switches-negative-voltage.dgs
  powerfactory/powerfactory-converter/src/test/resources/Switches-negative-voltage.xiidm
  powerfactory/powerfactory-converter/src/test/resources/Switches-without-bus.dgs
  powerfactory/powerfactory-converter/src/test/resources/Switches-without-bus.xiidm
Labels: bug, PR: ready-to-be-merged, PR: next-release

#2242 Phase tap changer tap position action
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/action/PhaseTapChangerTapPositionAction.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/ActionDeserializer.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/ActionSerializer.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/json/JsonActionAndOperatorStrategyTest.java
  security-analysis/security-analysis-api/src/test/resources/ActionFileTest.json
  security-analysis/security-analysis-api/src/test/resources/WrongActionFileTest.json
  security-analysis/security-analysis-api/src/test/resources/WrongActionFileTest2.json
Labels: PR: ready-to-be-merged

#2259 Some fixes on network modification
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/TopologyModificationUtils.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateFeederBayTest.java
Labels: PR: ready-to-be-merged

#2209 Create utility class for compareXml/compareTxt for refactoring purposes
  ampl-converter/src/test/java/com/powsybl/ampl/converter/AmplNetworkWriterTest.java
  commons/src/test/java/com/powsybl/commons/AbstractConverterTest.java
  commons/src/test/java/com/powsybl/commons/ComparisonUtils.java
  dynamic-simulation/dynamic-simulation-api/src/test/java/com/powsybl/dynamicsimulation/json/JsonDynamicSimulationParametersTest.java
  ieee-cdf/ieee-cdf-converter/src/test/java/com/powsybl/ieeecdf/converter/IeeeCdfImporterTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/EncodingTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/IdentifiableExtensionXmlSerializerTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/LoadingLimitsXmlTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/SimpleAnonymizerTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/SkipExtensionTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/XMLExporterTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/extensions/LoadDetailXmlTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/extensions/SlackTerminalXmlTest.java
  loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/json/JsonLoadFlowParametersTest.java
  loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/tools/RunLoadFlowToolTest.java
  matpower/matpower-converter/src/test/java/com/powsybl/matpower/converter/MatpowerImporterTest.java
  powerfactory/powerfactory-converter/src/test/java/com/powsybl/powerfactory/converter/PowerFactoryImporterTest.java
  psse/psse-converter/src/test/java/com/powsybl/psse/converter/PsseExporterTest.java
  psse/psse-converter/src/test/java/com/powsybl/psse/converter/PsseImporterTest.java
  psse/psse-model/src/test/java/com/powsybl/psse/model/PsseRawDataTest.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/json/JsonSecurityAnalysisParametersTest.java
  sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisParametersTest.java
  shortcircuit-api/src/test/java/com/powsybl/shortcircuit/ShortCircuitParametersTest.java
  shortcircuit-api/src/test/java/com/powsybl/shortcircuit/converter/ShortCircuitAnalysisResultExportersTest.java
  ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/UcteExporterTest.java
Labels: Breaking Change, PR: ready-to-be-merged, PR: next-release

#2224 Powerfactory: Capability curve and minor changes
  powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/GeneratorConverter.java
  powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ShuntConverter.java
  powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/SwitchConverter.java
  powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/TransformerConverter.java
  powerfactory/powerfactory-converter/src/test/java/com/powsybl/powerfactory/converter/PowerFactoryImporterTest.java
  powerfactory/powerfactory-converter/src/test/resources/CapabilityCurve.dgs
  powerfactory/powerfactory-converter/src/test/resources/CapabilityCurve.xiidm
  powerfactory/powerfactory-converter/src/test/resources/ThreeWindingsTransformerWinding1Ratio.dgs
  powerfactory/powerfactory-converter/src/test/resources/ThreeWindingsTransformerWinding1Ratio.xiidm
Labels: PR: next-release

#2260 Increase sensitivity function and variable types to support ThreeWindingsTransformer
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityFunctionType.java
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityVariableType.java
  sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityFactorTest.java
Labels: PR: next-release

#2249 Transform line on line into voltage level on line
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ModificationReports.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ReplaceTeePointByVoltageLevelOnLine.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ReplaceTeePointByVoltageLevelOnLineBuilder.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/TopologyModificationUtils.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/ReplaceTeePointByVoltageLevelOnLineTest.java
  iidm/iidm-modification/src/test/resources/eurostag-replace-tee-point-by-voltage-level-on-line-bb.xml
  iidm/iidm-modification/src/test/resources/eurostag-replace-tee-point-by-voltage-level-on-line-nbbb.xml
  iidm/iidm-modification/src/test/resources/eurostag-revert-connect-voltage-level-on-line-bb-vl.xml
  iidm/iidm-modification/src/test/resources/eurostag-revert-connect-voltage-level-on-line-nb-vl.xml
  iidm/iidm-modification/src/test/resources/fictitious-replace-tee-point-by-voltage-level-on-line-nb.xml
  iidm/iidm-modification/src/test/resources/fictitious-revert-connect-voltage-level-on-line-vl.xml
Labels: PR: ready-to-be-merged

#2264 [Network modifications] Add method to get orders by connectable
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/TopologyModificationUtils.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateFeederBayTest.java
Labels: PR: next-release

#2263 Rework sensitivity analysis results
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityAnalysis.java
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityAnalysisResult.java
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityAnalysisTool.java
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityResultCsvWriter.java
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityResultJsonWriter.java
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityResultModelWriter.java
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityResultWriter.java
  sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisParametersTest.java
  sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisProviderMock.java
  sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisResultTest.java
  sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisTest.java
  sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisToolTest.java
Labels: PR: next-release

#2257 Create Hypothesis for creation of branch feeders
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AbstractCreateConnectableFeederBays.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateBranchFeederBays.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateBranchFeederBaysBuilder.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateFeederBay.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ModificationReports.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateBranchFeedersTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateFeederBayTest.java
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-line-feeders-bbs.xml
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-twt-feeders-bbs.xml
Labels: PR: next-release, Modification

#2268 [Network modifications] Support of internal branches
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/TopologyModificationUtils.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateBranchFeederBaysTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateFeederBayTest.java
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-internal-line.xml
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-line.xml
Labels: PR: next-release

#2271 allow to serialize redundancy equal to false
  commons/src/main/java/com/powsybl/commons/xml/XmlUtil.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ObservabilityQuality.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ObservabilityQualityImpl.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractBranchObservabilityTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractInjectionObservabilityTest.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/BranchObservabilityXmlSerializer.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/InjectionObservabilityXmlSerializer.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/extensions/InjectionObservabilityXmlTest.java
  iidm/iidm-xml-converter/src/test/resources/V1_6/branchObservabilityRoundTripRef.xml
  iidm/iidm-xml-converter/src/test/resources/V1_7/branchObservabilityRoundTripRef.xml
  iidm/iidm-xml-converter/src/test/resources/V1_8/branchObservabilityRoundTripRef.xml
  iidm/iidm-xml-converter/src/test/resources/V1_8/injectionObservabilityRoundTripRef.xml
Labels: Breaking Change, PR: ready-to-be-merged

#2265 Add PowerTransformerEnd.ratedS and SynchronousMachine.EquipmentContainer info during CGMES export
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/PowerTransformerEq.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/SynchronousMachineEq.java
Labels: bug, CGMES, PR: ready-to-be-merged, PR: next-release

#2269 [Network modifications] range fix in utility method
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/TopologyModificationUtils.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateBranchFeederBaysTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateFeederBayTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/TopologyModificationUtilsTest.java
Labels: PR: next-release

#2270 [Network modifications] Fix half-added line
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ConnectablePosition.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AbstractCreateConnectableFeederBays.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateBranchFeederBaysTest.java
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-line-order-used.xml
Labels: PR: next-release

#2273 Rename contingency status enum
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityAnalysisResult.java
  sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisParametersTest.java
  sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisProviderMock.java
  sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisResultTest.java
  sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisToolTest.java
  sensitivity-analysis-api/src/test/resources/SensitivityAnalysisResultRefV1.json
  sensitivity-analysis-api/src/test/resources/contingencyStatusRef.json
Labels: PR: ready-to-be-merged, PR: next-release

#2277 Bump snakeyaml to 1.31 (vulnerability [CVE-2022-25857])
  pom.xml
Labels: PR: next-release, vulnerability

#2278 Add configurable feeder names in hypotheses creating feeders' bays
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AbstractCreateConnectableFeederBays.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateBranchFeederBays.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateBranchFeederBaysBuilder.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateFeederBay.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateFeederBayBuilder.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateBranchFeederBaysTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateFeederBayTest.java
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-line.xml
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-load-bbs4.xml
Labels: PR: next-release, Modification

#2275 Add Metrix tuto 6 buses test network
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/test/MetrixTutorialSixBusesFactory.java
  iidm/iidm-xml-converter/src/main/resources/metrix-tutorial-6-buses-network.xiidm
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/test/MetrixTutorialSixBusesFactoryTest.java
Labels: PR: ready-to-be-merged, PR: next-release

#2274 fix observability adder
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/BranchObservability.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/BranchObservabilityAdder.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/InjectionObservability.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/InjectionObservabilityAdder.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/BranchObservabilityAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/BranchObservabilityImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/InjectionObservabilityAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/InjectionObservabilityImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/extensions/InjectionObservabilityTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractBranchObservabilityTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractInjectionObservabilityTest.java
Labels: PR: ready-to-be-merged, PR: next-release

#2279 Bump snakeyaml to 1.32 (fix vulnerability [CVE-2022-38752])
  pom.xml
Labels: PR: ready-to-be-merged, PR: next-release, vulnerability

#2292 Changes on network modifications: Do not use redundant voltage level ID in CreateLineOnLine and ConnectVoltageLevelOnLine + Rename attribute + Delete deprecated constructors
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AbstractLineConnectionModification.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ConnectVoltageLevelOnLine.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ConnectVoltageLevelOnLineBuilder.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateLineOnLine.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateLineOnLineBuilder.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/TopologyModificationUtils.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/ConnectVoltageLevelOnLineTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateLineOnLineTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/ReplaceTeePointByVoltageLevelOnLineTest.java
  iidm/iidm-modification/src/test/resources/eurostag-tutorial-example1.xml
Labels: IIDM, Breaking Change, PR: ready-to-be-merged, Modification

#2296 CGMES: consider station supply objects in import
  cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/CgmesConformity1ModifiedCatalog.java
  cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_station_supply/MicroGridTestConfiguration_BC_BE_EQ_V2.xml
  cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_station_supply/MicroGridTestConfiguration_BC_BE_SSH_V2.xml
  cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_station_supply/MicroGridTestConfiguration_BC_BE_TP_V2.xml
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EnergyConsumerConversion.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
  cgmes/cgmes-model/src/main/resources/CIM16.sparql
Labels: bug, CGMES, PR: next-release

#2283 BaseVoltage attribute exported in CGMES for PowerTransformerEnd
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/PowerTransformerEq.java
Labels: bug, CGMES, PR: ready-to-be-merged

#2297 add getConnectable(string) in network
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Network.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergingView.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNetworkTest.java
Labels: PR: ready-to-be-merged

#2301 Upgrade string template version
  pom.xml
  tools/pom.xml
Labels: PR: ready-to-be-merged

#2299 Add IEEE 33 and 69 buses network
  ieee-cdf/ieee-cdf-converter/src/main/java/com/powsybl/ieeecdf/converter/IeeeCdfImporter.java
  ieee-cdf/ieee-cdf-converter/src/main/java/com/powsybl/ieeecdf/converter/IeeeCdfNetworkFactory.java
  ieee-cdf/ieee-cdf-converter/src/main/resources/ieee33-bus.csv
  ieee-cdf/ieee-cdf-converter/src/main/resources/ieee33-line.csv
  ieee-cdf/ieee-cdf-converter/src/main/resources/ieee33-mesh.csv
  ieee-cdf/ieee-cdf-converter/src/main/resources/ieee69-bus.csv
  ieee-cdf/ieee-cdf-converter/src/main/resources/ieee69-line.csv
  ieee-cdf/ieee-cdf-converter/src/main/resources/ieee69-mesh.csv
  ieee-cdf/ieee-cdf-converter/src/test/java/com/powsybl/ieeecdf/converter/IeeeCdfImporterTest.java
  ieee-cdf/ieee-cdf-converter/src/test/resources/ieee33.xiidm
  ieee-cdf/ieee-cdf-converter/src/test/resources/ieee69.xiidm
Labels: PR: ready-to-be-merged

#2306 [Network modification] Fix extension creation in case of no connectables in the voltage level.
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AbstractCreateConnectableFeederBays.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateFeederBayTest.java
  iidm/iidm-modification/src/test/resources/network_one_voltage_level.xiidm
Labels: bug, IIDM, PR: ready-to-be-merged, Modification
