Repository powsybl/powsybl-core, pull requests merged in 2022-03, with the labels that each got.

#1989 Fix Load contingency deserialization
  contingency/contingency-api/src/main/java/com/powsybl/contingency/json/ContingencyElementDeserializer.java
  contingency/contingency-api/src/test/java/com/powsybl/contingency/json/ContingencyJsonTest.java
  contingency/contingency-api/src/test/resources/contingency.json
Labels: bug

#1986 Add new overload for loadNetwork and improve code in Importers
  iidm/iidm-converter-api/src/main/java/com/powsybl/iidm/import_/Importers.java
  iidm/iidm-converter-api/src/test/java/com/powsybl/iidm/import_/ImportersTest.java
Labels: PR: ready-to-be-merged

#1988 Improve loadflow results completion
  ieee-cdf/ieee-cdf-converter/src/test/java/com/powsybl/ieeecdf/converter/IeeeCdfImporterTest.java
  loadflow/loadflow-results-completion/src/main/java/com/powsybl/loadflow/resultscompletion/LoadFlowResultsCompletion.java
  matpower/matpower-converter/src/test/java/com/powsybl/matpower/converter/MatpowerImporterTest.java
Labels: IIDM

#1992 Fix: exists() method for CGMES should not rely on profiles identifiers in file name
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesOnDataSource.java
Labels: bug, CGMES, PR: ready-to-be-merged

#1993 Small fix in CgmesDiscretePostProcessor: when SwitchPosition, type is SWITCH_POSITION, not OTHER
  cgmes/cgmes-measurements/src/main/java/com/powsybl/cgmes/measurements/CgmesDiscretePostProcessor.java
Labels: bug, CGMES, PR: ready-to-be-merged, extensions

#1997 CGMES export to specific CIM version
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/ExportToCimVersionTest.java
Labels: CGMES, PR: ready-to-be-merged

#1999 Fix serializer of HvdcOperatorActivePowerRange: its attributes are optional
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/HvdcOperatorActivePowerRangeXmlSerializer.java
Labels: bug, PR: ready-to-be-merged, extensions

#1995 Refactor support for severity in functional logs
  commons/src/main/java/com/powsybl/commons/reporter/ReportBuilder.java
  commons/src/main/java/com/powsybl/commons/reporter/TypedValue.java
  commons/src/test/java/com/powsybl/commons/reporter/TypedValueTest.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/IidmReportConstants.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ValidationUtil.java
  ucte/ucte-converter/src/test/resources/frVoltageRegulatingXnodeReport.json
  ucte/ucte-converter/src/test/resources/parallelUcteImportReport.json
  ucte/ucte-network/src/main/java/com/powsybl/ucte/network/UcteNode.java
  ucte/ucte-network/src/main/java/com/powsybl/ucte/network/UcteValidation.java
  ucte/ucte-network/src/main/java/com/powsybl/ucte/network/ext/UcteReportConstants.java
Labels: PR: ready-to-be-merged

#1974 Bug fix: when removed, network components cannot access the network anymore
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractConnectable.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractTerminal.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractVoltageLevel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusTerminal.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeTerminal.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SubstationImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TerminalExt.java
  iidm/iidm-reducer/src/main/java/com/powsybl/iidm/reducer/DefaultNetworkReducer.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractBatteryTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractGeneratorTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractLineTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractSubstationTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractVoltageLevelTest.java
Labels: bug, IIDM, Breaking Change, PR: ready-to-be-merged

#2005 File data source lists names of files only if they start with basename
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/ConversionTester.java
  commons/src/main/java/com/powsybl/commons/datasource/FileDataSource.java
  commons/src/test/java/com/powsybl/commons/datasource/FileDataSourceTest.java
Labels: bug, PR: ready-to-be-merged

#1959 Improve CGMES-IIDM mapping
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ACLineSegmentConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractConductingEquipmentConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/TopologyExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportContextTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/EquipmentExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/StateVariablesExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/SteadyStateHypothesisExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/TopologyExportTest.java
  cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesIidmMapping.java
  cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesIidmMappingImpl.java
  cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesIidmMappingXmlSerializer.java
  cgmes/cgmes-extensions/src/main/resources/xsd/cgmesIidmMapping.xsd
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java
  math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java
Labels: CGMES, PR: waiting-for-review

#2006 CGMES-IIDM mapping: move the check for null TP nodes to the mapping
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractConductingEquipmentConversion.java
  cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesIidmMappingImpl.java
Labels: PR: ready-to-be-merged

#1991 Do not allow switches with the same node or bus at both ends.
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusBreakerVoltageLevel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/SwitchBusBreakerTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/SwitchNodeBreakerTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractSwitchBusBreakerTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractSwitchNodeBreakerTest.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractIdentifiableXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/BusBreakerViewSwitchXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NodeBreakerViewSwitchXml.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/AbstractXmlConverterTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/SwitchTest.java
  iidm/iidm-xml-converter/src/test/resources/switches/switchWithSameBusAtBothEnds.xiidm
  iidm/iidm-xml-converter/src/test/resources/switches/switchWithSameNodeAtBothEnds.xiidm
Labels: IIDM, PR: ready-to-be-merged

#2007 Bug fix: Invalidate network validation level after setting tap position or section count
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractTapChanger.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ShuntCompensatorImpl.java
Labels: bug, PR: waiting-for-review

#2008 Fix: CGMES exporter and importer return a correct list in `getParameters()`
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportContextTest.java
Labels: bug, PR: ready-to-be-merged

#2010 Quality: Fix typo ";;"
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/extensions/IdentifiableShortCircuitXmlSerializerTest.java
Labels: PR: ready-to-be-merged

#2021 Fix: Use platform config for CGMES export config
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java
Labels: bug, CGMES, PR: ready-to-be-merged

#2018 Fix: read configuration about CGMES import of control areas
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java
Labels: bug, CGMES, PR: ready-to-be-merged

#2011 Fix: when participation percentage is 0%, the scaled equipment is considered as saturated
  action/action-util/src/main/java/com/powsybl/action/util/ProportionalScalable.java
Labels: PR: ready-to-be-merged, Scalable

#2028 Update threeten and jackson libs
  pom.xml
Labels: PR: ready-to-be-merged

#1755 TieLine. Fix issues without modifying the boundary interface
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ACLineSegmentConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractConductingEquipmentConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/BoundaryLine.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/TieLine.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/BranchData.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/DanglingLineData.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/LinkData.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/ReorientedBranchCharacteristics.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/TieLineUtil.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/TwtData.java
  iidm/iidm-api/src/main/javadoc/com/powsybl/iidm/network/doc-files/TieLine.svg
  iidm/iidm-api/src/main/javadoc/com/powsybl/iidm/network/doc-files/TwoDanglingLinesToTieLine.svg
  iidm/iidm-api/src/main/javadoc/com/powsybl/iidm/network/doc-files/TwoLinesToTieLine.svg
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TieLineImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/TieLineTest.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/HalfLineAdapter.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergedLine.java
  iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/DanglingLineAdapterTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractLineTest.java
Labels: IIDM, CGMES, PR: ready-to-be-merged

#2026 Accept that scalable can be empty + throw exception if a percentage is undefined in ProportionalScalable
  action/action-util/src/main/java/com/powsybl/action/util/ProportionalScalable.java
  action/action-util/src/test/java/com/powsybl/action/util/ScalableTest.java
Labels: Scalable

#2031 Fix NPE when adding a line or 3 windings transformer on already used node
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/LineAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ThreeWindingsTransformerAdderImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/NpeWhenAdding3wtOrLineAndNodeAlreadyUsed.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNpeWhenAdding3wtOrLineAndNodeAlreadyUsed.java
Labels: PR: ready-to-be-merged

#1983 Geographical and ControlArea persistence
  cgmes/cgmes-conformity/src/test/java/com/powsybl/cgmes/conformity/test/CgmesConformity1NetworkCatalog.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SubstationConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/cim14/Cim14SmallCasesNetworkCatalog.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesMappingTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/ExportXmlCompare.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/SteadyStateHypothesisExportTest.java
  cgmes/cgmes-conversion/src/test/resources/cim14/7buses.xiidm
  cgmes/cgmes-conversion/src/test/resources/cim14/ieee14.xiidm
  cgmes/cgmes-conversion/src/test/resources/cim14/nordic32.xiidm
  cgmes/cgmes-conversion/src/test/resources/cim14/tx-from-microBE-adapted.xiidm
  cgmes/cgmes-model/src/test/java/com/powsybl/cgmes/model/test/FakeCgmesModel.java
Labels: PR: ready-to-be-merged, PR: next-release

#2017 Powerfactory improve parser
  powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ContainersMappingHelper.java
  powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/PowerFactoryImporter.java
  powerfactory/powerfactory-dgs/pom.xml
  powerfactory/powerfactory-dgs/src/main/java/com/powsybl/powerfactory/dgs/DgsParser.java
  powerfactory/powerfactory-dgs/src/main/java/com/powsybl/powerfactory/dgs/DgsReader.java
  powerfactory/powerfactory-dgs/src/test/java/com/powsybl/powerfactory/dgs/DgsDataTest.java
  powerfactory/powerfactory-dgs/src/test/resources/TwoBuses.dgs
  powerfactory/powerfactory-dgs/src/test/resources/TwoBuses.json
  powerfactory/powerfactory-dgs/src/test/resources/TwoBusesCommaAsDecimalSeparator.dgs
  powerfactory/powerfactory-dgs/src/test/resources/TwoBusesCommaAsDecimalSeparator.json
  powerfactory/powerfactory-model/pom.xml
  powerfactory/powerfactory-model/src/main/java/com/powsybl/powerfactory/model/DataClass.java
  powerfactory/powerfactory-model/src/main/java/com/powsybl/powerfactory/model/DataObject.java
  powerfactory/powerfactory-model/src/main/java/com/powsybl/powerfactory/model/StudyCase.java
  powerfactory/powerfactory-model/src/test/java/com/powsybl/powerfactory/model/StudyCaseTest.java
Labels: PR: next-release

#2022 Switches removed from Voltage Level local data structures before call to Network listeners
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusBreakerVoltageLevel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/RemoveSwitchTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/util/AbstractRemoveDanglingSwitchesTopologyTest.java
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/NetworkBusBreakerTest1Factory.java
  math/src/main/java/com/powsybl/math/graph/DefaultUndirectedGraphListener.java
  math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java
  math/src/main/java/com/powsybl/math/graph/UndirectedGraphListener.java
Labels: PR: ready-to-be-merged, PR: next-release

#2030 Fix check in ValidationUtil: voltageRegulatorOn can be null in ValidationUtil, throwing an error
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ValidationUtil.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/GeneratorAdderImpl.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractGeneratorTest.java
Labels: bug, IIDM, PR: ready-to-be-merged

#2012 CGMES import: fix HVDC active power set point conversion
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/hvdc/DcLineSegmentConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/HvdcConversionTest.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/HvdcConverterStation.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractHvdcConverterStation.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/AbstractHvdcConverterStationAdapter.java
  iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/HvdcLineAdapterTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractLccTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractVscTest.java
Labels: PR: ready-to-be-merged, PR: next-release

#2037 CgmesIidmMapping now strictly contains topological mapping and is optional for CGMES import and export
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/TopologyExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportContextTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/StateVariablesExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/TopologyExportTest.java
  cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/BaseVoltageMapping.java
  cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/BaseVoltageMappingAdder.java
  cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/BaseVoltageMappingAdderImpl.java
  cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/BaseVoltageMappingAdderImplProvider.java
  cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/BaseVoltageMappingImpl.java
  cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/BaseVoltageMappingXmlSerializer.java
  cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesIidmMapping.java
  cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesIidmMappingAdder.java
  cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesIidmMappingAdderImpl.java
  cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesIidmMappingImpl.java
  cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesIidmMappingXmlSerializer.java
  cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/Source.java
  cgmes/cgmes-extensions/src/main/resources/xsd/baseVoltageMapping.xsd
  cgmes/cgmes-extensions/src/main/resources/xsd/cgmesIidmMapping.xsd
  cgmes/cgmes-model/src/test/java/com/powsybl/cgmes/model/test/FakeCgmesModel.java
Labels: Doc needed, CGMES, Breaking Change, PR: ready-to-be-merged, PR: next-release

#1998 CGMES export to version 3
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/ControlAreaEq.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/ModelDescriptionEq.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/RegulatingControlEq.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportContextTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/ExportToCimVersionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/ExportXmlCompare.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesNamespace.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesOnDataSource.java
Labels: PR: ready-to-be-merged, PR: next-release

#2045 Bug fix: When looking for boundaries, all files inside the boundary location directory are considered
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java
  commons/src/main/java/com/powsybl/commons/datasource/GenericReadOnlyDataSource.java
Labels: bug, CGMES, PR: ready-to-be-merged

#2040 add affected terminals to traverse in TrippingTopologyTraverser to trace which terminals have been traversed
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/tripping/AbstractInjectionTripping.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/tripping/BranchTripping.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/tripping/BusbarSectionTripping.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/tripping/HvdcLineTripping.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/tripping/ThreeWindingsTransformerTripping.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/tripping/Tripping.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/tripping/TrippingTopologyTraverser.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/tripping/BranchTrippingTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/tripping/TrippingTopologyTraverserTest.java
Labels: PR: ready-to-be-merged, PR: next-release

#2039 New sensitivity function types
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityAnalysisResult.java
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityFactor.java
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityFunctionType.java
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityValueKey.java
  sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisResultTest.java
  sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisTest.java
  sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisToolTest.java
  sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityFactorTest.java
  sensitivity-analysis-api/src/test/resources/factorRef.json
Labels: PR: ready-to-be-merged, PR: next-release

#2048 Bug fix: CGMES region and subregion are set from country and geotag (not randomly)
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
Labels: CGMES, PR: ready-to-be-merged

#1804 UCTE importer: fix phase changer regulation mode
  ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteImporter.java
  ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/UcteImporterTest.java
  ucte/ucte-converter/src/test/resources/phaseShifterActivePowerOn.uct
Labels: PR: ready-to-be-merged, PR: next-release
