Repository powsybl/powsybl-core, pull requests merged in 2023-01, with the labels that each got.

#2431 Full description of loadflow specific parameters
  commons/src/main/java/com/powsybl/commons/config/ModuleConfigUtil.java
  commons/src/main/java/com/powsybl/commons/parameters/Parameter.java
  commons/src/main/java/com/powsybl/commons/parameters/ParameterDefaultValueConfig.java
  commons/src/main/java/com/powsybl/commons/parameters/ParameterType.java
  commons/src/test/java/com/powsybl/commons/parameters/ParameterDefaultValueConfigTest.java
  commons/src/test/java/com/powsybl/commons/parameters/ParameterTest.java
  loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowProvider.java
  loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowProviderMock.java
  loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowTest.java
Labels: PR: ready-to-be-merged, PR: next-release

#2417 Default values for network element adders
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractBranchAdder.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/DanglingLineAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/LineAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/PhaseTapChangerAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/RatioTapChangerAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ThreeWindingsTransformerAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TieLineAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TwoWindingsTransformerAdderImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/TieLineTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractDanglingLineTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractLineTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractShuntCompensatorTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractTapChangerTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractThreeWindingsTransformerTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractTwoWindingsTransformerTest.java
Labels: PR: ready-to-be-merged, PR: next-release

#2426 CGMES importer: handle GeographicalRegion in BoundarySet
  cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/Cgmes3ModifiedCatalog.java
  cgmes/cgmes-conformity/src/main/resources/cgmes3-test-models-modified/MicroGrid/geographicalRegionInBoundary/20171002T0930Z_ENTSO-E_EQ_BD_2.xml
  cgmes/cgmes-conformity/src/main/resources/cgmes3-test-models-modified/MicroGrid/geographicalRegionInBoundary/20210209T1930Z_1D_BE_EQ_9.xml
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/Cgmes3ModifiedConversionTest.java
  cgmes/cgmes-model/src/main/resources/CIM16.sparql
Labels: PR: ready-to-be-merged, PR: next-release

#2433 [dynamic-simulation] Add EventModel startTime
  dynamic-simulation/dynamic-simulation-api/src/main/java/com/powsybl/dynamicsimulation/EventModel.java
  dynamic-simulation/dynamic-simulation-dsl/src/test/groovy/com/powsybl/dynamicsimulation/groovy/DummyEventModelGroovyExtension.groovy
  dynamic-simulation/dynamic-simulation-dsl/src/test/java/com/powsybl/dynamicsimulation/groovy/DummyEventModel.java
  dynamic-simulation/dynamic-simulation-dsl/src/test/java/com/powsybl/dynamicsimulation/groovy/GroovyEventModelSupplierTest.java
  dynamic-simulation/dynamic-simulation-dsl/src/test/resources/eventModels.groovy
Labels: Breaking Change, PR: ready-to-be-merged, PR: next-release

#2394 Implement new consistent behavior when calling merge method (uniform in NetworkImpl, MergingView and CGM import)
  cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/CgmesConformity1ModifiedCatalog.java
  cgmes/cgmes-conversion/pom.xml
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ACLineSegmentConversion.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/TieLineUtil.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergedLine.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergingViewIndex.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/ValidationUtil.java
  iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/BusAdapterTest.java
  iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/DanglingLineAdapterTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractMergeNetworkTest.java
Labels: bug, IIDM, CGMES, Breaking Change, PR: ready-to-be-merged, PR: next-release

#2430 PowerFactory: prepare for DGS 6 and 7 support
  powerfactory/powerfactory-dgs/src/main/java/com/powsybl/powerfactory/dgs/DgsHandler.java
  powerfactory/powerfactory-dgs/src/main/java/com/powsybl/powerfactory/dgs/DgsParser.java
  powerfactory/powerfactory-dgs/src/main/java/com/powsybl/powerfactory/dgs/DgsReader.java
  powerfactory/powerfactory-dgs/src/test/java/com/powsybl/powerfactory/dgs/DgsDataTest.java
  powerfactory/powerfactory-dgs/src/test/resources/ascii_v6.dgs
  powerfactory/powerfactory-dgs/src/test/resources/ascii_v7.dgs
Labels: PR: ready-to-be-merged

#2438 CGMES SV export: use naming strategy to obtain proper topological node identifiers
  cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_Assembled_v2_bad_ids/MicroGridTestConfiguration_BC_NL_TP_V2.xml
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesMappingTest.java
Labels: PR: ready-to-be-merged

#2435 CGMES: convert cim:GeneratingUnit.normalPF to ActivePowerControl iIDM extension
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SynchronousMachineConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/ActivePowerControlXmlSerializer.java
  iidm/iidm-xml-converter/src/main/resources/xsd/activePowerControl_V1_1.xsd
Labels: CGMES, PR: ready-to-be-merged, PR: next-release

#2436 Add secondary voltage control IIDM extension
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/SecondaryVoltageControl.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/SecondaryVoltageControlAdder.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/SecondaryVoltageControlAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/SecondaryVoltageControlAdderImplProvider.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/SecondaryVoltageControlImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/extensions/SecondaryVoltageControlTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractSecondaryVoltageControlTest.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NetworkXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/SecondaryVoltageControlXmlSerializer.java
  iidm/iidm-xml-converter/src/main/resources/xsd/secondaryVoltageControl_V1_0.xsd
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/extensions/SecondaryVoltageControlXmlTest.java
  iidm/iidm-xml-converter/src/test/resources/V1_8/secondaryVoltageControlRoundTripRef.xml
Labels: PR: next-release

#2434 Allow reduction of HVDC lines
  iidm/iidm-reducer/src/main/java/com/powsybl/iidm/reducer/DefaultNetworkReducer.java
  iidm/iidm-reducer/src/test/java/com/powsybl/iidm/reducer/DefaultNetworkReducerTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNetworkTest.java
Labels: PR: ready-to-be-merged, PR: next-release

#2439 Bbv cache not invalidated for a retained switch when opened/closed
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusBreakerVoltageLevel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SwitchImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VoltageLevelExt.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractSwitchSetRetainedTest.java
Labels: PR: next-release

#2379 Index sensitivity values by variable type
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityAnalysisResult.java
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityValueKey.java
  sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisResultTest.java
Labels: Breaking Change, PR: do-not-merge, PR: next-release

#2443 CGMES fix network id for CGMES3; conformity test configurations v3
  cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/CgmesCatalogsConstants.java
  cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/CgmesConformity3Catalog.java
  cgmes/cgmes-conformity/src/main/resources/conformity/cas-3-data-3.0.2/MicroGrid/BaseCase/MicroGrid-BD-MAS/20171002T0930Z_ENTSO-E_EQ_BD_2.xml
  cgmes/cgmes-conformity/src/main/resources/conformity/cas-3-data-3.0.2/MicroGrid/BaseCase/MicroGrid-BE-MAS/20210325T1530Z_1D_BE_DL_001.xml
  cgmes/cgmes-conformity/src/main/resources/conformity/cas-3-data-3.0.2/MicroGrid/BaseCase/MicroGrid-BE-MAS/20210325T1530Z_1D_BE_EQ_001.xml
  cgmes/cgmes-conformity/src/main/resources/conformity/cas-3-data-3.0.2/MicroGrid/BaseCase/MicroGrid-BE-MAS/20210325T1530Z_1D_BE_GL_001.xml
  cgmes/cgmes-conformity/src/main/resources/conformity/cas-3-data-3.0.2/MicroGrid/BaseCase/MicroGrid-BE-MAS/20210325T1530Z_1D_BE_SSH_001.xml
  cgmes/cgmes-conformity/src/main/resources/conformity/cas-3-data-3.0.2/MicroGrid/BaseCase/MicroGrid-BE-MAS/20210325T1530Z_1D_BE_SV_001.xml
  cgmes/cgmes-conformity/src/main/resources/conformity/cas-3-data-3.0.2/MicroGrid/BaseCase/MicroGrid-BE-MAS/20210325T1530Z_1D_BE_TP_001.xml
  cgmes/cgmes-conformity/src/main/resources/conformity/cas-3-data-3.0.2/MicroGrid/BaseCase/MicroGrid-BE-MAS/20210420T1730Z_1D_BE_DY_001.xml
  cgmes/cgmes-conformity/src/main/resources/conformity/cas-3-data-3.0.2/MicroGrid/BaseCase/MicroGrid-BaseCase-Merged/20171002T0930Z_ENTSO-E_EQ_BD_2.xml
  cgmes/cgmes-conformity/src/main/resources/conformity/cas-3-data-3.0.2/MicroGrid/BaseCase/MicroGrid-BaseCase-Merged/20210325T1530Z_1D_ASSEMBLED_DL_001.xml
  cgmes/cgmes-conformity/src/main/resources/conformity/cas-3-data-3.0.2/MicroGrid/BaseCase/MicroGrid-BaseCase-Merged/20210325T1530Z_1D_ASSEMBLED_SV_001.xml
  cgmes/cgmes-conformity/src/main/resources/conformity/cas-3-data-3.0.2/MicroGrid/BaseCase/MicroGrid-BaseCase-Merged/20210325T1530Z_1D_ASSEMBLED_TP_001.xml
  cgmes/cgmes-conformity/src/main/resources/conformity/cas-3-data-3.0.2/MicroGrid/BaseCase/MicroGrid-BaseCase-Merged/20210325T1530Z_1D_BE_EQ_001.xml
  cgmes/cgmes-conformity/src/main/resources/conformity/cas-3-data-3.0.2/MicroGrid/BaseCase/MicroGrid-BaseCase-Merged/20210325T1530Z_1D_BE_GL_001.xml
  cgmes/cgmes-conformity/src/main/resources/conformity/cas-3-data-3.0.2/MicroGrid/BaseCase/MicroGrid-BaseCase-Merged/20210325T1530Z_1D_BE_SSH_001.xml
  cgmes/cgmes-conformity/src/main/resources/conformity/cas-3-data-3.0.2/MicroGrid/BaseCase/MicroGrid-BaseCase-Merged/20210325T1530Z_1D_NL_EQ_001.xml
  cgmes/cgmes-conformity/src/main/resources/conformity/cas-3-data-3.0.2/MicroGrid/BaseCase/MicroGrid-BaseCase-Merged/20210325T1530Z_1D_NL_GL_001.xml
  cgmes/cgmes-conformity/src/main/resources/conformity/cas-3-data-3.0.2/MicroGrid/BaseCase/MicroGrid-BaseCase-Merged/20210325T1530Z_1D_NL_SSH_001.xml
  cgmes/cgmes-conformity/src/main/resources/conformity/cas-3-data-3.0.2/MicroGrid/BaseCase/MicroGrid-BaseCase-Merged/20210420T1730Z_1D_BE_DY_001.xml
  cgmes/cgmes-conformity/src/main/resources/conformity/cas-3-data-3.0.2/MicroGrid/BaseCase/MicroGrid-BaseCase-Merged/20210420T1730Z_1D_NL_DY_001.xml
  cgmes/cgmes-conformity/src/main/resources/conformity/cas-3-data-3.0.2/MicroGrid/BaseCase/MicroGrid-NL-MAS/20210325T1530Z_1D_NL_DL_001.xml
  cgmes/cgmes-conformity/src/main/resources/conformity/cas-3-data-3.0.2/MicroGrid/BaseCase/MicroGrid-NL-MAS/20210325T1530Z_1D_NL_EQ_001.xml
  cgmes/cgmes-conformity/src/main/resources/conformity/cas-3-data-3.0.2/MicroGrid/BaseCase/MicroGrid-NL-MAS/20210325T1530Z_1D_NL_GL_001.xml
  cgmes/cgmes-conformity/src/main/resources/conformity/cas-3-data-3.0.2/MicroGrid/BaseCase/MicroGrid-NL-MAS/20210325T1530Z_1D_NL_SSH_001.xml
  cgmes/cgmes-conformity/src/main/resources/conformity/cas-3-data-3.0.2/MicroGrid/BaseCase/MicroGrid-NL-MAS/20210325T1530Z_1D_NL_SV_001.xml
  cgmes/cgmes-conformity/src/main/resources/conformity/cas-3-data-3.0.2/MicroGrid/BaseCase/MicroGrid-NL-MAS/20210325T1530Z_1D_NL_TP_001.xml
  cgmes/cgmes-conformity/src/main/resources/conformity/cas-3-data-3.0.2/MicroGrid/BaseCase/MicroGrid-NL-MAS/20210420T1730Z_1D_NL_DY_001.xml
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/CgmesConformity3ConversionTest.java
  cgmes/cgmes-model/src/main/resources/CIM100.sparql
Labels: PR: ready-to-be-merged

#2448 Add side integer to SensitivityFunctionType, SensitivityVariableType
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityFunctionType.java
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityVariableType.java
  sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityAnalysisResultTest.java
  sensitivity-analysis-api/src/test/java/com/powsybl/sensitivity/SensitivityFactorTest.java
Labels: PR: ready-to-be-merged

#2449 Add comparison of intermediary file in roundTrip
  commons-test/src/main/java/com/powsybl/commons/test/AbstractConverterTest.java
Labels: XIIDM, PR: ready-to-be-merged, Test

#2451 Update GraphViz library
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/util/GraphvizConnectivityTest.java
  iidm/iidm-tck/src/test/resources/eurostag-tutorial-country-cluster.dot
  iidm/iidm-tck/src/test/resources/eurostag-tutorial-example1.dot
  pom.xml
Labels: PR: ready-to-be-merged

#2453 Fix proportional scaling with constant power factor
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/ProportionalScalable.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/ScalableTest.java
Labels: bug, PR: ready-to-be-merged, PR: next-release

#2456 change current limit name in as test network
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/SecurityAnalysisTestNetworkFactoryTest.java
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/SecurityAnalysisTestNetworkFactory.java
Labels: Security Analysis, XIIDM, PR: ready-to-be-merged, Test

#2452 Clean CGMES export of tie lines/dangling lines
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ACLineSegmentConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractConductingEquipmentConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/TopologyExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/CgmesConformity3ConversionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportTest.java
Labels: bug, CGMES, PR: ready-to-be-merged, PR: next-release
