Repository powsybl/powsybl-core, pull requests merged in 2023-10, with the labels that each got.

#2730 Disconnect dangling lines disconnected at boundary
  cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/CgmesConformity1ModifiedCatalog.java
  cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_line_disconnected_at_boundary_node/MicroGridTestConfiguration_BC_BE_SSH_V2.xml
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesReports.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
Labels: bug, CGMES, PR: next-release

#2731 CGMES phase tap changer xMin: optional and consistent with transformer x
  cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/Cgmes3ModifiedCatalog.java
  cgmes/cgmes-conformity/src/main/resources/cgmes3-test-models-modified/MicroGrid/phaseTapChangerXMin/20210209T1930Z_1D_BE_EQ_9.xml
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/CgmesPhaseTapChangerBuilder.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/TransformerConversionTest.java
  cgmes/cgmes-model/src/main/resources/CIM16.sparql
Labels: bug, CGMES, PR: next-release

#2733 Fix regression introduced in #2648 (optional ratedS for 3-winding transformers)
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/InterpretedT3xModel.java
Labels: bug, CGMES, PR: next-release

#2727 Fix unix file permissions, text files should not be executable
  cgmes/cgmes-conformity/src/main/resources/cgmes3-test-models-modified/MicroGrid/singleFile/20210209T1930Z_1D_BE_9.xml
  cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_single_file/MicroGridTestConfiguration_BC_BE_V2.xml
  cgmes/cgmes-conversion/src/test/resources/t-line.xml
  commons/src/main/java/com/powsybl/commons/datasource/FileDataSource.java
  commons/src/main/java/com/powsybl/commons/datasource/GenericReadOnlyDataSource.java
  commons/src/main/java/com/powsybl/commons/datasource/ReadOnlyDataSource.java
  commons/src/main/java/com/powsybl/commons/datasource/ReadOnlyMemDataSource.java
  commons/src/main/java/com/powsybl/commons/datasource/ZipFileDataSource.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/Coordinate.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/GeneratorShortCircuitImpl.java
  ucte/ucte-converter/src/test/resources/combineRtcAndPtc.uct
Labels: PR: next-release

#2734 [Shortcircuit API] Correct value of min-voltage-drop-proportional-threshold in tests
  shortcircuit-api/src/test/java/com/powsybl/shortcircuit/ShortCircuitParametersTest.java
  shortcircuit-api/src/test/java/com/powsybl/shortcircuit/json/JsonFaultParametersTest.java
  shortcircuit-api/src/test/resources/FaultParametersFile.json
  shortcircuit-api/src/test/resources/FaultParametersFileVersion10.json
  shortcircuit-api/src/test/resources/FaultParametersFileVersion11.json
  shortcircuit-api/src/test/resources/FaultParametersFileVersion12.json
  shortcircuit-api/src/test/resources/FaultParametersFileWithoutVoltageRanges.json
  shortcircuit-api/src/test/resources/config.yml
  shortcircuit-api/src/test/resources/wrongConfig.yml
Labels: PR: next-release

#2738 CGMES: improve log message for merged containers (substations and voltage levels)
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/SubstationIdMapping.java
Labels: CGMES

#2737 CGMES: adjust multiple unpaired dangling lines connected at same boundary node
  cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/CgmesConformity3ModifiedCatalog.java
  cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-3-data-3.0.2/MicroGrid/BE-3dls-same-boundary-node-1disconnected/20210325T1530Z_1D_BE_EQ_001_3dls_1disconnected.xml
  cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-3-data-3.0.2/MicroGrid/BE-3dls-same-boundary-node-1disconnected/20210325T1530Z_1D_BE_SSH_001_3dls_1disconnected.xml
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesReports.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/Cgmes3ModifiedConversionTest.java
Labels: CGMES, PR: ready-to-be-merged, PR: next-release

#2740 Fix merging networks with a tie line and a dangling line of same pairing key
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/TieLineUtil.java
  iidm/iidm-api/src/test/java/com/powsybl/iidm/network/TieLineUtilTest.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractMergeNetworkTest.java
Labels: PR: next-release

#2729 Add disconnectors on all parallel bars except one and make naming consistent
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AbstractCreateConnectableFeederBays.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ConnectVoltageLevelOnLine.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateCouplingDevice.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateLineOnLine.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ReplaceTeePointByVoltageLevelOnLine.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/TopologyModificationUtils.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/ConnectVoltageLevelOnLineTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateLineOnLineTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/RemoveFeederBayTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/ReplaceTeePointByVoltageLevelOnLineTest.java
  iidm/iidm-modification/src/test/resources/eurostag-line-split-nb-l.xml
  iidm/iidm-modification/src/test/resources/eurostag-line-split-nb-vl.xml
  iidm/iidm-modification/src/test/resources/eurostag-replace-tee-point-by-voltage-level-on-line-nbbb.xml
  iidm/iidm-modification/src/test/resources/fictitious-line-split-l-complete.xml
  iidm/iidm-modification/src/test/resources/fictitious-line-split-l.xml
  iidm/iidm-modification/src/test/resources/fictitious-line-split-vl-complete.xml
  iidm/iidm-modification/src/test/resources/fictitious-line-split-vl.xml
  iidm/iidm-modification/src/test/resources/fictitious-replace-tee-point-by-voltage-level-on-line-nb.xml
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-equipments-bbs1.xml
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-generator-bbs1.xml
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-internal-line.xml
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-line-order-used.xml
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-line.xml
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-load-bbs4.xml
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-twt-feeders-bbs.xml
  iidm/iidm-modification/src/test/resources/reporter/connect-voltage-level-on-line-NB-report.txt
  iidm/iidm-modification/src/test/resources/reporter/create-line-on-line-report.txt
  iidm/iidm-modification/src/test/resources/reporter/replace-tee-point-by-vl-on-line-nb-bb-report.txt
  iidm/iidm-modification/src/test/resources/reporter/replace-tee-point-by-vl-on-line-nb-report.txt
  iidm/iidm-modification/src/test/resources/testNetwork3BusbarSectionsWithCouplingDevice.xiidm
  iidm/iidm-modification/src/test/resources/testNetworkNodeBreakerWithCouplingDeviceDifferentSectionIndex.xml
  iidm/iidm-modification/src/test/resources/testNetworkNodeBreakerWithCouplingDeviceSameSectionIndex.xml
  iidm/iidm-modification/src/test/resources/testNetworkNodeBreakerWithCouplingDeviceWithoutExtensions.xml
Labels: Breaking Change

#2748 Cgmes import: fix atan in symmetrical phase shifters
  cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/CgmesConformity1NetworkCatalog.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/CgmesPhaseTapChangerBuilder.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/TransformerConversionTest.java
Labels: bug, CGMES

#2745 Add a getSide() from Three Windings Transformer Leg
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ThreeWindingsTransformer.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ThreeWindingsTransformerImpl.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractThreeWindingsTransformerTest.java
Labels: PR: ready-to-be-merged

#2744 Cgmes Import: HVDC fix lost configurations
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/hvdc/CgmesDcConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/hvdc/IslandEndHvdc.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/hvdc/NodeEquipment.java
Labels: PR: ready-to-be-merged

#2716 Cgmes export fix tap changer control issue
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/EquipmentExportTest.java
  cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesTapChanger.java
  cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesTapChangerImpl.java
Labels: PR: ready-to-be-merged
