Repository powsybl/powsybl-core, pull requests merged in 2023-05, with the labels that each got.

#2559 Fix hvdc removal reporting
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/RemoveHvdcLine.java
Labels: PR: ready-to-be-merged

#2558 Fix severity for remove vl or hvdc reports
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ModificationReports.java
Labels: PR: ready-to-be-merged

#2561 Fix: support of BusContingency in ContingencyElement
  contingency/contingency-api/src/main/java/com/powsybl/contingency/ContingencyElement.java
  contingency/contingency-api/src/test/java/com/powsybl/contingency/BusContingencyTest.java
Labels: PR: ready-to-be-merged

#2562 Improve move connectable notification
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/BusTopologyPoint.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/NodeTopologyPoint.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/TopologyPoint.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractConnectable.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusTerminal.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusTopologyPointImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeTerminal.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeTopologyPointImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TerminalExt.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/MoveConnectableNotifTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractMoveConnectableNotifTest.java
Labels: PR: ready-to-be-merged, PR: next-release

#2527 Export batteries in CGMES
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/ReactiveCapabilityCurveEq.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/SynchronousMachineEq.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportTest.java
Labels: CGMES, PR: next-release

#2542 European LV test feeder case
  iidm/iidm-test/pom.xml
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/EuropeanLvTestFeederFactory.java
  iidm/iidm-test/src/main/resources/europeanLvTestFeeder/Buscoords.csv
  iidm/iidm-test/src/main/resources/europeanLvTestFeeder/LineCodes.csv
  iidm/iidm-test/src/main/resources/europeanLvTestFeeder/Lines.csv
  iidm/iidm-test/src/main/resources/europeanLvTestFeeder/LoadShapes.csv
  iidm/iidm-test/src/main/resources/europeanLvTestFeeder/Loads.csv
  iidm/iidm-test/src/main/resources/europeanLvTestFeeder/Source.csv
  iidm/iidm-test/src/main/resources/europeanLvTestFeeder/Transformer.csv
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/EuropeanLvTestFeederFactoryXmlTest.java
  iidm/iidm-xml-converter/src/test/resources/V1_10/europeanLvTestFeederRef.xml
  pom.xml
Labels: PR: ready-to-be-merged, PR: next-release

#2560 Fix writing zero bPerSection for xiidm <1.5 for iidm4cpp
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/ShuntXml.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/ShuntCompensatorXmlTest.java
Labels: bug

#2556 Add method to retrieve CN from xnode in CgmesBoundary
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesBoundary.java
Labels: PR: ready-to-be-merged, PR: next-release

#2555 IIDM load model
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EnergyConsumerConversion.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/ConversionUtil.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/EquivalentBranchConversionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/HvdcConversionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/JoinVoltageLevelTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/LoadConversionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/RegulatingTerminalConversionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/TieFlowConversionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/TransformerConversionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/Cgmes3ConversionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
  cgmes/cgmes-model/src/main/resources/CIM16.sparql
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ExponentialLoadModel.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ExponentialLoadModelAdder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Load.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/LoadAdder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/LoadModel.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/LoadModelType.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ZipLoadModel.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ZipLoadModelAdder.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractLoadModelImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ExponentialLoadModelAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ExponentialLoadModelImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/LoadAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/LoadImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ZipLoadModelAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ZipLoadModelImpl.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/LoadAdapter.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/LoadAdderAdapter.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractLoadTest.java
  iidm/iidm-test/pom.xml
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/LoadXml.java
  iidm/iidm-xml-converter/src/main/resources/xsd/iidm_V1_10.xsd
  iidm/iidm-xml-converter/src/main/resources/xsd/iidm_equipment_V1_10.xsd
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/LoadModelXmlTest.java
  iidm/iidm-xml-converter/src/test/resources/V1_10/eurostag-tutorial-example1-expo-load-model.xml
  iidm/iidm-xml-converter/src/test/resources/V1_10/eurostag-tutorial-example1-zip-load-model.xml
  psse/psse-converter/src/main/java/com/powsybl/psse/converter/LoadConverter.java
  psse/psse-converter/src/test/java/com/powsybl/psse/converter/PsseImporterTest.java
  psse/psse-converter/src/test/resources/IEEE_14_buses_zip_load.raw
  psse/psse-converter/src/test/resources/IEEE_14_buses_zip_load.xiidm
  triple-store/triple-store-api/src/main/java/com/powsybl/triplestore/api/PropertyBag.java
Labels: IIDM, CGMES, PR: waiting-for-review, PR: next-release, PSS/E

#2565 Factorize CriterionContingencyListSerializer classes into a single one
  contingency/contingency-api/src/main/java/com/powsybl/contingency/json/ContingencyJsonModule.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/json/EquipmentCriterionContingencyListSerializer.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/json/HvdcLineCriterionContingencyListSerializer.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/json/LineCriterionContingencyListSerializer.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/json/ThreeWindingsTransformerCriterionContingencyListSerializer.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/json/TwoWindingsTransformerCriterionContingencyListSerializer.java
Labels: PR: ready-to-be-merged, PR: next-release

#2567 Matpower export: add support of VSC, LCC, SVC and batteries
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/HvdcUtils.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/util/HvdcUtilsTest.java
  matpower/matpower-converter/src/main/java/com/powsybl/matpower/converter/MatpowerExporter.java
  matpower/matpower-converter/src/test/java/com/powsybl/matpower/converter/MatpowerExporterTest.java
  matpower/matpower-converter/src/test/resources/fourSubstationFactory.json
Labels: PR: ready-to-be-merged, PR: next-release

#2570 Add command execution duration to local computation manager
  computation-local/src/main/java/com/powsybl/computation/local/LocalComputationManager.java
Labels: PR: ready-to-be-merged, PR: next-release

#2577 Fix duplicated junit dependency
  iidm/iidm-test/pom.xml
Labels: PR: ready-to-be-merged, PR: next-release

#2578 Various Matpower export fixes
  matpower/matpower-converter/src/main/java/com/powsybl/matpower/converter/MatpowerExporter.java
  matpower/matpower-converter/src/main/java/com/powsybl/matpower/converter/MatpowerImporter.java
  matpower/matpower-converter/src/test/java/com/powsybl/matpower/converter/MatpowerExporterTest.java
  matpower/matpower-converter/src/test/java/com/powsybl/matpower/converter/MatpowerRoundTripTest.java
  matpower/matpower-converter/src/test/resources/be.json
  matpower/matpower-converter/src/test/resources/fourSubstationFactory.json
  matpower/matpower-converter/src/test/resources/ieee118.xiidm
  matpower/matpower-converter/src/test/resources/ieee14-inverted-voltage-limits.xiidm
  matpower/matpower-converter/src/test/resources/ieee14-phase-shifter.xiidm
  matpower/matpower-converter/src/test/resources/ieee14.xiidm
  matpower/matpower-converter/src/test/resources/ieee30-considering-base-voltage.json
  matpower/matpower-converter/src/test/resources/ieee30-considering-base-voltage.xiidm
  matpower/matpower-converter/src/test/resources/ieee30.xiidm
  matpower/matpower-converter/src/test/resources/ieee300.xiidm
  matpower/matpower-converter/src/test/resources/ieee57.xiidm
  matpower/matpower-converter/src/test/resources/ieee9.xiidm
  matpower/matpower-converter/src/test/resources/ieee9_limits.xiidm
  matpower/matpower-converter/src/test/resources/ieee9zeroimpedance.xiidm
  matpower/matpower-converter/src/test/resources/sim1-with-tie-lines.json
  matpower/matpower-converter/src/test/resources/sim1.json
  matpower/matpower-model/src/test/java/com/powsybl/matpower/model/MatpowerReaderWriterTest.java
Labels: PR: next-release

#2557 Add new network modifications
  action/action-dsl/src/test/java/com/powsybl/action/dsl/GeneratorModificationActionTest.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ThreeWindingsTransformer.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/AbstractNetworkModification.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/GeneratorModification.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/ShuntCompensatorPositionModification.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/StaticVarCompensatorModification.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/VscConverterStationModification.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/tapchanger/AbstractTapPositionModification.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/tapchanger/PhaseTapPositionModification.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/tapchanger/RatioTapPositionModification.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/ShuntCompensatorPositionModificationTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/StaticVarCompensatorModificationTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/VscConverterStationModificationTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/tapchanger/TapPositionModificationTest.java
Labels: PR: ready-to-be-merged, PR: next-release

#2579 Load ZIP model: allow negative coefficients
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ZipLoadModel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ZipLoadModelImpl.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractLoadTest.java
Labels: PR: ready-to-be-merged, PR: next-release

#2581 add new method checkLimitsDc with dcPowerFactor param
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/LimitViolationDetector.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/Security.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/detectors/AbstractContingencyBlindDetector.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/SecurityTest.java
Labels: PR: ready-to-be-merged, PR: next-release

#2580 [powsybl-iidm-tck] Put tie line tests apart
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/TieLineTest.java
  iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/tck/TieLineTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractLineTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractTieLineTest.java
Labels: PR: ready-to-be-merged

#2584 Add parameter to allow or not a generator to scale when its initial targetP is outside minP - maxP
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/GeneratorScalable.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/ScalingParameters.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/GeneratorScalableTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/ScalingParametersTest.java
Labels: PR: next-release

#2564 Add modification to replace tie lines by lines
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/TieLineReports.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/TieLineUtil.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/DanglingLineImpl.java
  iidm/iidm-modification/pom.xml
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/ReplaceTieLinesByLines.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/ReplaceTieLinesByLinesPostProcessor.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AbstractCreateConnectableFeederBays.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AbstractLineConnectionModification.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateCouplingDevice.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateLineOnLine.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateVoltageLevelTopology.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/RemoveFeederBay.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/RemoveHvdcLine.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/RemoveVoltageLevel.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ReplaceTeePointByVoltageLevelOnLine.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/RevertConnectVoltageLevelOnLine.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/RevertCreateLineOnLine.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/TopologyModificationUtils.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/util/ModificationReports.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/ReplaceTieLinesByLinesTest.java
  iidm/iidm-modification/src/test/resources/eurostag-replace-tl.xml
  iidm/iidm-modification/src/test/resources/replace-tl-nb.xml
Labels: PR: next-release, PR: waiting-for-coverage-test

#2585 Fix ampl writer: writing current limits which are on paired dangling lines
  ampl-converter/src/main/java/com/powsybl/ampl/converter/AmplNetworkWriter.java
  ampl-converter/src/main/java/com/powsybl/ampl/converter/AmplUtil.java
  ampl-converter/src/test/java/com/powsybl/ampl/converter/AmplNetworkWriterTest.java
  ampl-converter/src/test/resources/inputs/eurostag-tutorial-example1-branches-tl.txt
  ampl-converter/src/test/resources/inputs/eurostag-tutorial-example1-limits-tl.txt
Labels: PR: ready-to-be-merged

#2586 Add tie lines support in limit violation detector
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/LimitViolationUtils.java
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/EurostagTutorialExample1Factory.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/LimitViolationDetector.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/detectors/AbstractContingencyBlindDetector.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/detectors/AbstractLimitViolationDetector.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/detectors/DefaultLimitViolationDetector.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/detectors/DefaultLimitViolationDetectorTest.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/detectors/LimitViolationDetectorTest.java
Labels: Breaking Change, PR: ready-to-be-merged, PR: next-release

#2576 [Network modifications] Add check on order position value in CreateConnectableBay
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/BusbarSectionPosition.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ConnectablePosition.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AbstractCreateConnectableFeederBays.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/TopologyModificationUtils.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/util/ModificationReports.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateBranchFeederBaysTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateFeederBayTest.java
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-equipments-bbs1.xml
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-generator-bbs1.xml
  iidm/iidm-modification/src/test/resources/network-node-breaker-with-new-twt-feeders-bbs.xml
Labels: bug, PR: next-release

#2587 Export tie lines in graphviz export
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/GraphvizConnectivity.java
Labels: bug, PR: next-release

#2589 SV: support of DC approximation
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/SV.java
  iidm/iidm-api/src/test/java/com/powsybl/iidm/network/util/SVTest.java
Labels: PR: ready-to-be-merged, PR: next-release

#2588 Support of ConnectionShuntModification
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/ShuntCompensatorModification.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/ShuntCompensatorModificationTest.java
Labels: PR: next-release

#2591 Branch does not extend connectable
  ampl-converter/src/main/java/com/powsybl/ampl/converter/AmplNetworkWriter.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Branch.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/BranchAdder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Line.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/TieLine.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/TwoWindingsTransformer.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/GraphvizConnectivity.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/LimitViolationUtils.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractConnectableBranch.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BranchUtil.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/LineImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TieLineImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TwoWindingsTransformerImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/TieLineTest.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/AbstractConnectableBranchAdapter.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/LineAdapter.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergedLine.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergingViewIndex.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/TieLineAdapter.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/TwoWindingsTransformerAdapter.java
  iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/LineAdapterTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNetworkTest.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/LimitViolationDetector.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/detectors/AbstractContingencyBlindDetector.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/detectors/AbstractLimitViolationDetector.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/detectors/DefaultLimitViolationDetector.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/detectors/LimitViolationDetectorTest.java
Labels: Breaking Change, PR: next-release

#2574 Fixes in CGMES export
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/TopologyExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/ControlAreaEq.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/EquivalentInjectionEq.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/LoadAreaEq.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/PowerTransformerEq.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/ReactiveCapabilityCurveEq.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/SynchronousMachineEq.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/TerminalEq.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/CgmesConformity1ConversionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportContextTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesMappingTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/ExportXmlCompare.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesNames.java
Labels: PR: ready-to-be-merged, PR: next-release
