Repository powsybl/powsybl-core, pull requests merged in 2023-08, with the labels that each got.

#2669 Check dense matrix max element count
  math/src/main/java/com/powsybl/math/matrix/DenseMatrix.java
  math/src/test/java/com/powsybl/math/matrix/DenseMatrixTest.java
Labels: bug

#2684 Java S6355 rule: add arguments to @Deprecated annotations
  commons/src/main/java/com/powsybl/commons/compress/ZipHelper.java
  commons/src/main/java/com/powsybl/commons/config/ModuleConfigRepository.java
  commons/src/main/java/com/powsybl/commons/config/PlatformConfig.java
  commons/src/main/java/com/powsybl/commons/config/PlatformConfigNamedProvider.java
  commons/src/main/java/com/powsybl/commons/xml/XmlWriterContext.java
  computation/src/main/java/com/powsybl/computation/SimpleCommand.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/Contingency.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Importer.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/NetworkFactory.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractMultiVariantConnectableExtension.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateCouplingDevice.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateCouplingDeviceBuilder.java
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/EurostagTutorialExample1Factory.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/ConnectableXmlUtil.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NetworkXmlWriterContext.java
  loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java
  loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowProvider.java
  math/src/main/java/com/powsybl/math/graph/UndirectedGraph.java
  math/src/main/java/com/powsybl/math/matrix/DenseMatrix.java
  math/src/main/java/com/powsybl/math/matrix/Matrix.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/ShortCircuitParameters.java
Labels: Quality

#2626 Traversal from terminal by depth or breadth first
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Terminal.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusBreakerVoltageLevel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusTerminal.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeTerminal.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TerminalExt.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/TopologyTraverseDepthAndBreadthTest.java
  iidm/iidm-impl/src/test/javadoc/com/powsybl/iidm/network/impl/doc-files/traversalByDepthOrBreadthNetwork.svg
  math/src/main/java/com/powsybl/math/graph/TraversalType.java
  math/src/main/java/com/powsybl/math/graph/UndirectedGraph.java
  math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java
  math/src/test/java/com/powsybl/math/graph/UndirectedGraphImplTest.java
Labels: Breaking Change

#2644 CgmesExport. Export transformers with sorted ends
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportContextTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/EquipmentExportTest.java
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/ThreeWindingsTransformerNetworkFactory.java
Labels: Doc needed, PR: ready-to-be-merged
