Repository powsybl/powsybl-core, pull requests merged in 2023-03, with the labels that each got.

#2477 [Security analysis] Fix check on 0 value in tap changer tap position action
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/action/AbstractTapChangerTapPositionActionDeserializer.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/json/JsonActionAndOperatorStrategyTest.java
  security-analysis/security-analysis-api/src/test/resources/WrongActionFileTest2.json
Labels: bug, Security Analysis, PR: ready-to-be-merged

#2479 Bump snakeyaml to 2.0. Fix [CVE-2022-1471]
  commons/src/main/java/com/powsybl/commons/config/BaseVoltagesConfig.java
  pom.xml
Labels: PR: ready-to-be-merged, Quality

#2484 [Sensitivity analysis] add new variable and function types
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityFunctionType.java
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityVariableType.java
Labels: PR: ready-to-be-merged

#2468 [Security analysis] Add new action conditions
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/condition/AbstractFilteredCondition.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/condition/AllViolationCondition.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/condition/AnyViolationCondition.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/condition/AtLeastOneViolationCondition.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/ConditionDeserializer.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/ConditionSerializer.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/json/JsonActionAndOperatorStrategyTest.java
  security-analysis/security-analysis-api/src/test/resources/OperatorStrategyFileTest.json
  security-analysis/security-analysis-api/src/test/resources/OperatorStrategyFileTestV1.0.json
  security-analysis/security-analysis-api/src/test/resources/OperatorStrategyFileTestV1.1.json
Labels: Security Analysis, PR: waiting-for-review, PR: next-release

#2490 Fix anonymized xml writing
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NetworkXml.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/XMLImporterTest.java
  iidm/iidm-xml-converter/src/test/resources/V1_9/eurostag-tutorial-example1-anonymized.xml
  iidm/iidm-xml-converter/src/test/resources/eurostag-tutorial-example1-mapping.csv
Labels: PR: ready-to-be-merged, PR: next-release

#2470 Remove regulating terminal when the equipment it is pointing to is removed from the network
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractConnectable.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractTapChanger.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractTerminal.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/GeneratorImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/PhaseTapChangerImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/RatioTapChangerImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/RegulatingPoint.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ShuntCompensatorImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/StaticVarCompensatorImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TerminalExt.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VscConverterStationImpl.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractStaticVarCompensatorTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractTapChangerTest.java
Labels: IIDM, PR: ready-to-be-merged, PR: next-release

#2486 Fortescue data extensions
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/FortescueConstants.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/GeneratorFortescue.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/GeneratorFortescueAdder.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/LineFortescue.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/LineFortescueAdder.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ThreeWindingsTransformerFortescue.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ThreeWindingsTransformerFortescueAdder.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/TwoWindingsTransformerFortescue.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/TwoWindingsTransformerFortescueAdder.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/WindingConnectionType.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/GeneratorFortescueAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/GeneratorFortescueAdderImplProvider.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/GeneratorFortescueImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/LineFortescueAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/LineFortescueAdderImplProvider.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/LineFortescueImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ThreeWindingsTransformerFortescueAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ThreeWindingsTransformerFortescueAdderImplProvider.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ThreeWindingsTransformerFortescueImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/TwoWindingsTransformerFortescueAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/TwoWindingsTransformerFortescueAdderImplProvider.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/TwoWindingsTransformerFortescueImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/extensions/FortescueExtensionTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractFortescueExtensionTest.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/GeneratorFortescueXmlSerializer.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/LineFortescueXmlSerializer.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/ThreeWindingsTransformerFortescueXmlSerializer.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/TwoWindingsTransformerFortescueXmlSerializer.java
  iidm/iidm-xml-converter/src/main/resources/xsd/generatorFortescue_V1_0.xsd
  iidm/iidm-xml-converter/src/main/resources/xsd/lineFortescue_V1_0.xsd
  iidm/iidm-xml-converter/src/main/resources/xsd/threeWindingsTransformerFortescue_V1_0.xsd
  iidm/iidm-xml-converter/src/main/resources/xsd/twoWindingsTransformerFortescue_V1_0.xsd
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/extensions/GeneratorFortescueXmlSerializerTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/extensions/LineFortescueXmlSerializerTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/extensions/ThreeWindingsTransformerFortescueXmlSerializerTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/extensions/TwoWindingsTransformerFortescueXmlSerializerTest.java
  iidm/iidm-xml-converter/src/test/resources/fortescue/generatorFortescueRef.xml
  iidm/iidm-xml-converter/src/test/resources/fortescue/lineFortescueRef.xml
  iidm/iidm-xml-converter/src/test/resources/fortescue/threeWindingsTransformerFortescueRef.xml
  iidm/iidm-xml-converter/src/test/resources/fortescue/twoWindingsTransformerFortescueRef.xml
Labels: PR: next-release

#2494 [Short Circuit API] Replace names in FortescueValue
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/AbstractFaultResult.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/FortescueValue.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/converter/AbstractTableShortCircuitAnalysisResultExporter.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/json/FortescueValuesSerializer.java
  shortcircuit-api/src/test/java/com/powsybl/shortcircuit/ShortCircuitAnalysisTest.java
  shortcircuit-api/src/test/java/com/powsybl/shortcircuit/converter/ShortCircuitAnalysisResultExportersTest.java
Labels: Breaking Change, PR: ready-to-be-merged, PR: next-release

#2454 Add Hvdc action
  commons/src/main/java/com/powsybl/commons/json/JsonUtil.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/action/GeneratorAction.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/action/HvdcAction.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/action/HvdcActionBuilder.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/action/LoadAction.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/SecurityAnalysisJsonModule.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/action/HvdcActionDeserializer.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/action/HvdcActionSerializer.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/json/JsonActionAndOperatorStrategyTest.java
  security-analysis/security-analysis-api/src/test/resources/ActionFileTest.json
  security-analysis/security-analysis-api/src/test/resources/ActionFileTestV1.0.json
Labels: Security Analysis, PR: waiting-for-review, PR: next-release

#2472 CGMES Importer: optional creation of terminals fictitious switches
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/NodeMapping.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractConductingEquipmentConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SvInjectionConversion.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/Cgmes3ConversionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/TopologyExportCornerCasesTest.java
Labels: PR: ready-to-be-merged, PR: next-release

#2481 Refactoring XML IIDM serialization classes
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractComplexIdentifiableXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractIdentifiableXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractSimpleIdentifiableXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractSwitchXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractTransformerXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AliasesXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/BatteryXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/BusXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/BusbarSectionXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/ConnectableXmlUtil.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/DanglingLineXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/GeneratorXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/HvdcLineXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/LccConverterStationXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/LineXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/LoadXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/PropertiesXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/ShuntXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/StaticVarCompensatorXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/SubstationXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/ThreeWindingsTransformerXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/TieLineXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/TwoWindingsTransformerXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/VoltageLevelXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/VscConverterStationXml.java
Labels: Refactoring, XIIDM, PR: next-release

#2502 Add add method to the adders API
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractConductingEquipmentConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractIdentifiedObjectConversion.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/BatteryAdder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/BranchAdder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/BusAdder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/BusbarSectionAdder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/DanglingLineAdder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/GeneratorAdder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/HvdcConverterStationAdder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/HvdcLineAdder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/IdentifiableAdder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/InjectionAdder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/LccConverterStationAdder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/LineAdder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/LoadAdder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ShuntCompensatorAdder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/StaticVarCompensatorAdder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/SubstationAdder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ThreeWindingsTransformerAdder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/TieLineAdder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/TwoWindingsTransformerAdder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevel.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevelAdder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VscConverterStationAdder.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/AbstractHvdcConverterStationAdderAdapter.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/AbstractIdentifiableAdderAdapter.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/AbstractInjectionAdderAdapter.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/BatteryAdderAdapter.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/BusAdderAdapter.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/BusBreakerVoltageLevelAdapter.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/BusbarSectionAdderAdapter.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/DanglingLineAdderAdapter.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/GeneratorAdderAdapter.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/LccConverterStationAdderAdapter.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/LoadAdderAdapter.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/NodeBreakerVoltageLevelAdapter.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/ShuntCompensatorAdderAdapter.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/StaticVarCompensatorAdderAdapter.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/SubstationAdderAdapter.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/ThreeWindingsTransformerAdderAdapter.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/TwoWindingsTransformerAdderAdapter.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/VoltageLevelAdderAdapter.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/VscConverterStationAdderAdapter.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateBranchFeederBays.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateBranchFeederBaysBuilder.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateFeederBay.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateFeederBayBuilder.java
  iidm/iidm-reducer/src/main/java/com/powsybl/iidm/reducer/DefaultNetworkReducer.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractComplexIdentifiableXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractIdentifiableXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractSimpleIdentifiableXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractSwitchXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractTransformerXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/ShuntXml.java
Labels: Breaking Change

#2497 Create action to change shunt compensator position
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/action/ShuntCompensatorPositionAction.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/action/ShuntCompensatorPositionActionBuilder.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/SecurityAnalysisJsonModule.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/action/ShuntCompensatorPositionActionDeserializer.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/action/ShuntCompensatorPositionActionSerializer.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/json/JsonActionAndOperatorStrategyTest.java
  security-analysis/security-analysis-api/src/test/resources/ActionFileTest.json
  security-analysis/security-analysis-api/src/test/resources/ActionFileTestV1.0.json
Labels: Security Analysis, PR: ready-to-be-merged, PR: next-release, Action

#2455 AMPL solver
  ampl-converter/src/main/java/com/powsybl/ampl/converter/AbstractAmplNetworkUpdater.java
  ampl-converter/src/main/java/com/powsybl/ampl/converter/AmplElementReader.java
  ampl-converter/src/main/java/com/powsybl/ampl/converter/AmplNetworkReader.java
  ampl-converter/src/main/java/com/powsybl/ampl/converter/AmplNetworkUpdater.java
  ampl-converter/src/main/java/com/powsybl/ampl/converter/AmplNetworkUpdaterFactory.java
  ampl-converter/src/main/java/com/powsybl/ampl/converter/AmplReadableElement.java
  ampl-converter/src/main/java/com/powsybl/ampl/converter/DefaultAmplNetworkUpdater.java
  ampl-converter/src/main/java/com/powsybl/ampl/converter/DefaultAmplNetworkUpdaterFactory.java
  ampl-converter/src/main/java/com/powsybl/ampl/converter/OutputFileFormat.java
  ampl-executor/pom.xml
  ampl-executor/src/main/java/com/powsybl/ampl/executor/AbstractAmplModel.java
  ampl-executor/src/main/java/com/powsybl/ampl/executor/AmplConfig.java
  ampl-executor/src/main/java/com/powsybl/ampl/executor/AmplInputFile.java
  ampl-executor/src/main/java/com/powsybl/ampl/executor/AmplModel.java
  ampl-executor/src/main/java/com/powsybl/ampl/executor/AmplModelExecutionHandler.java
  ampl-executor/src/main/java/com/powsybl/ampl/executor/AmplModelRunner.java
  ampl-executor/src/main/java/com/powsybl/ampl/executor/AmplOutputFile.java
  ampl-executor/src/main/java/com/powsybl/ampl/executor/AmplParameters.java
  ampl-executor/src/main/java/com/powsybl/ampl/executor/AmplResults.java
  ampl-executor/src/main/java/com/powsybl/ampl/executor/EmptyAmplParameters.java
  ampl-executor/src/test/java/com/powsybl/ampl/executor/AmplConfigTest.java
  ampl-executor/src/test/java/com/powsybl/ampl/executor/AmplModelExecutionHandlerTest.java
  ampl-executor/src/test/java/com/powsybl/ampl/executor/DummyAmplModel.java
  ampl-executor/src/test/java/com/powsybl/ampl/executor/DummyAmplNetworkUpdater.java
  ampl-executor/src/test/resources/output_generators.txt
  distribution-core/pom.xml
  pom.xml
Labels: PR: ready-to-be-merged, PR: next-release

#2501 Create a fictitious substation during CGMES export when a voltage level does not have a substation
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
Labels: bug, CGMES, PR: ready-to-be-merged, PR: next-release

#2461 Introduce ScalingParameters for Scalable
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/AbstractCompoundScalable.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/AbstractScalable.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/DanglingLineScalable.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/GeneratorScalable.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/LoadScalable.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/ProportionalScalable.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/Scalable.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/ScalableAdapter.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/ScalingParameters.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/StackScalable.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/UpDownScalable.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/DanglingLineScalableTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/GeneratorScalableTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/LoadScalableTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/ScalableTest.java
Labels: Breaking Change, PR: next-release

#2500 Feature removing Hvdc line and its converter stations
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ModificationReports.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/RemoveHvdcLine.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/RemoveHvdcLineBuilder.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/RemoveHvdcLineTest.java
Labels: PR: ready-to-be-merged

#2505 CGMES. Test creation of fictitious substations
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportTest.java
Labels: CGMES, PR: ready-to-be-merged, Test

#2493 Matpower importer: Support lines with different nominal voltage at both ends
  matpower/matpower-converter/src/main/java/com/powsybl/matpower/converter/MatpowerImporter.java
  matpower/matpower-converter/src/test/java/com/powsybl/matpower/converter/MatpowerImporterTest.java
  matpower/matpower-converter/src/test/resources/ieee118.xiidm
  matpower/matpower-converter/src/test/resources/ieee14-inverted-voltage-limits.xiidm
  matpower/matpower-converter/src/test/resources/ieee14-phase-shifter.xiidm
  matpower/matpower-converter/src/test/resources/ieee14.xiidm
  matpower/matpower-converter/src/test/resources/ieee30-considering-base-voltage.xiidm
  matpower/matpower-converter/src/test/resources/ieee30.xiidm
  matpower/matpower-converter/src/test/resources/ieee300.xiidm
  matpower/matpower-converter/src/test/resources/ieee57.xiidm
Labels: PR: next-release, Matpower

#2508 CGMES import: CN is a property of DLs (can not be unique to a DL)
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractConductingEquipmentConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportTest.java
Labels: bug, CGMES, PR: ready-to-be-merged, PR: next-release

#2507 CGMES import: make substations property bags distinct when their region is defined twice (in BD and IGM)
  cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/CgmesConformity1ModifiedCatalog.java
  cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_duplicate_region/MicroGridTestConfiguration_EQ_BD.xml
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
  cgmes/cgmes-model/src/main/resources/CIM16.sparql
Labels: bug, CGMES, PR: ready-to-be-merged, PR: next-release

#2510 Add loading from platform config and serialization for ScalingParameters
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/ScalingParameters.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/json/JsonScalingParameters.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/json/ScalingParametersDeserializer.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/json/ScalingParametersJsonModule.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/json/ScalingParametersSerializer.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/ScalingParametersTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/json/JsonScalingParametersTest.java
  iidm/iidm-modification/src/test/resources/json/ScalingParameters.json
  iidm/iidm-modification/src/test/resources/json/ScalingParametersError.json
Labels: PR: ready-to-be-merged, PR: next-release, Scalable

#2517 Clean of CGMES options
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesMappingTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/EquipmentExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/ExportProfilesConsistencyTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/TopologyExportTest.java
Labels: CGMES, PR: ready-to-be-merged, PR: next-release

#2519 Fix: BusbarSection getters in node-breaker view only return a non-null BusbarSection if it is in their voltage level
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNetworkTest.java
Labels: bug, IIDM, PR: ready-to-be-merged, PR: next-release

#2520 Fix identifiable stream
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Network.java
Labels: bug, PR: ready-to-be-merged, PR: next-release

#2521 Remove duplicate code
  contingency/contingency-api/src/main/java/com/powsybl/contingency/contingency/list/AbstractEquipmentCriterionContingencyList.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/contingency/list/HvdcLineCriterionContingencyList.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/contingency/list/InjectionCriterionContingencyList.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/contingency/list/LineCriterionContingencyList.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/contingency/list/ThreeWindingsTransformerCriterionContingencyList.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/contingency/list/TwoWindingsTransformerCriterionContingencyList.java
Labels: PR: ready-to-be-merged

#2511 Fix doc for sensitivity thresholds
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityAnalysisParameters.java
Labels: PR: next-release

#2516 Creating an modification with wrong bus bar section now throws an exception
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ReplaceTeePointByVoltageLevelOnLine.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/ReplaceTeePointByVoltageLevelOnLineTest.java
  iidm/iidm-modification/src/test/resources/eurostag-replace-tee-point-by-voltage-level-on-line-bb.xml
Labels: PR: next-release

#2522 [Network modifications] Fix: Remove disconnectors and breakers in RemoveHvdcLine and RemoveVoltageLevel
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/RemoveHvdcLine.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/RemoveVoltageLevel.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/RemoveVoltageLevelTest.java
  iidm/iidm-modification/src/test/resources/eurostag-remove-voltage-level-nb.xml
Labels: bug, PR: ready-to-be-merged

#2518 Output reading behavior, read all files even if some throws
  ampl-converter/src/main/java/com/powsybl/ampl/converter/AmplNetworkReader.java
  ampl-converter/src/test/java/com/powsybl/ampl/converter/AmplNetworkReaderTest.java
  ampl-executor/pom.xml
  ampl-executor/src/main/java/com/powsybl/ampl/executor/AmplModel.java
  ampl-executor/src/main/java/com/powsybl/ampl/executor/AmplModelExecutionHandler.java
  ampl-executor/src/main/java/com/powsybl/ampl/executor/AmplParameters.java
  ampl-executor/src/main/java/com/powsybl/ampl/executor/AmplResults.java
  ampl-executor/src/main/java/com/powsybl/ampl/executor/EmptyAmplParameters.java
  ampl-executor/src/test/java/com/powsybl/ampl/executor/AmplModelExecutionHandlerTest.java
  ampl-executor/src/test/java/com/powsybl/ampl/executor/DummyAmplModel.java
  ampl-executor/src/test/java/com/powsybl/ampl/executor/SimpleAmplParameters.java
  ampl-executor/src/test/resources/output_indic.txt
  ampl-executor/src/test/resources/sample_model.run
  ampl-executor/src/test/resources/simple_output.txt
Labels: PR: next-release

#2513 CGMES pre-processors
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImportPreProcessor.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/CgmesImportPreAndPostProcessorsTest.java
Labels: PR: ready-to-be-merged

#2525 Add methods to access supplementary data in CGMES boundaries
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesBoundary.java
Labels: CGMES
