Repository powsybl/powsybl-core, pull requests merged in 2023-12, with the labels that each got.

#2787 Factorizing breadth/depth-first traversals
  math/src/main/java/com/powsybl/math/graph/UndirectedGraph.java
  math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java
Labels: December release

#2810 Fix iidm v1.11 equipment xsd
  iidm/iidm-serde/src/main/resources/xsd/iidm_equipment_V1_11.xsd
Labels: December release

#2796 BranchStatus renamed OperatingStatus and HVDC lines support
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/BranchStatus.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/OperatingStatus.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/OperatingStatusAdder.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/BranchStatusAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/OperatingStatusAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/OperatingStatusAdderImplProvider.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/OperatingStatusImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/extensions/OperatingStatusTest.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/extensions/BranchStatusSerDe.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/extensions/OperatingStatusSerDe.java
  iidm/iidm-serde/src/main/resources/xsd/operatingStatus.xsd
  iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/extensions/OperatingStatusXmlTest.java
  iidm/iidm-serde/src/test/resources/operatingStatusRef.xml
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractOperatingStatusTest.java
Labels: December release

#2814 Matpower export: fix low impedance branches and branches connected to same bus
  matpower/matpower-converter/src/main/java/com/powsybl/matpower/converter/MatpowerExporter.java
  matpower/matpower-converter/src/test/java/com/powsybl/matpower/converter/MatpowerExporterTest.java
  matpower/matpower-converter/src/test/resources/line-connected-same-bus.json
  matpower/matpower-converter/src/test/resources/small-impedance-line.json
Labels: PR: ready-to-be-merged, December release

#2788 Dynamic simulation results
  dynamic-simulation/dynamic-simulation-api/src/main/java/com/powsybl/dynamicsimulation/DynamicSimulationResult.java
  dynamic-simulation/dynamic-simulation-api/src/main/java/com/powsybl/dynamicsimulation/DynamicSimulationResultImpl.java
  dynamic-simulation/dynamic-simulation-api/src/main/java/com/powsybl/dynamicsimulation/TimelineEvent.java
  dynamic-simulation/dynamic-simulation-api/src/main/java/com/powsybl/dynamicsimulation/json/DynamicSimulationResultDeserializer.java
  dynamic-simulation/dynamic-simulation-api/src/main/java/com/powsybl/dynamicsimulation/json/DynamicSimulationResultSerializer.java
  dynamic-simulation/dynamic-simulation-api/src/test/java/com/powsybl/dynamicsimulation/AnotherDynamicSimulationProviderMock.java
  dynamic-simulation/dynamic-simulation-api/src/test/java/com/powsybl/dynamicsimulation/DynamicSimulationProviderMock.java
  dynamic-simulation/dynamic-simulation-api/src/test/java/com/powsybl/dynamicsimulation/DynamicSimulationResultTest.java
  dynamic-simulation/dynamic-simulation-api/src/test/java/com/powsybl/dynamicsimulation/json/DynamicSimulationResultJsonTest.java
  dynamic-simulation/dynamic-simulation-api/src/test/resources/DynamicSimulationFailedResult.json
  dynamic-simulation/dynamic-simulation-api/src/test/resources/DynamicSimulationResult.json
  dynamic-simulation/dynamic-simulation-api/src/test/resources/DynamicSimulationResultError.json
  dynamic-simulation/dynamic-simulation-tool/src/main/java/com/powsybl/dynamicsimulation/tool/DynamicSimulationTool.java
  dynamic-simulation/dynamic-simulation-tool/src/test/java/com/powsybl/dynamicsimulation/tool/DynamicSimulationProviderMock.java
  dynamic-simulation/dynamic-simulation-tool/src/test/java/com/powsybl/dynamicsimulation/tool/DynamicSimulationToolTest.java
Labels: December release

#2807 Fix identifier contingency list deserialization
  contingency/contingency-api/src/main/java/com/powsybl/contingency/contingency/list/DefaultContingencyList.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/contingency/list/HvdcLineCriterionContingencyList.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/contingency/list/IdentifierContingencyList.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/contingency/list/InjectionCriterionContingencyList.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/contingency/list/LineCriterionContingencyList.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/contingency/list/ListOfContingencyLists.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/contingency/list/ThreeWindingsTransformerCriterionContingencyList.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/contingency/list/TieLineCriterionContingencyList.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/contingency/list/TwoWindingsTransformerCriterionContingencyList.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/json/AbstractEquipmentCriterionContingencyListDeserializer.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/json/ContingencyDeserializer.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/json/ContingencyElementDeserializer.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/json/ContingencyListDeserializer.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/json/CriterionDeserializer.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/json/DefaultContingencyListDeserializer.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/json/HvdcLineCriterionContingencyListDeserializer.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/json/IdentifierContingencyListDeserializer.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/json/IdentifierContingencyListSerializer.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/json/IdentifierDeserializer.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/json/InjectionCriterionContingencyListDeserializer.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/json/LineCriterionContingencyListDeserializer.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/json/ListOfContingencyListsDeserializer.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/json/ThreeWindingsTransformerCriterionContingencyListDeserializer.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/json/TieLineCriterionContingencyListDeserializer.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/json/TwoWindingsTransformerCriterionContingencyListDeserializer.java
  contingency/contingency-api/src/test/java/com/powsybl/contingency/json/ListOfContingencyListsJsonTest.java
  contingency/contingency-api/src/test/java/com/powsybl/contingency/json/NetworkElementIdentifierContingencyListJsonTest.java
  contingency/contingency-api/src/test/resources/contingencyListsList.json
  contingency/contingency-api/src/test/resources/identifierContingencyList.json
  contingency/contingency-api/src/test/resources/identifierContingencyListReferenceForLessThan1_2.json
  contingency/contingency-api/src/test/resources/identifierContingencyListTest.json
  contingency/contingency-api/src/test/resources/identifierContingencyListv1_0.json
  contingency/contingency-api/src/test/resources/identifierContingencyListv1_1.json
Labels: December release, Contingency

#2827 CGMES import: fix loading limits conversion
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/TerminalMapping.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/OperationalLimitConversion.java
Labels: bug, December release

#2824 Precise error and log messages for extensions
  iidm/iidm-impl/pom.xml
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/BusbarSectionPositionImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/CoordinatedReactiveControlImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/GeneratorEntsoeCategoryImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/HvdcAngleDroopActivePowerControlImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/LoadDetailImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ReferencePrioritiesImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ReferencePriorityImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/StandbyAutomatonImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/extensions/BusbarSectionPositionImplTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/extensions/GeneratorEntsoeCategoryTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/extensions/LoadDetailTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/extensions/StandbyAutomatonTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractCoordinatedReactiveControlTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractHvdcAngleDroopActivePowerTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractReferencePrioritiesTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractStandbyAutomatonTest.java
Labels: PR: ready-to-be-merged

#2821 Pinned versions for GitHub actions
  .github/workflows/maven.yml
Labels: PR: ready-to-be-merged
