Repository powsybl/powsybl-core, pull requests merged in 2023-09, with the labels that each got.

#2660 add getBusCount() to network and voltage level busbreakerview for symetry
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Network.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusBreakerVoltageLevel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNetworkTest.java
Labels: PR: ready-to-be-merged

#2691 CGMES import: switches may not have a name attribute
  cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/CgmesConformity1ModifiedCatalog.java
  cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_NL_v2_switch_without_name/MicroGridTestConfiguration_BC_NL_EQ_V2.xml
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
  cgmes/cgmes-model/src/main/resources/CIM16.sparql
Labels: CGMES

#2693 CGMES fix export SV unitary test when ratio and phase tap changer are present
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/StateVariablesExportTest.java
Labels: PR: next-release

#2648 CGMES : import optional ratedS value of transformers
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/CgmesT2xModel.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/CgmesT3xModel.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/ConvertedT2xModel.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/ConvertedT3xModel.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/InterpretedT2xModel.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/InterpretedT3xModel.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/ThreeWindingsTransformerConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/TwoWindingsTransformerConversion.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/Cgmes3ConversionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/EquipmentExportTest.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesNames.java
  cgmes/cgmes-model/src/main/resources/CIM16.sparql
Labels: PR: ready-to-be-merged, PR: next-release

#2695 Matpower export: fix nan in targetQ
  matpower/matpower-converter/src/main/java/com/powsybl/matpower/converter/MatpowerExporter.java
  matpower/matpower-converter/src/test/java/com/powsybl/matpower/converter/MatpowerExporterTest.java
  matpower/matpower-converter/src/test/resources/sim1-with-nan-target-q.json
Labels: bug

#2673 CGMES: Equivalent shunts not exported in SSH, SV
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EquivalentShuntConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/EquivalentShuntEq.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/EquipmentExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/StateVariablesExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/SteadyStateHypothesisExportTest.java
Labels: PR: next-release

#2696 Remove adding transformers from the network
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/ThreeWindingsTransformerConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/TwoWindingsTransformerConversion.java
  ieee-cdf/ieee-cdf-converter/src/main/java/com/powsybl/ieeecdf/converter/IeeeCdfImporter.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Network.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ThreeWindingsTransformerAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TwoWindingsTransformerAdderImpl.java
  iidm/iidm-scripting/src/test/groovy/com/powsybl/iidm/network/scripting/ThreeWindingsTransformerExtensionTest.groovy
  iidm/iidm-scripting/src/test/groovy/com/powsybl/iidm/network/scripting/TwoWindingsTransformerExtensionTest.groovy
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractThreeWindingsTransformerTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractTwoWindingsTransformerTest.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/AbstractTransformerXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NetworkXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/ThreeWindingsTransformerXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/TwoWindingsTransformerXml.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/NetworkXmlTest.java
  matpower/matpower-converter/src/main/java/com/powsybl/matpower/converter/MatpowerImporter.java
  psse/psse-converter/src/main/java/com/powsybl/psse/converter/TransformerConverter.java
Labels: Breaking Change, PR: next-release

#2618 CGMES export: use region and base voltage references from given BD file
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/ReferenceDataProvider.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportContextTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/ReferenceDataProviderTest.java
  cgmes/cgmes-conversion/src/test/resources/reference-data-provider/sample_EQBD.xml
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesModel.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesModelFactory.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesNamespace.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/InMemoryCgmesModel.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/triplestore/CgmesModelTripleStore.java
  cgmes/cgmes-model/src/main/resources/CIM16.sparql
Labels: PR: next-release

#2665 Matpower limits export
  matpower/matpower-converter/src/main/java/com/powsybl/matpower/converter/MatpowerExporter.java
  matpower/matpower-converter/src/test/java/com/powsybl/matpower/converter/MatpowerExporterTest.java
  matpower/matpower-converter/src/test/resources/be.json
  matpower/matpower-converter/src/test/resources/fourSubstationFactory.json
  matpower/matpower-converter/src/test/resources/sim1-with-apparent-power-limits.json
  matpower/matpower-converter/src/test/resources/sim1-with-current-limits.json
  matpower/matpower-converter/src/test/resources/sim1-with-current-limits2.json
Labels: PR: ready-to-be-merged, PR: next-release

#2705 Remove deprecated sensitivity function types
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityFactor.java
  sensitivity-analysis-api/src/main/java/com/powsybl/sensitivity/SensitivityFunctionType.java
Labels: Breaking Change, PR: ready-to-be-merged

#2708 Fix IEEE 118 nominal voltages
  ieee-cdf/ieee-cdf-converter/src/main/java/com/powsybl/ieeecdf/converter/IeeeCdfNetworkFactory.java
  ieee-cdf/ieee-cdf-converter/src/test/resources/ieee118cdf.xiidm
Labels: PR: next-release

#2709 CGMES: preserve original switch type and use it for export; update alias type for terminals of DLs
  cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/CgmesConformity1ModifiedCatalog.java
  cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_NL_v2_switch_type_preserved/MicroGridTestConfiguration_BC_NL_EQ_V2.xml
  cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_NL_v2_switch_type_preserved/MicroGridTestConfiguration_BC_NL_SSH_V2.xml
  cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MiniGrid/NodeBreaker/BaseCase_Complete_v3_switch_type_preserved/MiniGridTestConfiguration_BC_EQ_v3.0.0.xml
  cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MiniGrid/NodeBreaker/BaseCase_Complete_v3_switch_type_preserved/MiniGridTestConfiguration_BC_SSH_v3.0.0.xml
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SwitchConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/SwitchEq.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/issues/SwitchExportTest.java
  cgmes/cgmes-model/src/main/resources/CIM14.sparql
Labels: CGMES, PR: next-release

#2694 Added generator remote reactive power control iIDM extension XML serialization
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/extensions/RemoteReactivePowerControlXmlSerializer.java
  iidm/iidm-xml-converter/src/main/resources/xsd/remoteReactivePowerControl_V1_0.xsd
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/extensions/RemoteReactivePowerControlXmlTest.java
  iidm/iidm-xml-converter/src/test/resources/V1_0/remoteReactivePowerControlNotSupported.xml
  iidm/iidm-xml-converter/src/test/resources/V1_1/remoteReactivePowerControlNotSupported.xml
  iidm/iidm-xml-converter/src/test/resources/V1_10/remoteReactivePowerControlRef.xml
  iidm/iidm-xml-converter/src/test/resources/V1_11/remoteReactivePowerControlRef.xml
  iidm/iidm-xml-converter/src/test/resources/V1_2/remoteReactivePowerControlNotSupported.xml
  iidm/iidm-xml-converter/src/test/resources/V1_3/remoteReactivePowerControlNotSupported.xml
  iidm/iidm-xml-converter/src/test/resources/V1_4/remoteReactivePowerControlNotSupported.xml
  iidm/iidm-xml-converter/src/test/resources/V1_5/remoteReactivePowerControlRef.xml
  iidm/iidm-xml-converter/src/test/resources/V1_6/remoteReactivePowerControlRef.xml
  iidm/iidm-xml-converter/src/test/resources/V1_7/remoteReactivePowerControlRef.xml
  iidm/iidm-xml-converter/src/test/resources/V1_8/remoteReactivePowerControlRef.xml
  iidm/iidm-xml-converter/src/test/resources/V1_9/remoteReactivePowerControlRef.xml
Labels: PR: ready-to-be-merged, PR: next-release

#2678 Subnetworks XIIDM export
  commons-test/src/main/java/com/powsybl/commons/test/AbstractConverterTest.java
  commons/src/main/java/com/powsybl/commons/extensions/ExtensionProviders.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractNetwork.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/NetworkXml.java
  iidm/iidm-xml-converter/src/main/resources/xsd/iidm_V1_11.xsd
  iidm/iidm-xml-converter/src/main/resources/xsd/iidm_equipment_V1_11.xsd
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/IdentifiableExtensionXmlSerializerTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/NetworkXmlTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/extensions/util/NetworkSourceExtension.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/extensions/util/NetworkSourceExtensionImpl.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/extensions/util/NetworkSourceExtensionXmlSerializer.java
  iidm/iidm-xml-converter/src/test/resources/V1_10/subnetworks.xml
  iidm/iidm-xml-converter/src/test/resources/V1_11/multiple-subnetwork-levels.xml
  iidm/iidm-xml-converter/src/test/resources/V1_11/subnetworks.xml
  iidm/iidm-xml-converter/src/test/resources/V1_5/subnetworks.xml
  iidm/iidm-xml-converter/src/test/resources/V1_6/subnetworks.xml
  iidm/iidm-xml-converter/src/test/resources/V1_7/subnetworks.xml
  iidm/iidm-xml-converter/src/test/resources/V1_8/subnetworks.xml
  iidm/iidm-xml-converter/src/test/resources/V1_9/subnetworks.xml
Labels: IIDM, XIIDM, PR: next-release

#2663 Adapt CGMES export for merge with subnetworks
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/TopologyExport.java
Labels: PR: ready-to-be-merged, PR: next-release

#2710 Proposal for handling UpDown scalable get steady state power instead of throwing exception
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/DanglingLineScalable.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/GeneratorScalable.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/LoadScalable.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/ProportionalScalable.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/Scalable.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/ScalableAdapter.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/StackScalable.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/UpDownScalable.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/UpDownScalableTest.java
Labels: PR: next-release

#2711 Clean CGMES export with subnetworks
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
Labels: PR: next-release

#2676 Rename dangling line ucteXnodeCode to pairingKey
  ampl-converter/src/main/java/com/powsybl/ampl/converter/AmplUtil.java
  cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/CgmesConformity1NetworkCatalog.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ACLineSegmentConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractConductingEquipmentConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/TopologyExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/network/compare/Comparison.java
  cgmes/cgmes-extensions/src/test/resources/eurostag_cgmes_line_boundary_node.xml
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/DanglingLine.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/DanglingLineAdder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/TieLine.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/TieLineUtil.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/DanglingLineAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/DanglingLineImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TieLineAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TieLineImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/MergeTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/TieLineTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/util/SVTest.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/ReplaceTieLinesByLines.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/util/ModificationReports.java
  iidm/iidm-modification/src/test/resources/eurostag-replace-tl.xml
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractComponentCalculationBugWhenMergingTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractConnectedComponentWithTieLineBugTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractDanglingLineTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractMergeNetworkTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNullPointerWhenRemovingMergedLineBugTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractSubnetworksExplorationTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractTieLineTest.java
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/EurostagTutorialExample1Factory.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/DanglingLineXml.java
  iidm/iidm-xml-converter/src/main/java/com/powsybl/iidm/xml/TieLineXml.java
  iidm/iidm-xml-converter/src/main/resources/xsd/iidm_V1_11.xsd
  iidm/iidm-xml-converter/src/main/resources/xsd/iidm_equipment_V1_11.xsd
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/NetworkXmlTest.java
  iidm/iidm-xml-converter/src/test/resources/V1_11/multiple-subnetwork-levels.xml
  iidm/iidm-xml-converter/src/test/resources/V1_11/subnetworks.xml
  iidm/iidm-xml-converter/src/test/resources/V1_11/tieline.xml
  iidm/iidm-xml-converter/src/test/resources/V1_11/tielineWithAliases.xml
  iidm/iidm-xml-converter/src/test/resources/V1_11/tl-loading-limits.xml
  ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/DefaultNamingStrategy.java
  ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteExporter.java
  ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteImporter.java
Labels: Breaking Change, PR: next-release

#2717 CGMES option to force import of node/breaker as bus/breaker
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/CgmesConformity1ConversionTest.java
Labels: CGMES, PR: ready-to-be-merged, PR: next-release

#2721 ThreeSides to integer conversion helper in enum
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ThreeSides.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractThreeWindingsTransformerTest.java
Labels: PR: next-release

#2718 Rename 'Network.create(Network...)' in 'Network.merge(Network...)'
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/CgmesConformity3ConversionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportTest.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Network.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/NetworkFactory.java
  iidm/iidm-api/src/test/java/com/powsybl/iidm/network/NetworkFactoryMock.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkFactoryImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/MergeTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractAliasesTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractComponentCalculationBugWhenMergingTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractMergeNetworkTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNullPointerWhenRemovingMergedLineBugTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractSubnetworksExplorationTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/NetworkXmlTest.java
  ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/UcteExporterTest.java
  ucte/ucte-util/src/test/java/com/powsybl/ucte/util/UcteAliasesCreationTest.java
Labels: Breaking Change, PR: next-release

#2674 List dynamic models
  dynamic-simulation/dynamic-simulation-dsl/src/main/java/com/powsybl/dynamicsimulation/groovy/DynamicModelGroovyExtension.java
  dynamic-simulation/dynamic-simulation-dsl/src/main/java/com/powsybl/dynamicsimulation/groovy/EventModelGroovyExtension.java
  dynamic-simulation/dynamic-simulation-dsl/src/test/groovy/com/powsybl/dynamicsimulation/groovy/DummyDynamicModelGroovyExtension.groovy
  dynamic-simulation/dynamic-simulation-dsl/src/test/groovy/com/powsybl/dynamicsimulation/groovy/DummyEventModelGroovyExtension.groovy
  dynamic-simulation/dynamic-simulation-tool/pom.xml
  dynamic-simulation/dynamic-simulation-tool/src/main/java/com/powsybl/dynamicsimulation/tool/ListDynamicSimulationModelsTool.java
  dynamic-simulation/dynamic-simulation-tool/src/test/java/com/powsybl/dynamicsimulation/tool/DynamicSimulationProviderMock.java
  dynamic-simulation/dynamic-simulation-tool/src/test/java/com/powsybl/dynamicsimulation/tool/DynamicSimulationToolTest.java
  dynamic-simulation/dynamic-simulation-tool/src/test/java/com/powsybl/dynamicsimulation/tool/ListDynamicSimulationModelsToolTest.java
Labels: PR: next-release
