Repository powsybl/powsybl-core, pull requests merged in 2023-06, with the labels that each got.

#2592 CGMES: Export all SvPowerflow for switches
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/StateVariablesExportTest.java
Labels: CGMES

#2593 SV: fix DC approximation
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/SV.java
  iidm/iidm-api/src/test/java/com/powsybl/iidm/network/util/SVTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/util/SVTest.java
Labels: PR: ready-to-be-merged, PR: next-release

#2599 Fix Java >= 19 build
  ampl-converter/src/test/resources/inputs/eurostag-tutorial-example1-branches-tl.txt
  cgmes/cgmes-extensions/src/test/resources/eurostag_cgmes_line_boundary_node.xml
  iidm/iidm-modification/src/test/resources/eurostag-replace-tl.xml
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/EurostagTutorialExample1Factory.java
Labels: bug, PR: next-release

#2596 Fix Ampl Writer
  ampl-converter/src/main/java/com/powsybl/ampl/converter/AmplNetworkWriter.java
  ampl-converter/src/test/resources/inputs/three-windings-transformers-branches.txt
  ampl-converter/src/test/resources/inputs/three-windings-transformers-tct.txt
Labels: PR: ready-to-be-merged, PR: next-release

#2601 Remove remaining xsd and reference files
  entsoe-util/src/main/resources/xsd/mergedXnode_V1_0.xsd
  entsoe-util/src/main/resources/xsd/mergedXnode_V1_1.xsd
  entsoe-util/src/main/resources/xsd/xnode.xsd
  entsoe-util/src/test/resources/mergedXnodeRef.xml
  entsoe-util/src/test/resources/xnodeRef.xml
Labels: PR: next-release

#2602 Update javadoc following halfLine replacement
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/TwoWindingsTransformerConversion.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/DanglingLine.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/TieLine.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/SV.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/TieLineUtil.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergedLine.java
  ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteExporter.java
Labels: PR: next-release

#2590 Update wording for "section identifiable not found"
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AbstractCreateConnectableFeederBays.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AbstractLineConnectionModification.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateCouplingDevice.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/util/ModificationLogs.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/util/ModificationReports.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/ConnectVoltageLevelOnLineTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateBranchFeederBaysTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateCouplingDeviceTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateFeederBayTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateLineOnLineTest.java
Labels: PR: next-release

#2600 Multiple data sources
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/MultipleDataSourceTest.java
  commons/src/main/java/com/powsybl/commons/datasource/DataSource.java
  commons/src/main/java/com/powsybl/commons/datasource/MultipleReadOnlyDataSource.java
  commons/src/test/java/com/powsybl/commons/datasource/MultipleReadOnlyDataSourceTest.java
  commons/src/test/java/com/powsybl/commons/datasource/ZipFileDataSourceTest.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Importers.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Network.java
  iidm/iidm-api/src/test/java/com/powsybl/iidm/network/ImportersTest.java
Labels: CGMES, Breaking Change, PR: next-release, Feature

#2605 [Scalable] If equipment is disconnected, then it is not scaled
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/DanglingLineScalable.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/GeneratorScalable.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/LoadScalable.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/Scalable.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/ScalingParameters.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/DanglingLineScalableTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/GeneratorScalableTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/LoadScalableTest.java
Labels: PR: ready-to-be-merged, Scalable

#2610 Fix handling of T-Point during CGMES Bus-Branch import
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractConductingEquipmentConversion.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/EqOnlyConversionTest.java
  cgmes/cgmes-conversion/src/test/resources/t-line.xml
Labels: bug, CGMES, PR: ready-to-be-merged

#2463 CGMES : Implement a pre-processor that completes the CGMES model with missing containers before starting the conversion
  cgmes/cgmes-completion/pom.xml
  cgmes/cgmes-completion/src/main/java/com/powsybl/cgmes/completion/CreateMissingContainersPreProcessor.java
  cgmes/cgmes-completion/src/test/java/com/powsybl/cgmes/completion/CgmesCompletionTest.java
  cgmes/cgmes-completion/src/test/resources/com/powsybl/config/test/config.yml
  cgmes/cgmes-completion/src/test/resources/com/powsybl/config/test/filelist.txt
  cgmes/cgmes-completion/src/test/resources/logback-test.xml
  cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/CgmesConformity1ModifiedCatalog.java
  cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MiniGrid/NodeBreaker/BaseCase_Complete_v3_missing_voltage_level/MiniGridTestConfiguration_BC_EQ_v3.0.0.xml
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/AbstractCgmesModel.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesNames.java
  cgmes/cgmes-model/src/main/resources/CIM16.sparql
  cgmes/pom.xml
  distribution-core/pom.xml
Labels: PR: ready-to-be-merged

#2611 Clean some deprecated methods
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesBoundary.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CurrentLimitsMapping.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/FakeTapChangerConversionTest.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesModel.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/InMemoryCgmesModel.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Bus.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Identifiable.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/StaticVarCompensator.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/StaticVarCompensatorAdder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ValidationUtil.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevel.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/LimitViolationUtils.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/Networks.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/AbstractScalable.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/Scalable.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/tripping/BranchTripping.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/GeneratorScalableTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/ScalableTest.java
  loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java
Labels: PR: ready-to-be-merged

#2575 Remove CGMES properties and aliases from tie lines: keep mapping data in dangling lines
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/NamingStrategy.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ACLineSegmentConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractConductingEquipmentConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/CgmesConformity3ConversionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesMappingTest.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java
  iidm/iidm-mergingview/src/main/java/com/powsybl/iidm/mergingview/MergedLine.java
  iidm/iidm-mergingview/src/test/java/com/powsybl/iidm/mergingview/DanglingLineAdapterTest.java
  iidm/iidm-xml-converter/src/test/java/com/powsybl/iidm/xml/ShuntCompensatorXmlTest.java
  ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteExporter.java
  ucte/ucte-util/src/main/java/com/powsybl/ucte/util/UcteAliasesCreation.java
Labels: CGMES

#2623 Invalid components after dangling lines merging and tie lines removal
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TieLineAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TieLineImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/ComponentCalculationBugWhenMergingTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractComponentCalculationBugWhenMergingTest.java
Labels: bug

#2598 CGMES export: improve default ratedS value
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/PowerTransformerEq.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/SynchronousMachineEq.java
Labels: PR: ready-to-be-merged
