Repository powsybl/powsybl-core, pull requests merged in 2024-03, with the labels that each got.

#2910 CGMES. Fix access to busbar section container in bus/breaker import
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/BusbarSectionConversion.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/BusbarSectionConversionTest.java
  cgmes/cgmes-conversion/src/test/resources/bbs-busbreaker_EQ.xml
  cgmes/cgmes-conversion/src/test/resources/bbs-busbreaker_TP.xml
  cgmes/cgmes-conversion/src/test/resources/bbs-busbreaker_TP_withoutLinkToTN.xml
  cgmes/cgmes-conversion/src/test/resources/bbs-busbreaker_TP_withoutTN.xml
Labels: bug, CGMES, PR: next-release

#2905 CGMES condensers shall not have generating units
  cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/CgmesConformity1Catalog.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/EntsoeCategoryPostProcessor.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SynchronousMachineConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/SynchronousMachineEq.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/CondenserImportExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesNamingStrategyTest.java
  cgmes/cgmes-conversion/src/test/resources/issues/condenser2_EQ.xml
  cgmes/cgmes-conversion/src/test/resources/issues/condenser3_EQ.xml
  cgmes/cgmes-conversion/src/test/resources/issues/condenser3_SSH.xml
  cgmes/cgmes-model-test/src/main/java/com/powsybl/cgmes/model/test/CgmesModelTester.java
  cgmes/cgmes-model-test/src/main/java/com/powsybl/cgmes/model/test/Cim14SmallCasesCatalog.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesModel.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/InMemoryCgmesModel.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/triplestore/CgmesModelTripleStore.java
  cgmes/cgmes-model/src/main/resources/CIM100.sparql
  cgmes/cgmes-model/src/main/resources/CIM14.sparql
  cgmes/cgmes-model/src/main/resources/CIM16.sparql
  matpower/matpower-converter/src/test/resources/be.json
Labels: bug, CGMES, Deprecated, PR: next-release, March release

#2823 Update to parent 18 with default groovydoc attach instead of build-helper-maven-plugin
  loadflow/loadflow-scripting/pom.xml
  pom.xml
Labels: PR: do-not-merge, March release

#2881 Add "tieLineCriterion" in options for contingency list type deserialization
  contingency/contingency-api/src/main/java/com/powsybl/contingency/json/ContingencyListDeserializer.java
  contingency/contingency-api/src/test/java/com/powsybl/contingency/json/ListOfContingencyListsJsonTest.java
  contingency/contingency-api/src/test/resources/contingencyListsList.json
Labels: March release

#2915 Add new field Name in equals and hash code
  contingency/contingency-api/src/main/java/com/powsybl/contingency/Contingency.java
  contingency/contingency-api/src/test/java/com/powsybl/contingency/ContingencyTest.java
Labels: PR: ready-to-be-merged, March release

#2749 CGMES export: export fossilFuel and hydroPowerPlant
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SynchronousMachineConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/GeneratingUnitEq.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/naming/CgmesObjectReference.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/EquipmentExportTest.java
  cgmes/cgmes-model/src/main/resources/CIM100.sparql
  cgmes/cgmes-model/src/main/resources/CIM16.sparql
  triple-store/triple-store-api/src/main/java/com/powsybl/triplestore/api/PropertyBag.java
Labels: CGMES, March release

#2921 Use reference priority extension
  cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/CgmesConformity1ModifiedCatalog.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SynchronousMachineConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/CondenserImportExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/CgmesConformity1ConversionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/StateVariablesExportTest.java
Labels: March release

#2919 Add VoltageRegulation extension
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/VoltageRegulation.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/VoltageRegulationAdder.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VoltageRegulationAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/VoltageRegulationAdderImplProvider.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/VoltageRegulationImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/extensions/VoltageRegulationTest.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/extensions/VoltageRegulationSerDe.java
  iidm/iidm-serde/src/main/resources/xsd/voltageRegulation_V1_0.xsd
  iidm/iidm-serde/src/main/resources/xsd/voltageRegulation_V1_0_legacy.xsd
  iidm/iidm-serde/src/main/resources/xsd/voltageRegulation_V1_1.xsd
  iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/test/VoltageRegulationSerDeTest.java
  iidm/iidm-serde/src/test/resources/V1_12/voltageRegulationRoundTripRef.xml
Labels: March release

#2619 CGMES export: tie lines as two separate equipment (ACLSs)
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/TerminalMapping.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractConductingEquipmentConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/TopologyExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesNamingStrategyTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/ExportXmlCompare.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/SteadyStateHypothesisExportTest.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/DanglingLineData.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/TieLineUtil.java
Labels: March release

#2914 Export ActivePowerControl extension in all versions of IIDM
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/NetworkSerDe.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/extensions/ActivePowerControlSerDe.java
  iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/extensions/ActivePowerControlXmlTest.java
  iidm/iidm-serde/src/test/resources/V1_0/batteryNetworkWithActivePowerControlRoundTripRef.xml
Labels: March release

#2933 CGMES. Fix performance regression checking for condensers
  cgmes/cgmes-model/src/main/resources/CIM16.sparql
  matpower/matpower-converter/src/test/resources/be.json
Labels: bug, CGMES

#2934 Move properties during network merge and detach
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractNetwork.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SubnetworkImpl.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractMergeNetworkTest.java
Labels: bug

#2935 Use double format for limit reduction values
  action/action-dsl/src/main/java/com/powsybl/action/dsl/ast/AbstractBranchActionExpressionNode.java
  action/action-dsl/src/main/java/com/powsybl/action/dsl/ast/ActionExpressionEvaluator.java
  action/action-dsl/src/main/java/com/powsybl/action/dsl/ast/ActionExpressionHelper.java
  action/action-dsl/src/main/java/com/powsybl/action/dsl/ast/AllOverloadedNode.java
  action/action-dsl/src/main/java/com/powsybl/action/dsl/ast/IsOverloadedNode.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Branch.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ThreeWindingsTransformer.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/LimitViolationUtils.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractConnectableBranch.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ThreeWindingsTransformerImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TieLineImpl.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/LimitViolation.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/LimitViolationDetector.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/Security.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/detectors/DefaultLimitViolationDetector.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/LimitViolationDeserializer.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/limitreduction/LimitReduction.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/detectors/LimitViolationDetectorForThreeWindingsTransformerTest.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/detectors/LimitViolationDetectorTest.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/limitreduction/LimitReductionListTest.java
  security-analysis/security-analysis-api/src/test/resources/LimitReductions.json
  security-analysis/security-analysis-api/src/test/resources/PostContingencyResultTest.json
  security-analysis/security-analysis-api/src/test/resources/SecurityAnalysisResult.json
  shortcircuit-api/src/test/java/com/powsybl/shortcircuit/TestingResultFactory.java
Labels: Breaking Change, PR: do-not-merge, March release

#2904 Add a pairing key setter for unpaired dangling line
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/DanglingLine.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/DanglingLineImpl.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractDanglingLineTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractTieLineTest.java
Labels: Breaking Change, March release

#2830 Add elements not found in network for contingencies
  contingency/contingency-api/src/main/java/com/powsybl/contingency/contingency/list/IdentifierContingencyList.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/contingency/list/identifier/IdBasedNetworkElementIdentifier.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/contingency/list/identifier/NetworkElementIdentifier.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/contingency/list/identifier/NetworkElementIdentifierList.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/contingency/list/identifier/VoltageLevelAndOrderNetworkElementIdentifier.java
  contingency/contingency-api/src/test/java/com/powsybl/contingency/NetworkElementIdentifierContingencyListTest.java
  contingency/contingency-dsl/src/main/groovy/com/powsybl/contingency/dsl/ContingencyDslLoader.groovy
  contingency/contingency-dsl/src/main/java/com/powsybl/contingency/dsl/GroovyContingencyList.java
  contingency/contingency-dsl/src/test/java/com/powsybl/contingency/dsl/GroovyContingencyListTest.java
Labels: March release

#2936 PSSE: Fix Qrecord management
  psse/psse-model/src/main/java/com/powsybl/psse/model/io/AbstractRecordGroup.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/io/LegacyTextReader.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/io/RecordGroupIO.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/io/RecordGroupIOJson.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/io/RecordGroupIOLegacyText.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/pf/io/CaseIdentificationData.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/pf/io/GneDeviceData.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/pf/io/MultiTerminalDcTransmissionLineData.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/pf/io/PowerFlowRawData32.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/pf/io/PowerFlowRawData33.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/pf/io/PowerFlowRawData35.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/pf/io/PowerFlowRawDataAllVersions.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/pf/io/PowerFlowRawxDataAllVersions.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/pf/io/TransformerData.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/pf/io/TransformerImpedanceCorrectionTablesData.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/pf/io/TwoTerminalDcTransmissionLineData.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/pf/io/VoltageSourceConverterDcTransmissionLineData.java
  psse/psse-model/src/test/java/com/powsybl/psse/model/PsseRawDataTest.java
  psse/psse-model/src/test/resources/IEEE_14_bus_Q_record_rev35.json
  psse/psse-model/src/test/resources/IEEE_14_bus_Q_record_rev35.raw
Labels: PR: next-release, March release

#2948 Reject null values for IdentifiableCriterion
  iidm/iidm-criteria/src/main/java/com/powsybl/iidm/criteria/IdentifiableCriterion.java
  iidm/iidm-criteria/src/main/java/com/powsybl/iidm/criteria/json/IdentifiableCriterionDeserializer.java
  iidm/iidm-criteria/src/test/java/com/powsybl/iidm/criteria/IdentifiableCriterionTest.java
  iidm/iidm-criteria/src/test/java/com/powsybl/iidm/criteria/json/NetworkElementCriterionModuleTest.java
  iidm/iidm-criteria/src/test/resources/criterion/identifiable-criteria.json
Labels: March release

#2949 `TemporaryDurationCriterion` improvements
  iidm/iidm-criteria/src/main/java/com/powsybl/iidm/criteria/duration/EqualityTemporaryDurationCriterion.java
  iidm/iidm-criteria/src/main/java/com/powsybl/iidm/criteria/duration/IntervalTemporaryDurationCriterion.java
  iidm/iidm-criteria/src/test/java/com/powsybl/iidm/criteria/duration/IntervalTemporaryDurationCriterionTest.java
Labels: March release

#2950 Add a builder for LimitReductions
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/json/limitreduction/LimitReductionDeserializer.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/limitreduction/LimitReduction.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/distributed/SecurityAnalysisExecutionHandlersTest.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/json/limitreduction/LimitReductionModuleTest.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/limitreduction/LimitReductionBuilderTest.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/limitreduction/LimitReductionListTest.java
  security-analysis/security-analysis-api/src/test/resources/LimitReductions.json
Labels: Breaking Change, March release

#2939 Support of validation level for missing permanent limit
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Network.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ValidationUtil.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractLoadingLimits.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractLoadingLimitsAdder.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ActivePowerLimitsAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ApparentPowerLimitsAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/CurrentLimitsAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/OperationalLimitsGroupImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/OperationalLimitsGroupsImpl.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/AbstractTreeDataImporter.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/ConnectableSerDeUtil.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/DanglingLineSerDe.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/ImportOptions.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/LineSerDe.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/NetworkDeserializerContext.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/NetworkSerDe.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/ThreeWindingsTransformerSerDe.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/TieLineSerDe.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/TwoWindingsTransformerSerDe.java
  iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/LoadingLimitsXmlTest.java
  iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/XMLImporterTest.java
  iidm/iidm-serde/src/test/resources/V1_12/withoutPermanentLimit.xml
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNetworkTest.java
Labels: Breaking Change, PR: ready-to-be-merged, March release

#2954 Add convenient creation methods for IntervalTemporaryDurationCriterion
  iidm/iidm-criteria/src/main/java/com/powsybl/iidm/criteria/duration/IntervalTemporaryDurationCriterion.java
  iidm/iidm-criteria/src/test/java/com/powsybl/iidm/criteria/duration/IntervalTemporaryDurationCriterionTest.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/json/limitreduction/LimitReductionModuleTest.java
Labels: PR: ready-to-be-merged, March release

#2929 Export tculControlMode as volt by default in CGMES 2.4.15 and prevent export of the attribute in 3.0
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMappingForTransformers.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/TapChangerEq.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesNamespace.java
  cgmes/cgmes-model/src/main/resources/CIM16.sparql
Labels: PR: ready-to-be-merged, March release

#2726 CGMES export. Preserve original class of generators. Fix synchronous machine type. Fix operating mode
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EquivalentInjectionConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ExternalNetworkInjectionConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SynchronousMachineConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/EquivalentInjectionEq.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/ExternalNetworkInjectionEq.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/EquipmentExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/ExportXmlCompare.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/SteadyStateHypothesisExportTest.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesNames.java
  cgmes/cgmes-model/src/main/resources/CIM100.sparql
  cgmes/cgmes-model/src/main/resources/CIM16.sparql
Labels: CGMES, PR: ready-to-be-merged, March release

#2925 Default version number for unversioned TimeSeries
  time-series/time-series-api/src/main/java/com/powsybl/timeseries/TimeSeries.java
  time-series/time-series-api/src/main/java/com/powsybl/timeseries/TimeSeriesCsvConfig.java
  time-series/time-series-api/src/main/java/com/powsybl/timeseries/TimeSeriesVersions.java
  time-series/time-series-api/src/test/java/com/powsybl/timeseries/TimeSeriesTableTest.java
  time-series/time-series-api/src/test/java/com/powsybl/timeseries/TimeSeriesTest.java
  time-series/time-series-api/src/test/java/com/powsybl/timeseries/TimeSeriesVersionsTest.java
  time-series/time-series-api/src/test/resources/timeseries.csv
Labels: Breaking Change, PR: ready-to-be-merged, Time series, March release

#2956 Fix reference terminal extension managing cloned variants
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ReferenceTerminalsImpl.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractReferenceTerminalsTest.java
Labels: bug, extensions, March release

#2957 Expose ReportNode severity key
  commons/src/main/java/com/powsybl/commons/report/ReportConstants.java
  commons/src/main/java/com/powsybl/commons/report/ReportNodeAdderOrBuilder.java
Labels: bug, March release

#2958 Add getters to ReportNode API
  commons/src/main/java/com/powsybl/commons/report/ReportNode.java
  commons/src/main/java/com/powsybl/commons/report/ReportNodeImpl.java
  commons/src/main/java/com/powsybl/commons/report/ReportNodeNoOp.java
  commons/src/test/java/com/powsybl/commons/report/NoOpTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/RemoveFeederBayTest.java
Labels: March release

#2944 CGMES: Fix support for ACLineSegments contained in cim:Line containers
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/NodeConversion.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/LineContainersTest.java
  cgmes/cgmes-conversion/src/test/resources/issues/line_container_3acls_EQ.xml
Labels: March release

#2960 Fix flows, voltage and angle at Boundary if generation present
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/DanglingLineBoundaryImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/util/SVTest.java
  iidm/iidm-serde/src/test/resources/V1_10/danglingLineWithGeneration.xml
  iidm/iidm-serde/src/test/resources/V1_11/danglingLineWithGeneration.xml
  iidm/iidm-serde/src/test/resources/V1_12/danglingLineWithGeneration.xml
  iidm/iidm-serde/src/test/resources/V1_3/danglingLineWithGeneration.xml
  iidm/iidm-serde/src/test/resources/V1_4/danglingLineWithGeneration.xml
  iidm/iidm-serde/src/test/resources/V1_5/danglingLineWithGeneration.xml
  iidm/iidm-serde/src/test/resources/V1_6/danglingLineWithGeneration.xml
  iidm/iidm-serde/src/test/resources/V1_7/danglingLineWithGeneration.xml
  iidm/iidm-serde/src/test/resources/V1_8/danglingLineWithGeneration.xml
  iidm/iidm-serde/src/test/resources/V1_9/danglingLineWithGeneration.xml
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/DanglingLineNetworkFactory.java
  matpower/matpower-converter/src/test/resources/dangling-line-generation.json
Labels: March release
