Repository powsybl/powsybl-core, pull requests merged in 2024-05, with the labels that each got.

#2996 CGMES export fix: modelling authority must be preserved
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/LegacyCommonGridModelExportTest.java
Labels: bug, CGMES, PR: next-release

#2992 Fix CGMES GL import
  cgmes/cgmes-gl/pom.xml
  cgmes/cgmes-gl/src/main/java/com/powsybl/cgmes/gl/CgmesGLExporter.java
  cgmes/cgmes-gl/src/main/java/com/powsybl/cgmes/gl/CgmesGLUtils.java
  cgmes/cgmes-gl/src/main/java/com/powsybl/cgmes/gl/LinePositionImporter.java
  cgmes/cgmes-gl/src/main/java/com/powsybl/cgmes/gl/SubstationPositionImporter.java
  cgmes/cgmes-gl/src/main/resources/CGMES-GL.sparql
  cgmes/cgmes-gl/src/test/java/com/powsybl/cgmes/gl/AbstractCgmesGLTest.java
  cgmes/cgmes-gl/src/test/java/com/powsybl/cgmes/gl/CgmesGLExporterTest.java
  cgmes/cgmes-gl/src/test/java/com/powsybl/cgmes/gl/CgmesGLImportPostProcessorTest.java
  cgmes/cgmes-gl/src/test/java/com/powsybl/cgmes/gl/CgmesGLImporterTest.java
  cgmes/cgmes-gl/src/test/java/com/powsybl/cgmes/gl/CgmesGLModelTest.java
  cgmes/cgmes-gl/src/test/java/com/powsybl/cgmes/gl/GLTestUtils.java
  cgmes/cgmes-gl/src/test/resources/importGL_EQ.xml
  cgmes/cgmes-gl/src/test/resources/importGL_GL.xml
  cgmes/cgmes-gl/src/test/resources/unsupportedLineCrs_GL.xml
  cgmes/cgmes-gl/src/test/resources/unsupportedSubstationCrs_GL.xml
Labels: PR: next-release

#2835 Proposition to create a complex matrix class
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/util/FortescueUtil.java
  math/pom.xml
  math/src/main/java/com/powsybl/math/matrix/ComplexMatrix.java
  math/src/test/java/com/powsybl/math/matrix/ComplexMatrixTest.java
Labels: June release

#3009 Fix SlackTerminal.isEmpty misuses
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/SlackTerminal.java
Labels: bug

#3008 Move Ref interface and implementations to powsybl-commons
  commons/src/main/java/com/powsybl/commons/ref/Ref.java
  commons/src/main/java/com/powsybl/commons/ref/RefChain.java
  commons/src/main/java/com/powsybl/commons/ref/RefObj.java
  commons/src/test/java/com/powsybl/commons/ref/RefTest.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractAutomationSystem.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractConnectable.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractConnectableBranch.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractHvdcConverterStation.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractIdentifiableAdder.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractInjectionAdder.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractTapChanger.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractTerminal.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractVoltageLevel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BatteryImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusBreakerVoltageLevel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusTerminal.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusbarSectionImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ConfiguredBusImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ConnectedComponentImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/DanglingLineImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/GeneratorImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/GroundImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/HvdcLineAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/HvdcLineImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/LccConverterStationImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/LineAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/LineImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/LoadImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkExt.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeTerminal.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ShuntCompensatorImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/StaticVarCompensatorImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SubnetworkImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SubstationAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SubstationImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SynchronousComponentImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TerminalBuilder.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ThreeWindingsTransformerImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TieLineAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TieLineImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TwoWindingsTransformerImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VariantArray.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VoltageAngleLimitAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VoltageAngleLimitImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VoltageLevelAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VoltageLevelExt.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VscConverterStationImpl.java
Labels: Breaking Change

#3006 CGMES export equipment fix: equivalent injection base voltage reference
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/EquipmentExportTest.java
Labels: bug, CGMES, PR: ready-to-be-merged, June release

#3007 ReportNode::include: fix missing ReportNode
  commons/src/main/java/com/powsybl/commons/report/ReportNodeImpl.java
  commons/src/test/java/com/powsybl/commons/report/ReportNodeTest.java
  commons/src/test/resources/testIncludeReportNode.json
Labels: bug

#3025 TCK: Set public access to test methods
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractConnectionNotificationTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractGroundTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractTckSuiteExhaustivityTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractReferencePrioritiesTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractReferenceTerminalsTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractSecondaryVoltageControlTest.java
Labels: bug

#3020 Remove order constraint for streams in tck
  iidm/iidm-impl/pom.xml
  iidm/iidm-tck/pom.xml
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNetworkTest.java
Labels: Breaking Change

#3027 Add slack bus mismatch: slack terminal can be disconnected
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/StateVariablesExportTest.java
Labels: PR: ready-to-be-merged, June release

#3029 CGMES export retained switch with same TN at both ends as non-retained
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/issues/RetainedSwitchExportTest.java
Labels: CGMES, PR: ready-to-be-merged, June release

#3017 Security analysis runner parameters
  contingency/contingency-api/src/main/java/com/powsybl/contingency/ContingencyContext.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/ContingencyContextType.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/SecurityAnalysis.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/SecurityAnalysisProvider.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/SecurityAnalysisRunParameters.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/execution/SecurityAnalysisExecutionImpl.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/monitor/StateMonitor.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/results/BranchResult.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/results/BusResult.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/results/ThreeWindingsTransformerResult.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/execution/SecurityAnalysisExecutionBuilderTest.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/execution/SecurityAnalysisExecutionImplTest.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/json/SecurityAnalysisProviderMock.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/tools/SecurityAnalysisToolTest.java
  security-analysis/security-analysis-default/src/main/java/com/powsybl/security/impl/DefaultSecurityAnalysisProvider.java
  security-analysis/security-analysis-default/src/test/java/com/powsybl/security/impl/SecurityAnalysisProviderTest.java
  security-analysis/security-analysis-default/src/test/java/com/powsybl/security/impl/SecurityAnalysisTest.java
Labels: Breaking Change, June release

#3021 IIDM Validation Util rework
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ValidationUtil.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractHvdcConverterStation.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractHvdcConverterStationAdder.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractLoadingLimits.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractLoadingLimitsAdder.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractTapChanger.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractTapChangerAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BatteryAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BatteryImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/DanglingLineAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/DanglingLineImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/GenerationAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/GeneratorAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/GeneratorImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/HvdcLineAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/HvdcLineImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/LoadAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/LoadImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/PhaseTapChangerAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/PhaseTapChangerImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/RatioTapChangerAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/RatioTapChangerImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ShuntCompensatorAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ShuntCompensatorImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ShuntCompensatorLinearModelImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/StaticVarCompensatorAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/StaticVarCompensatorImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VscConverterStationAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VscConverterStationImpl.java
Labels: Breaking Change, June release

#2983 Add documentation
  docs/.readthedocs.yaml
  docs/Makefile
  docs/README.md
  docs/_static/favicon.ico
  docs/_static/logos/logo_lfe_powsybl.svg
  docs/conf.py
  docs/grid_exchange_formats/ampl/ampl.md
  docs/grid_exchange_formats/cgmes/examples.md
  docs/grid_exchange_formats/cgmes/export.md
  docs/grid_exchange_formats/cgmes/format_specification.md
  docs/grid_exchange_formats/cgmes/import.md
  docs/grid_exchange_formats/cgmes/index.md
  docs/grid_exchange_formats/cgmes/post_processor.md
  docs/grid_exchange_formats/cgmes/triple_store.md
  docs/grid_exchange_formats/ieee/ieee.md
  docs/grid_exchange_formats/index.md
  docs/grid_exchange_formats/matpower/matpower.md
  docs/grid_exchange_formats/psse/psse.md
  docs/grid_exchange_formats/ucte/ucte.md
  docs/grid_exchange_formats/xiidm/xiidm.md
  docs/index.md
  docs/make.bat
  docs/requirements.txt
  docs/simulation/index.md
  docs/simulation/loadflow/loadflow.md
  docs/simulation/security/security.md
  docs/simulation/sensitivity/sensitivity.md
  docs/simulation/shortcircuit/index.md
  docs/simulation/shortcircuit/inputs.md
  docs/simulation/shortcircuit/outputs.md
  docs/simulation/shortcircuit/parameters.md
Labels: Documentation

#3016 IIDM ThreeWindingsTransformer RatedU0 modification
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ThreeWindingsTransformer.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ThreeWindingsTransformerImpl.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/ThreeWindingsTransformerModification.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/TestThreeWindingsTransformerModification.java
Labels: PR: ready-to-be-merged, June release

#3013 Modify AMPL export per unitage of lines with different nominal voltage at ends
  ampl-converter/src/main/java/com/powsybl/ampl/converter/version/BasicAmplExporter.java
  ampl-converter/src/test/java/com/powsybl/ampl/converter/AmplNetworkWriterTest.java
  ampl-converter/src/test/resources/inputs/line-with-different-nominal-voltage-at-ends-test-case.txt
  ampl-converter/src/test/resources/inputs/zero-impedance-line-with-different-nominal-voltage-at-ends-test-case.txt
Labels: PR: ready-to-be-merged, June release

#3031 Add network modification to hvdc line action
  action-api/src/main/java/com/powsybl/action/HvdcAction.java
  action-api/src/test/java/com/powsybl/action/ApplyActionToNetworkTest.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/HvdcLineModification.java
Labels: PR: ready-to-be-merged, June release

#3037 Fix: the fictitious load SvInjection should refer to TopologicalNode UUID
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/StateVariablesExportTest.java
Labels: bug

#3011 ReportNode V2.1
  commons/src/main/java/com/powsybl/commons/report/AbstractReportNodeAdderOrBuilder.java
  commons/src/main/java/com/powsybl/commons/report/ReportConstants.java
  commons/src/main/java/com/powsybl/commons/report/ReportNodeAdderOrBuilder.java
  commons/src/main/java/com/powsybl/commons/report/ReportNodeBuilder.java
  commons/src/main/java/com/powsybl/commons/report/ReportNodeDeserializer.java
  commons/src/main/java/com/powsybl/commons/report/ReportNodeImpl.java
  commons/src/main/java/com/powsybl/commons/report/ReportNodeJsonModule.java
  commons/src/main/java/com/powsybl/commons/report/ReportNodeRootBuilderImpl.java
  commons/src/main/java/com/powsybl/commons/report/ReportNodeSerializer.java
  commons/src/main/java/com/powsybl/commons/report/ReportNodeVersion.java
  commons/src/main/java/com/powsybl/commons/report/RootContext.java
  commons/src/main/java/com/powsybl/commons/report/TypedValue.java
  commons/src/test/java/com/powsybl/commons/report/ReportNodeTest.java
  commons/src/test/java/com/powsybl/commons/report/TypedValueTest.java
  commons/src/test/resources/testDictionaryEnd.json
  commons/src/test/resources/testIncludeReportNode.json
  commons/src/test/resources/testValuesReportNode.json
  iidm/iidm-api/src/test/resources/postProcessorReportNodeTest.json
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/RemoveFeederBayTest.java
  ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/UcteImporterReportNodeTest.java
  ucte/ucte-converter/src/test/resources/frVoltageRegulatingXnodeReport.json
  ucte/ucte-converter/src/test/resources/parallelUcteImportReport.json
Labels: Breaking Change, June release

#3039 CGMES SvInjection for slack unit test: referred topological node must be defined
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/StateVariablesExportTest.java
Labels: CGMES

#3034 Doc: grid formats + itools convert-network
  .gitignore
  docs/grid_exchange_formats/ampl/ampl.md
  docs/grid_exchange_formats/ampl/example.md
  docs/grid_exchange_formats/ampl/export.md
  docs/grid_exchange_formats/ampl/import.md
  docs/grid_exchange_formats/ampl/index.md
  docs/grid_exchange_formats/ieee/ieee.md
  docs/grid_exchange_formats/index.md
  docs/grid_exchange_formats/matpower/export.md
  docs/grid_exchange_formats/matpower/import.md
  docs/grid_exchange_formats/matpower/index.md
  docs/grid_exchange_formats/matpower/matpower.md
  docs/grid_exchange_formats/psse/examples.md
  docs/grid_exchange_formats/psse/export.md
  docs/grid_exchange_formats/psse/img/three-windings-transformer-model.svg
  docs/grid_exchange_formats/psse/img/two-windings-transformer-model.svg
  docs/grid_exchange_formats/psse/import.md
  docs/grid_exchange_formats/psse/index.md
  docs/grid_exchange_formats/psse/psse.md
  docs/grid_exchange_formats/ucte/export.md
  docs/grid_exchange_formats/ucte/format_specification.md
  docs/grid_exchange_formats/ucte/import.md
  docs/grid_exchange_formats/ucte/index.md
  docs/grid_exchange_formats/ucte/ucte.md
  docs/grid_features/import_post_processor.md
  docs/grid_features/index.md
  docs/index.md
  docs/simulation/shortcircuit/parameters.md
  docs/user/index.md
  docs/user/itools/convert_network.md
  docs/user/itools/index.md
Labels: Documentation

#3041 Doc: iidm
  docs/grid_exchange_formats/cgmes/export.md
  docs/grid_exchange_formats/cgmes/import.md
  docs/grid_exchange_formats/iidm/export.md
  docs/grid_exchange_formats/iidm/import.md
  docs/grid_exchange_formats/iidm/index.md
  docs/grid_exchange_formats/index.md
  docs/grid_exchange_formats/ucte/import.md
  docs/grid_exchange_formats/xiidm/xiidm.md
  docs/grid_features/import_post_processor.md
  docs/grid_model/additional.md
  docs/grid_model/extensions.md
  docs/grid_model/going_further.md
  docs/grid_model/img/currentLimits.svg
  docs/grid_model/img/danglingLine.svg
  docs/grid_model/img/generator-sign-convention.svg
  docs/grid_model/img/line-model.svg
  docs/grid_model/img/three-windings-transformer-model.svg
  docs/grid_model/img/two-windings-transformer-model.svg
  docs/grid_model/img/voltage-level.svg
  docs/grid_model/index.md
  docs/grid_model/network_subnetwork.md
  docs/index.md
  docs/simulation/shortcircuit/parameters.md
Labels: Documentation

#2998 Add an IIDM import post-processor to fill geographical extensions from ODRE data
  distribution-core/pom.xml
  docs/grid_features/import_post_processor.md
  docs/grid_model/extensions.md
  iidm/iidm-geodata/pom.xml
  iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/elements/GeoShape.java
  iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/elements/LineGeoData.java
  iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/elements/SubstationGeoData.java
  iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/odre/FileValidator.java
  iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/odre/GeographicDataParser.java
  iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/odre/OdreGeoDataAdder.java
  iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/odre/OdreGeoDataAdderPostProcessor.java
  iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/odre/OdreGeoDataCsvLoader.java
  iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/utils/DistanceCalculator.java
  iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/utils/GeoShapeDeserializer.java
  iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/utils/InputUtils.java
  iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/utils/LineGraph.java
  iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/utils/NetworkGeoDataExtensionsAdder.java
  iidm/iidm-geodata/src/test/java/com/powsybl/iidm/geodata/elements/LineGeoDataTest.java
  iidm/iidm-geodata/src/test/java/com/powsybl/iidm/geodata/elements/SubstationGeoDataTest.java
  iidm/iidm-geodata/src/test/java/com/powsybl/iidm/geodata/odre/FileValidatorTest.java
  iidm/iidm-geodata/src/test/java/com/powsybl/iidm/geodata/odre/OdreGeoDataAdderPostProcessorTest.java
  iidm/iidm-geodata/src/test/java/com/powsybl/iidm/geodata/odre/OdreGeoDataAdderTest.java
  iidm/iidm-geodata/src/test/java/com/powsybl/iidm/geodata/odre/OdreGeoDataCsvLoaderTest.java
  iidm/iidm-geodata/src/test/java/com/powsybl/iidm/geodata/utils/DistanceCalculatorTest.java
  iidm/iidm-geodata/src/test/java/com/powsybl/iidm/geodata/utils/NetworkGeoDataExtensionsAdderTest.java
  iidm/iidm-geodata/src/test/resources/eurostag-test/aerial-lines.csv
  iidm/iidm-geodata/src/test/resources/eurostag-test/substations-error.csv
  iidm/iidm-geodata/src/test/resources/eurostag-test/substations.csv
  iidm/iidm-geodata/src/test/resources/eurostag-test/underground-lines.csv
  iidm/iidm-geodata/src/test/resources/valid-line-name/aerial-lines.csv
  iidm/iidm-geodata/src/test/resources/valid-line-name/substations.csv
  iidm/iidm-geodata/src/test/resources/valid-line-name/underground-lines.csv
  iidm/pom.xml
  pom.xml
Labels: June release

#3042 Update math native library to 1.3.1
  pom.xml
Labels: PR: ready-to-be-merged, June release

#3043 Remove name unicity constraint on temporary limits
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ValidationUtil.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractCurrentLimitsTest.java
Labels: June release

#3040 Load default loadflow parameters from json file in classpath
  loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/AbstractLoadFlowDefaultParametersLoader.java
  loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowDefaultParametersLoader.java
  loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java
  loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowDefaultParametersLoaderMock.java
  loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowDefaultParametersLoaderTest.java
  loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/json/JsonLoadFlowParametersTest.java
Labels: June release
