Repository powsybl/powsybl-core, pull requests merged in 2024-09, with the labels that each got.

#3136 Create directory for resources in TestPlatformConfigProvider
  config-test/src/main/java/com/powsybl/config/test/TestPlatformConfigProvider.java
  config-test/src/test/java/com/powsybl/config/test/TestPlatformConfigProviderTest.java
  config-test/src/test/resources/com/powsybl/config/test/filelist.txt
  config-test/src/test/resources/com/powsybl/config/test/subfolder/subfolder_file.txt
Labels: bug

#3128 Fix CGM export dependencies issues
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CommonGridModelExportTest.java
  docs/grid_exchange_formats/cgmes/export.md
Labels: bug, CGMES

#3141 Fix CGMES importer documentation of parameter cgm-with-subnetworks-defined-by
  docs/grid_exchange_formats/cgmes/import.md
Labels: CGMES, Documentation

#3137 Datasource - part 7: fixes
  commons/src/main/java/com/powsybl/commons/datasource/DataSourceUtil.java
  commons/src/main/java/com/powsybl/commons/datasource/FileInformation.java
  commons/src/main/java/com/powsybl/commons/datasource/GenericReadOnlyDataSource.java
  commons/src/main/java/com/powsybl/commons/datasource/TarArchiveDataSource.java
  commons/src/main/java/com/powsybl/commons/datasource/ZipArchiveDataSource.java
  commons/src/test/java/com/powsybl/commons/datasource/DataSourceBuilderTest.java
  commons/src/test/java/com/powsybl/commons/datasource/DataSourceUtilTest.java
Labels: October 2024 release

#3129 [Documentation] Fix broken links
  README.md
  docs/conf.py
  docs/grid_exchange_formats/cgmes/import.md
  docs/grid_model/extensions.md
  docs/grid_model/network_subnetwork.md
  docs/index.md
  docs/simulation/dynamic/configuration.md
  docs/simulation/dynamic/index.md
  docs/simulation/dynamic_security/configuration.md
  docs/simulation/loadflow/configuration.md
  docs/simulation/loadflow/index.md
  docs/user/itools/index.md
Labels: PR: ready-to-be-merged, Documentation, October 2024 release

#3115 Flatten network
  docs/grid_features/index.md
  docs/grid_features/working_with_subnetworks.md
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Network.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractNetwork.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SubnetworkImpl.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractAreaTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractMergeNetworkTest.java
Labels: Breaking Change, PR: ready-to-be-merged, October 2024 release

#3147 CgmesImporter, allow importing with wrong dataextension when the mainfile doesn't exist
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesOnDataSource.java
  cgmes/cgmes-model/src/test/java/com/powsybl/cgmes/model/CgmesOnDataSourceTest.java
Labels: October 2024 release

#3131 Fix overload detection on reduced limits via LimitViolationUtils
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/LimitViolationUtils.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/LoadingLimitsUtil.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractLoadingLimitsAdder.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/limitreduction/result/AbstractReducedLoadingLimits.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/LimitViolationDetectionTest.java
Labels: October 2024 release

#3150 Add all parameters network read method from a data source
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Network.java
Labels: October 2024 release

#3151 Allow adding new post processors on an existing ImportConfig
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ImportConfig.java
  iidm/iidm-api/src/test/java/com/powsybl/iidm/network/ImportConfigTest.java
Labels: October 2024 release

#3080 ODRE import postprocessor fixes
  iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/elements/LineGeoData.java
  iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/elements/SubstationGeoData.java
  iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/odre/FileValidator.java
  iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/odre/GeographicDataParser.java
  iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/odre/OdreGeoDataAdder.java
  iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/odre/OdreGeoDataAdderPostProcessor.java
  iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/odre/OdreGeoDataCsvLoader.java
  iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/utils/DistanceCalculator.java
  iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/utils/InputUtils.java
  iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/utils/LineCoordinatesOrdering.java
  iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/utils/LineGraph.java
  iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/utils/NetworkGeoDataExtensionsAdder.java
  iidm/iidm-geodata/src/test/java/com/powsybl/iidm/geodata/elements/LineGeoDataTest.java
  iidm/iidm-geodata/src/test/java/com/powsybl/iidm/geodata/elements/SubstationGeoDataTest.java
  iidm/iidm-geodata/src/test/java/com/powsybl/iidm/geodata/odre/FileValidatorTest.java
  iidm/iidm-geodata/src/test/java/com/powsybl/iidm/geodata/odre/OdreGeoDataAdderTest.java
  iidm/iidm-geodata/src/test/java/com/powsybl/iidm/geodata/odre/OdreGeoDataCsvLoaderTest.java
  iidm/iidm-geodata/src/test/java/com/powsybl/iidm/geodata/utils/NetworkGeoDataExtensionsAdderTest.java
  iidm/iidm-geodata/src/test/resources/valid-line-name/aerial-lines.csv
  iidm/iidm-geodata/src/test/resources/valid-line-name/substations.csv
  iidm/iidm-geodata/src/test/resources/valid-line-name/underground-lines.csv
Labels: PR: ready-to-be-merged, October 2024 release

#2916 Allow task interruption in groovy scripts
  action-ial/action-ial-dsl/src/main/groovy/com/powsybl/action/ial/dsl/ActionDslLoader.groovy
  action-ial/action-ial-dsl/src/main/groovy/com/powsybl/action/ial/dsl/ConditionDslLoader.groovy
  computation/pom.xml
  computation/src/test/java/com/powsybl/computation/AbstractTaskInterruptionTest.java
  contingency/contingency-dsl/pom.xml
  contingency/contingency-dsl/src/main/groovy/com/powsybl/contingency/dsl/ContingencyDslLoader.groovy
  contingency/contingency-dsl/src/test/java/com/powsybl/contingency/dsl/GroovyContingencyListTest.java
  dsl/src/main/groovy/com/powsybl/dsl/DslLoader.groovy
  dsl/src/main/groovy/com/powsybl/dsl/ExpressionDslLoader.groovy
  iidm/iidm-scripting/pom.xml
  iidm/iidm-scripting/src/main/java/com/powsybl/iidm/network/scripting/GroovyScriptPostProcessor.java
  iidm/iidm-scripting/src/test/java/com/powsybl/iidm/network/scripting/GroovyScriptPostProcessorTest.java
  scripting-test/src/main/java/com/powsybl/scripting/test/AbstractGroovyScriptTest.java
  scripting/pom.xml
  scripting/src/main/groovy/com/powsybl/scripting/groovy/GroovyScripts.groovy
  scripting/src/test/java/com/powsybl/scripting/InterruptScriptsTest.java
  scripting/src/test/java/com/powsybl/scripting/RunScriptToolTest.java
  scripting/src/test/resources/junit-platform.properties
  time-series/time-series-dsl/pom.xml
  time-series/time-series-dsl/src/main/groovy/com/powsybl/timeseries/dsl/CalculatedTimeSeriesGroovyDslLoader.groovy
  time-series/time-series-dsl/src/test/java/com/powsybl/timeseries/dsl/CalculatedTimeSeriesGroovyDslInterruptionsTest.java
Labels: PR: waiting-for-review, Groovy, October 2024 release

#3132 Add parameter in NetworkSerDe.copy to choose between formats (xml, binary, etc.)
  commons-test/src/main/java/com/powsybl/commons/test/ComparisonUtils.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/NetworkSerDe.java
  iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/NetworkSerDeTest.java
Labels: October 2024 release

#2604 AMPL export : extended exporter
  ampl-converter/pom.xml
  ampl-converter/src/main/java/com/powsybl/ampl/converter/AmplConstants.java
  ampl-converter/src/main/java/com/powsybl/ampl/converter/AmplNetworkWriter.java
  ampl-converter/src/main/java/com/powsybl/ampl/converter/util/NetworkUtil.java
  ampl-converter/src/main/java/com/powsybl/ampl/converter/version/AmplColumnsExporter.java
  ampl-converter/src/main/java/com/powsybl/ampl/converter/version/AmplExportVersion.java
  ampl-converter/src/main/java/com/powsybl/ampl/converter/version/BasicAmplExporter.java
  ampl-converter/src/main/java/com/powsybl/ampl/converter/version/ExtendedAmplExporter.java
  ampl-converter/src/test/java/com/powsybl/ampl/converter/AmplNetworkWriterTest.java
  ampl-converter/src/test/java/com/powsybl/ampl/converter/ExtendedAmplExporterTest.java
  ampl-converter/src/test/resources/inputs/extended_exporter/dangling-line-buses.txt
  ampl-converter/src/test/resources/inputs/extended_exporter/eurostag-tutorial-example1-buses-tl.txt
  ampl-converter/src/test/resources/inputs/extended_exporter/eurostag-tutorial-example1-buses.txt
  ampl-converter/src/test/resources/inputs/extended_exporter/eurostag-tutorial-example1-generators-regulating-bus.txt
  ampl-converter/src/test/resources/inputs/extended_exporter/eurostag-tutorial-example1-tct.txt
  ampl-converter/src/test/resources/inputs/extended_exporter/headers.txt
  ampl-converter/src/test/resources/inputs/extended_exporter/svc-test-case-regulating-bus.txt
  ampl-converter/src/test/resources/inputs/extended_exporter/three-windings-transformers-buses.txt
  ampl-converter/src/test/resources/inputs/extended_exporter/three-windings-transformers-tct.txt
  commons/src/main/java/com/powsybl/commons/io/table/TableFormatterHelper.java
  docs/grid_exchange_formats/ampl/export.md
Labels: October 2024 release

#3154 Fix DanglingLine ID in Eurostag example network with tie-lines
  ampl-converter/src/test/resources/inputs/eurostag-tutorial-example1-branches-tl.txt
  cgmes/cgmes-extensions/src/test/resources/eurostag_cgmes_dangling_line_boundary_node.xml
  cgmes/cgmes-extensions/src/test/resources/eurostag_cgmes_line_boundary_node.xml
  iidm/iidm-modification/src/test/resources/eurostag-replace-tl.xml
  iidm/iidm-reducer/src/test/java/com/powsybl/iidm/reducer/TieLineReductionTest.java
  iidm/iidm-serde/src/test/resources/V1_11/tieLineTerminalRefBug.xml
  iidm/iidm-serde/src/test/resources/V1_12/tieLineTerminalRefBug.xml
  iidm/iidm-serde/src/test/resources/V1_13/tieLineTerminalRefBug.xml
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractAreaTest.java
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/EurostagTutorialExample1Factory.java
Labels: Quality

#3144 Refactor AbstractToolTest::assertCommand for regex
  tools-test/src/main/java/com/powsybl/tools/test/AbstractToolTest.java
  tools-test/src/test/java/com/powsybl/tools/test/CommandLineToolsTest.java
Labels: Breaking Change, October 2024 release

#3155 Fix ReportNode deserialization by enriching ReportNode API with TreeContext
  commons/src/main/java/com/powsybl/commons/report/ReportNode.java
  commons/src/main/java/com/powsybl/commons/report/ReportNodeDeserializer.java
  commons/src/main/java/com/powsybl/commons/report/ReportNodeImpl.java
  commons/src/main/java/com/powsybl/commons/report/ReportNodeJsonModule.java
  commons/src/main/java/com/powsybl/commons/report/ReportNodeNoOp.java
  commons/src/main/java/com/powsybl/commons/report/ReportNodeSerializer.java
  commons/src/main/java/com/powsybl/commons/report/TreeContext.java
  commons/src/main/java/com/powsybl/commons/report/TreeContextImpl.java
  commons/src/main/java/com/powsybl/commons/report/TypedValue.java
  commons/src/test/java/com/powsybl/commons/report/ReportNodeTest.java
  ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/UcteImporterReportNodeTest.java
Labels: Breaking Change, October 2024 release

#3142 Dynamic simulation final state value
  docs/grid_exchange_formats/cgmes/export.md
  docs/simulation/dynamic/index.md
  docs/user/itools/dynamic-simulation.md
  dynamic-simulation/dynamic-simulation-api/src/main/java/com/powsybl/dynamicsimulation/DynamicSimulation.java
  dynamic-simulation/dynamic-simulation-api/src/main/java/com/powsybl/dynamicsimulation/DynamicSimulationProvider.java
  dynamic-simulation/dynamic-simulation-api/src/main/java/com/powsybl/dynamicsimulation/DynamicSimulationResult.java
  dynamic-simulation/dynamic-simulation-api/src/main/java/com/powsybl/dynamicsimulation/DynamicSimulationResultImpl.java
  dynamic-simulation/dynamic-simulation-api/src/main/java/com/powsybl/dynamicsimulation/OutputVariable.java
  dynamic-simulation/dynamic-simulation-api/src/main/java/com/powsybl/dynamicsimulation/OutputVariablesSupplier.java
  dynamic-simulation/dynamic-simulation-api/src/main/java/com/powsybl/dynamicsimulation/json/DynamicSimulationResultDeserializer.java
  dynamic-simulation/dynamic-simulation-api/src/main/java/com/powsybl/dynamicsimulation/json/DynamicSimulationResultSerializer.java
  dynamic-simulation/dynamic-simulation-api/src/test/java/com/powsybl/dynamicsimulation/AnotherDynamicSimulationProviderMock.java
  dynamic-simulation/dynamic-simulation-api/src/test/java/com/powsybl/dynamicsimulation/DynamicSimulationProviderMock.java
  dynamic-simulation/dynamic-simulation-api/src/test/java/com/powsybl/dynamicsimulation/DynamicSimulationTest.java
  dynamic-simulation/dynamic-simulation-api/src/test/java/com/powsybl/dynamicsimulation/json/DynamicSimulationResultJsonTest.java
  dynamic-simulation/dynamic-simulation-api/src/test/resources/DynamicSimulationFailedResult.json
  dynamic-simulation/dynamic-simulation-api/src/test/resources/DynamicSimulationResult.json
  dynamic-simulation/dynamic-simulation-dsl/pom.xml
  dynamic-simulation/dynamic-simulation-dsl/src/main/java/com/powsybl/dynamicsimulation/groovy/AbstractGroovySupplier.java
  dynamic-simulation/dynamic-simulation-dsl/src/main/java/com/powsybl/dynamicsimulation/groovy/DynamicSimulationSupplierFactory.java
  dynamic-simulation/dynamic-simulation-dsl/src/main/java/com/powsybl/dynamicsimulation/groovy/GroovyCurvesSupplier.java
  dynamic-simulation/dynamic-simulation-dsl/src/main/java/com/powsybl/dynamicsimulation/groovy/GroovyDynamicModelsSupplier.java
  dynamic-simulation/dynamic-simulation-dsl/src/main/java/com/powsybl/dynamicsimulation/groovy/GroovyEventModelsSupplier.java
  dynamic-simulation/dynamic-simulation-dsl/src/main/java/com/powsybl/dynamicsimulation/groovy/GroovyOutputVariablesSupplier.java
  dynamic-simulation/dynamic-simulation-dsl/src/main/java/com/powsybl/dynamicsimulation/groovy/OutputVariableGroovyExtension.java
  dynamic-simulation/dynamic-simulation-dsl/src/test/groovy/com/powsybl/dynamicsimulation/groovy/DummyCurveGroovyExtension.groovy
  dynamic-simulation/dynamic-simulation-dsl/src/test/groovy/com/powsybl/dynamicsimulation/groovy/DummyOutputVariableGroovyExtension.groovy
  dynamic-simulation/dynamic-simulation-dsl/src/test/java/com/powsybl/dynamicsimulation/groovy/DummyOutputVariable.java
  dynamic-simulation/dynamic-simulation-dsl/src/test/java/com/powsybl/dynamicsimulation/groovy/GroovyCurvesSupplierTest.java
  dynamic-simulation/dynamic-simulation-dsl/src/test/java/com/powsybl/dynamicsimulation/groovy/GroovyOutputVariablesSupplierTest.java
  dynamic-simulation/dynamic-simulation-dsl/src/test/resources/outputVariables.groovy
  dynamic-simulation/dynamic-simulation-tool/src/main/java/com/powsybl/dynamicsimulation/tool/DynamicSimulationTool.java
  dynamic-simulation/dynamic-simulation-tool/src/test/java/com/powsybl/dynamicsimulation/tool/DynamicSimulationProviderMock.java
  dynamic-simulation/dynamic-simulation-tool/src/test/java/com/powsybl/dynamicsimulation/tool/DynamicSimulationToolTest.java
Labels: Breaking Change, October 2024 release

#3159 [CGMES GL] Add SubstationPosition extension when location on voltage levels
  cgmes/cgmes-gl/src/main/java/com/powsybl/cgmes/gl/CgmesGLImporter.java
  cgmes/cgmes-gl/src/main/java/com/powsybl/cgmes/gl/CgmesGLModel.java
  cgmes/cgmes-gl/src/main/java/com/powsybl/cgmes/gl/LinePositionImporter.java
  cgmes/cgmes-gl/src/main/java/com/powsybl/cgmes/gl/SubstationPositionImporter.java
  cgmes/cgmes-gl/src/main/resources/CGMES-GL.sparql
  cgmes/cgmes-gl/src/test/java/com/powsybl/cgmes/gl/CgmesGLImportPostProcessorTest.java
  cgmes/cgmes-gl/src/test/resources/importGL_EQ.xml
  cgmes/cgmes-gl/src/test/resources/importGL_GL.xml
Labels: PR: ready-to-be-merged, October 2024 release

#3161 CGMES functional logs (first steps)
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesReports.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Context.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/SubstationIdMapping.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/BusbarSectionConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EnergyConsumerConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EquivalentBranchConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EquivalentShuntConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ExternalNetworkInjectionConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/GroundConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/OperationalLimitConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ShuntConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/StaticVarCompensatorConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SubstationConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SwitchConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SynchronousMachineConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/VoltageLevelConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/hvdc/AcDcConverterConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/hvdc/DcLineSegmentConversion.java
  cgmes/cgmes-conversion/src/test/resources/functional-logs/microGridBaseCaseBE-invalid-voltage-bus.txt
  cgmes/cgmes-conversion/src/test/resources/functional-logs/microGridBaseCaseBE-target-deadband.txt
  cgmes/cgmes-conversion/src/test/resources/functional-logs/microGridBaseCaseBE.txt
  cgmes/cgmes-conversion/src/test/resources/functional-logs/miniGridNodeBreaker.txt
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesModel.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesNames.java
Labels: October 2024 release

#3133 Synchronize parameter retrieval methods with PlatformConfig overrides
  ampl-converter/src/main/java/com/powsybl/ampl/converter/AmplExporter.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java
  commons/src/main/java/com/powsybl/commons/parameters/ConfiguredParameter.java
  commons/src/main/java/com/powsybl/commons/parameters/Parameter.java
  commons/src/test/java/com/powsybl/commons/parameters/ConfiguredParameterTest.java
  ieee-cdf/ieee-cdf-converter/src/main/java/com/powsybl/ieeecdf/converter/IeeeCdfImporter.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/AbstractTreeDataExporter.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/AbstractTreeDataImporter.java
  loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowProvider.java
  loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowProviderMock.java
  loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowProviderTest.java
  matpower/matpower-converter/src/main/java/com/powsybl/matpower/converter/MatpowerExporter.java
  matpower/matpower-converter/src/main/java/com/powsybl/matpower/converter/MatpowerImporter.java
  psse/psse-converter/src/main/java/com/powsybl/psse/converter/PsseExporter.java
  psse/psse-converter/src/main/java/com/powsybl/psse/converter/PsseImporter.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/ShortCircuitAnalysisProvider.java
  shortcircuit-api/src/test/java/com/powsybl/shortcircuit/ShortCircuitAnalysisMock.java
  shortcircuit-api/src/test/java/com/powsybl/shortcircuit/ShortCircuitAnalysisProviderTest.java
  ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteExporter.java
  ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteImporter.java
Labels: October 2024 release

#3138 [CGMES export] Export boundary TopologicalNodes in the TopologicalIsland
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/StateVariablesExportTest.java
Labels: CGMES, October 2024 release

#3139 Improve CGMES import and export of OperationalLimits
  cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MicroGrid/BaseCase/BC_BE_v2_limits/MicroGridTestConfiguration_BC_BE_EQ_V2.xml
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/LoadingLimitsMapping.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/OperationalLimitConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/OperationalLimitTypeEq.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/OperationalLimitsGroupTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/EquipmentExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/ExportXmlCompare.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/issues/ExportNumberMaxValueTest.java
  cgmes/cgmes-conversion/src/test/resources/OperationalLimits.xml
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesNames.java
  cgmes/cgmes-model/src/main/resources/CIM100.sparql
  cgmes/cgmes-model/src/main/resources/CIM14.sparql
  cgmes/cgmes-model/src/main/resources/CIM16.sparql
  docs/grid_exchange_formats/cgmes/export.md
  docs/grid_exchange_formats/cgmes/import.md
  docs/grid_model/additional.md
Labels: CGMES, October 2024 release
