Repository powsybl/powsybl-core, pull requests merged in 2024-12, with the labels that each got.

#3225 Store the CGMES id/name of OperationalLimitSet in a unique property
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/OperationalLimitConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/OperationalLimitsGroupTest.java
Labels: CGMES, December 2024 release

#3130 Create adders from existing objects: ReactiveCapabilityCurve, PhaseTapChanger, RatioTapChanger
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/PhaseTapChangerHolder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/RatioTapChangerHolder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ReactiveLimitsHolder.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/TapChangerHolderTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractReactiveCapabilityCurveTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractTapChangerHolderTest.java
Labels: December 2024 release

#3197 Bump powsybl-parent to v20
  pom.xml
Labels: December 2024 release

#3237 Fix typos in LoadFlowParameters yml parsing
  loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java
  loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowParametersTest.java
Labels: bug, December 2024 release

#3215 CGMES. Fix import of condensers
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SynchronousMachineConversion.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/CondenserImportExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/cim14/Cim14SmallCasesConversionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/modified/CgmesConformity1ModifiedConversionTest.java
  cgmes/cgmes-model-test/src/main/resources/cim14/condenser/condenser_EQ.xml
  cgmes/cgmes-model-test/src/main/resources/cim14/condenser/condenser_TP.xml
  cgmes/cgmes-model-test/src/test/java/com/powsybl/cgmes/model/test/cim14/Cim14SmallCasesTest.java
  cgmes/cgmes-model/src/main/resources/CIM14.sparql
Labels: bug, CGMES, December 2024 release

#3240 Remove link to https://www.itesla-project.eu/
  docs/grid_exchange_formats/iidm/index.md
Labels: IIDM, PR: ready-to-be-merged, Documentation, December 2024 release

#3220 Add version 1.2 of AMPL exporter
  ampl-converter/src/main/java/com/powsybl/ampl/converter/AmplConstants.java
  ampl-converter/src/main/java/com/powsybl/ampl/converter/version/AmplExportVersion.java
  ampl-converter/src/main/java/com/powsybl/ampl/converter/version/BasicAmplExporter.java
  ampl-converter/src/main/java/com/powsybl/ampl/converter/version/ExtendedAmplExporterV2.java
  ampl-converter/src/test/java/com/powsybl/ampl/converter/AbstractAmplExporterTest.java
  ampl-converter/src/test/java/com/powsybl/ampl/converter/AmplNetworkWriterTest.java
  ampl-converter/src/test/java/com/powsybl/ampl/converter/ExtendedAmplExporterTest.java
  ampl-converter/src/test/java/com/powsybl/ampl/converter/ExtendedAmplExporterV2Test.java
  ampl-converter/src/test/resources/inputs/extended_exporter_v2/battery-q0-unit-column.txt
  ampl-converter/src/test/resources/inputs/extended_exporter_v2/eurostag-tutorial-example1-generators-is-condenser.txt
  ampl-converter/src/test/resources/inputs/extended_exporter_v2/headers.txt
  ampl-converter/src/test/resources/inputs/extended_exporter_v2/hvdc-ac-emul-lcc-test-case.txt
  ampl-converter/src/test/resources/inputs/extended_exporter_v2/hvdc-ac-emul-vsc-test-case.txt
  ampl-converter/src/test/resources/inputs/extended_exporter_v2/hvdc-vsc-test-case.txt
  ampl-converter/src/test/resources/inputs/extended_exporter_v2/lcc-load-target-q-test-case.txt
  docs/grid_exchange_formats/ampl/export.md
Labels: Breaking Change, December 2024 release

#3199 Voltage level topology model conversion
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractConnectable.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractIidmExtension.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AreaBoundaryImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AreaImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusBreakerTopologyModel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusTerminal.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerTopologyModel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeTerminal.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/Referrer.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/RegulatingPoint.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VoltageLevelImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/RemoteReactivePowerControlImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/SlackTerminalImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/ConvertTopologyTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractConvertTopologyTest.java
Labels: December 2024 release

#3235 cim:Jumper support
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SwitchConversion.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/SwitchConversionTest.java
  cgmes/cgmes-conversion/src/test/resources/groundTest.xml
  cgmes/cgmes-conversion/src/test/resources/jumperTest.xml
  cgmes/cgmes-model/src/main/resources/CIM100.sparql
Labels: December 2024 release

#3243 Handle duplicate timeseries index
  time-series/time-series-api/src/main/java/com/powsybl/timeseries/IrregularTimeSeriesIndex.java
  time-series/time-series-api/src/main/java/com/powsybl/timeseries/TimeSeries.java
  time-series/time-series-api/src/test/java/com/powsybl/timeseries/IrregularTimeSeriesIndexTest.java
  time-series/time-series-api/src/test/java/com/powsybl/timeseries/TimeSeriesTest.java
Labels: December 2024 release

#3249 CGMES: fictitious voltage levels marked as fictitious
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/NodeContainerMappingTest.java
Labels: bug, December 2024 release

#3252 CGMES Import: allow voltage levels without names
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/NodeContainerMappingTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/cim14/Cim14SmallCasesConversionTest.java
  cgmes/cgmes-conversion/src/test/resources/cim14/vl_without_name.xml
  cgmes/cgmes-conversion/src/test/resources/issues/node-containers/vl_without_name.xml
  cgmes/cgmes-model/src/main/resources/CIM14.sparql
  cgmes/cgmes-model/src/main/resources/CIM16.sparql
Labels: bug, December 2024 release

#3206 More robust UCTE naming strategy
  ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/AbstractNamingStrategy.java
  ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/CounterNamingStrategy.java
  ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/DefaultNamingStrategy.java
  ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/NamingStrategy.java
  ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteExporter.java
  ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteImporter.java
  ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/util/UcteConverterConstants.java
  ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/CounterNamingStrategyTest.java
  ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/NamingStrategyTest.java
  ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/UcteImporterTest.java
  ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/util/UcteConverterHelperTest.java
  ucte/ucte-converter/src/test/resources/network.xiidm
  ucte/ucte-network/pom.xml
  ucte/ucte-network/src/main/java/com/powsybl/ucte/network/UcteCountryCode.java
  ucte/ucte-network/src/main/java/com/powsybl/ucte/network/UcteElementId.java
  ucte/ucte-network/src/main/java/com/powsybl/ucte/network/UcteVoltageLevelCode.java
  ucte/ucte-network/src/main/java/com/powsybl/ucte/network/util/UcteNetworkUtil.java
  ucte/ucte-network/src/test/java/com/powsybl/ucte/network/UcteVoltageLevelCodeTest.java
  ucte/ucte-network/src/test/java/com/powsybl/ucte/network/util/UcteNetworkUtilTest.java
Labels: Breaking Change, Release 03/2025

#3253 Enable documentation download in pdf format
  docs/.readthedocs.yaml
Labels: Release 03/2025
