Repository powsybl/powsybl-core, pull requests merged in 2024-06, with the labels that each got.

#3044 CGMES export: output max number values as float, not double
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/issues/ExportNumberMaxValueTest.java
Labels: bug, CGMES, June release

#2943 Remove violation detector from SecurityAnalysis API
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/LimitViolationDetection.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/Security.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/SecurityAnalysisInput.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/SecurityAnalysisRunParameters.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/detectors/AbstractContingencyBlindDetector.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/detectors/AbstractLimitViolationDetector.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/detectors/DefaultLimitViolationDetector.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/detectors/LimitViolationDetector.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/detectors/package-info.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/execution/SecurityAnalysisExecutionImpl.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/LimitViolationDetectionTest.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/SecurityAnalysisInputTest.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/detectors/AbstractLimitViolationDetectionTest.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/detectors/DefaultLimitViolationDetectorTest.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/detectors/LimitViolationDetectorForThreeWindingsTransformerTest.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/detectors/LimitViolationDetectorTest.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/execution/SecurityAnalysisExecutionImplTest.java
  security-analysis/security-analysis-default/src/main/java/com/powsybl/security/impl/DefaultSecurityAnalysis.java
  security-analysis/security-analysis-default/src/main/java/com/powsybl/security/impl/DefaultSecurityAnalysisProvider.java
  security-analysis/security-analysis-default/src/test/java/com/powsybl/security/impl/SecurityAnalysisTest.java
Labels: Breaking Change, June release

#3052 Add network extraction feature in documentation
  docs/grid_features/extraction.md
  docs/grid_features/index.md
Labels: PR: ready-to-be-merged, Documentation

#3053 Add examples for additional network models
  docs/grid_model/additional.md
  docs/grid_model/img/currentLimitsExample1.svg
  docs/grid_model/img/currentLimitsExample2.svg
  docs/grid_model/network_subnetwork.md
Labels: PR: ready-to-be-merged, Documentation

#3048 Boundary P, Q, angle and voltage with zero impedance
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/DanglingLineBoundaryImpl.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/DanglingLineData.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/TieLineUtil.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/TieLineTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/util/SVTest.java
Labels: bug, PR: ready-to-be-merged, June release

#3014 Three-windings transformer manipulation improvements
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ThreeWindingsTransformer.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ThreeWindingsTransformerToBeEstimatedAdder.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ThreeWindingsTransformerImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ThreeWindingsTransformerToBeEstimatedAdderImpl.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractThreeWindingsTransformerTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractThreeWindingsTransformerToBeEstimatedTest.java
Labels: Breaking Change, PR: ready-to-be-merged, June release

#3045 Documentation : load flow and load flow validation
  docs/README.md
  docs/grid_exchange_formats/ampl/export.md
  docs/grid_exchange_formats/cgmes/export.md
  docs/grid_exchange_formats/cgmes/import.md
  docs/grid_exchange_formats/iidm/export.md
  docs/grid_exchange_formats/iidm/import.md
  docs/grid_exchange_formats/iidm/index.md
  docs/grid_exchange_formats/index.md
  docs/grid_exchange_formats/psse/import.md
  docs/grid_exchange_formats/ucte/export.md
  docs/grid_features/extraction.md
  docs/grid_features/import_post_processor.md
  docs/grid_model/extensions.md
  docs/grid_model/network_subnetwork.md
  docs/simulation/index.md
  docs/simulation/loadflow/index.md
  docs/simulation/loadflow/loadflow.md
  docs/simulation/loadflow/loadflow_validation.md
  docs/user/configuration/import-export-parameters-default-value.md
  docs/user/configuration/index.md
  docs/user/configuration/load-flow-action-simulator.md
  docs/user/configuration/load-flow-based-phase-shifter-optimizer.md
  docs/user/configuration/load-flow.md
  docs/user/configuration/loadflow-results-completion-parameters.md
  docs/user/configuration/loadflow-validation.md
  docs/user/index.md
  docs/user/itools/convert_network.md
  docs/user/itools/loadflow-validation.md
  docs/user/itools/loadflow.md
Labels: Documentation

#3035 Doc: Index + Timeseries
  docs/README.md
  docs/_templates/page.html
  docs/_templates/sidebar/brand.html
  docs/conf.py
  docs/data/timeseries.md
  docs/index.md
  docs/requirements.txt
Labels: Documentation

#3047 Add security-analysis related pages to the documentation.
  docs/data/timeseries.md
  docs/grid_features/extraction.md
  docs/grid_features/import_post_processor.md
  docs/grid_features/index.md
  docs/grid_features/loadflow_validation.md
  docs/grid_model/extensions.md
  docs/index.md
  docs/simulation/dynamic/index.md
  docs/simulation/index.md
  docs/simulation/loadflow/configuration.md
  docs/simulation/loadflow/index.md
  docs/simulation/security/action-dsl.md
  docs/simulation/security/configuration.md
  docs/simulation/security/contingency-dsl.md
  docs/simulation/security/implementations.md
  docs/simulation/security/index.md
  docs/simulation/security/security.md
  docs/simulation/shortcircuit/inputs.md
  docs/user/configuration/componentDefaultConfig.md
  docs/user/configuration/external-security-analysis-config.md
  docs/user/configuration/groovy-dsl-contingencies.md
  docs/user/configuration/index.md
  docs/user/configuration/limit-violation-default-filter.md
  docs/user/configuration/loadflow-validation.md
  docs/user/configuration/security-analysis.md
  docs/user/itools/action-simulator.md
  docs/user/itools/cim-anonymizer.md
  docs/user/itools/compare-security-analysis-results.md
  docs/user/itools/dynamic-simulation.md
  docs/user/itools/index.md
  docs/user/itools/loadflow-validation.md
  docs/user/itools/loadflow.md
  docs/user/itools/run-script.md
  docs/user/itools/security-analysis.md
  docs/user/itools/sensitivity-computation.md
Labels: Documentation

#2994 Add side in FeederResult
  docs/simulation/shortcircuit/outputs.md
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/AbstractFeederResult.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/FeederResult.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/FortescueFeederResult.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/MagnitudeFeederResult.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/ShortCircuitAnalysisResult.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/json/FeederResultDeserializer.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/json/FeederResultSerializer.java
  shortcircuit-api/src/test/java/com/powsybl/shortcircuit/ShortCircuitAnalysisTest.java
  shortcircuit-api/src/test/java/com/powsybl/shortcircuit/TestingResultFactory.java
  shortcircuit-api/src/test/java/com/powsybl/shortcircuit/converter/ShortCircuitAnalysisResultExportersTest.java
  shortcircuit-api/src/test/resources/shortcircuit-failed-result.json
  shortcircuit-api/src/test/resources/shortcircuit-fortescue-results.json
  shortcircuit-api/src/test/resources/shortcircuit-magnitude-results.json
  shortcircuit-api/src/test/resources/shortcircuit-multiple-feeder-results.json
  shortcircuit-api/src/test/resources/shortcircuit-results-with-feeder-result.json
  shortcircuit-api/src/test/resources/shortcircuit-results-with-two-faults.json
  shortcircuit-api/src/test/resources/shortcircuit-with-extensions-results.json
Labels: Shortcircuits, June release

#3057 Allow OperatingStatus on busbar sections
  docs/grid_model/extensions.md
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/OperatingStatus.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractOperatingStatusTest.java
Labels: June release

#3051 CIM-anonymiser
  docs/user/itools/cim_anonymizer.md
  docs/user/itools/index.md
Labels: PR: ready-to-be-merged, Documentation

#3059 Additional info on network reducer
  docs/grid_features/extraction.md
Labels: Documentation

#3063 Add sensitivity analysis documentation
  docs/grid_model/additional.md
  docs/grid_model/extensions.md
  docs/grid_model/network_subnetwork.md
  docs/simulation/index.md
  docs/simulation/loadflow/configuration.md
  docs/simulation/security/configuration.md
  docs/simulation/security/contingency-dsl.md
  docs/simulation/sensitivity/configuration.md
  docs/simulation/sensitivity/index.md
  docs/simulation/sensitivity/sensitivity.md
Labels: Documentation

#3054 Add the ability to override minP and maxP to reflect generator temporary limits
  docs/grid_model/extensions.md
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ActivePowerControl.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ActivePowerControlAdder.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ActivePowerControlAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ActivePowerControlImpl.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/extensions/ActivePowerControlSerDe.java
  iidm/iidm-serde/src/main/resources/xsd/activePowerControl_V1_2.xsd
  iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/EurostagBinaryTest.java
  iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/extensions/ActivePowerControlXmlTest.java
  iidm/iidm-serde/src/test/resources/V1_12/activePowerControlWithLimitRoundTripRef.xml
  iidm/iidm-serde/src/test/resources/V1_12/eurostag-tutorial1-lf-extensions.bin
  iidm/iidm-serde/src/test/resources/V1_12/eurostag-tutorial1-lf-extensions.json
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractActivePowerControlTest.java
Labels: PR: ready-to-be-merged, June release

#3050 Consider sides when applying limitReductions with IdentifiableCriterion
  iidm/iidm-criteria/src/main/java/com/powsybl/iidm/criteria/AtLeastOneCountryCriterion.java
  iidm/iidm-criteria/src/main/java/com/powsybl/iidm/criteria/AtLeastOneNominalVoltageCriterion.java
  iidm/iidm-criteria/src/main/java/com/powsybl/iidm/criteria/Criterion.java
  iidm/iidm-criteria/src/main/java/com/powsybl/iidm/criteria/NetworkElementVisitor.java
  iidm/iidm-criteria/src/main/java/com/powsybl/iidm/criteria/translation/DefaultNetworkElementAdapter.java
  iidm/iidm-criteria/src/main/java/com/powsybl/iidm/criteria/translation/NetworkElement.java
  iidm/iidm-criteria/src/test/java/com/powsybl/iidm/criteria/DanglingLineCriterionTest.java
  iidm/iidm-criteria/src/test/java/com/powsybl/iidm/criteria/IdentifiableCriterionTest.java
  iidm/iidm-criteria/src/test/java/com/powsybl/iidm/criteria/LineCriterionTest.java
  iidm/iidm-criteria/src/test/java/com/powsybl/iidm/criteria/ThreeWindingsTransformerCriterionTest.java
  iidm/iidm-criteria/src/test/java/com/powsybl/iidm/criteria/TieLineCriterionTest.java
  iidm/iidm-criteria/src/test/java/com/powsybl/iidm/criteria/TwoWindingsTransformerCriterionTest.java
  iidm/iidm-criteria/src/test/java/com/powsybl/iidm/criteria/translation/DefaultNetworkElementAdapterTest.java
  iidm/iidm-criteria/src/test/java/com/powsybl/iidm/criteria/translation/NetworkElementTest.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/limitreduction/AbstractLimitReductionsApplier.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/limitreduction/DefaultLimitReductionsApplierTest.java
Labels: bug, PR: ready-to-be-merged, June release

#3036 Add dynamic simulation docs
  .gitignore
  docs/simulation/dynamic/configuration.md
  docs/simulation/dynamic/index.md
  docs/simulation/dynamic/parameters.md
  docs/user/itools/dynamic-simulation.md
Labels: Documentation

#3058 Update CGMES documentation from website version
  docs/grid_exchange_formats/cgmes/examples.md
  docs/grid_exchange_formats/cgmes/export.md
  docs/grid_exchange_formats/cgmes/import.md
  docs/grid_exchange_formats/cgmes/index.md
  docs/grid_exchange_formats/cgmes/post_processor.md
  docs/grid_exchange_formats/cgmes/triple_store.md
Labels: Documentation

#3018 Another dependencies update
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/tools/ConversionToolUtils.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNetworkTest.java
  pom.xml
Labels: June release

#2955 Generic Area model in IIDM
  docs/grid_model/network_subnetwork.md
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Area.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/AreaAdder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/AreaBoundary.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/AreaBoundaryAdder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/IdentifiableType.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Network.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractVoltageLevel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AreaAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AreaBoundaryAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AreaBoundaryImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AreaImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SubnetworkImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/AreaTest.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/AreaBoundarySerDe.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/AreaSerDe.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/BoundaryRefSerDe.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/NetworkSerDe.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/VoltageLevelRefSerDe.java
  iidm/iidm-serde/src/main/resources/xsd/iidm_V1_13.xsd
  iidm/iidm-serde/src/main/resources/xsd/iidm_equipment_V1_13.xsd
  iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/AreaSerDeTest.java
  iidm/iidm-serde/src/test/resources/V1_11/areaRoundTripRef.xml
  iidm/iidm-serde/src/test/resources/V1_12/areaRoundTripRef.xml
  iidm/iidm-serde/src/test/resources/V1_13/areaRoundTripRef.xml
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractAreaTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractMergeNetworkTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractSubnetworksCreationTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractSubnetworksExplorationTest.java
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/EurostagTutorialExample1Factory.java
Labels: IIDM, Breaking Change, new version XIIDM/JIIDM, June release

#2927 CGMES export. Handle CGM export dependencies
  cgmes/cgmes-completion/src/main/java/com/powsybl/cgmes/completion/CreateMissingContainersPreProcessor.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/TopologyExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/CgmesConformity1ConversionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/CgmesConformity3ConversionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportContextTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CommonGridModelExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/LegacyCommonGridModelExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/StateVariablesExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/SteadyStateHypothesisExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/issues/ModelIdTest.java
  cgmes/cgmes-extensions/src/main/java/com/powsybl/cgmes/extensions/CgmesMetadataModelsAdderImpl.java
  docs/grid_exchange_formats/cgmes/export.md
Labels: CGMES, PR: ready-to-be-merged, June release

#3056 Allow to use checkLimits methods with LimitReductions
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Overload.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/limitmodification/result/AbstractDistinctLimitsContainer.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/LimitViolationUtils.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/OverloadImpl.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/PermanentLimitCheckResult.java
  iidm/iidm-api/src/test/java/com/powsybl/iidm/network/limitmodification/result/LimitsContainerTest.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/LimitViolationDetection.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/Security.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/limitreduction/SimpleLimitsComputer.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/limitreduction/computation/AbstractLimitsReducer.java
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/limitreduction/computation/SimpleLimitsReducer.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/LimitViolationDetectionTest.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/SecurityTest.java
  security-analysis/security-analysis-default/src/main/java/com/powsybl/security/impl/DefaultSecurityAnalysis.java
Labels: June release

#3065 Support of condensers
  docs/grid_model/network_subnetwork.md
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Generator.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/GeneratorAdder.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/GeneratorAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/GeneratorImpl.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/GeneratorSerDe.java
  iidm/iidm-serde/src/main/resources/xsd/iidm_V1_13.xsd
  iidm/iidm-serde/src/main/resources/xsd/iidm_equipment_V1_13.xsd
  iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/AbstractIidmSerDeTest.java
  iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/GeneratorSerDeTest.java
  iidm/iidm-serde/src/test/resources/V1_12/generator.xml
  iidm/iidm-serde/src/test/resources/V1_13/generator.xml
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractGeneratorTest.java
Labels: IIDM, new version XIIDM/JIIDM, June release

#3068 Support ActivePowerControl extension v1.2 only since IIDM v1.13
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/extensions/ActivePowerControlSerDe.java
  iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/extensions/ActivePowerControlXmlTest.java
  iidm/iidm-serde/src/test/resources/V1_12/activePowerControlWithLimitRoundTripRef.xml
  iidm/iidm-serde/src/test/resources/V1_12/eurostag-tutorial1-lf-extensions.json
Labels: June release

#3069 Fix exception for connectable not found in Network Modification connection and disconnection
  action-api/src/test/java/com/powsybl/action/ApplyActionToNetworkTest.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/AbstractDisconnection.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/ConnectableConnection.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/PlannedDisconnection.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/UnplannedDisconnection.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/ConnectionAndDisconnectionsTest.java
Labels: bug, PR: ready-to-be-merged, June release

#3075 ODRE data post-processing: Replace super-csv by apache commons-csv
  iidm/iidm-geodata/pom.xml
  iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/odre/FileValidator.java
  iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/odre/GeographicDataParser.java
  iidm/iidm-geodata/src/main/java/com/powsybl/iidm/geodata/odre/OdreGeoDataCsvLoader.java
  iidm/iidm-geodata/src/test/resources/eurostag-test/substations-error.csv
  pom.xml
Labels: Breaking Change, June release

#3076 Fix ReferenceTerminals and SlackTerminal iIDM extension with merged networks and subnetworks
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ReferenceTerminals.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/SlackTerminal.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ReferenceTerminalsImpl.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractReferenceTerminalsTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractSlackTerminalTest.java
Labels: bug, June release

#3079 TerminalsConnectionAction: fix javadoc
  action-api/src/main/java/com/powsybl/action/TerminalsConnectionAction.java
Labels: June release

#3081 Fix area boundary auto-removal with merged and detached Networks
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AreaImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SubnetworkImpl.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractAreaTest.java
Labels: June release

#3064 Fix omission of styles.css
  docs/_static/styles/styles.css
Labels: Documentation

#3083 Add historical versions of voltageRegulation xsd for compatibility purposes
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/extensions/VoltageRegulationSerDe.java
  iidm/iidm-serde/src/main/resources/xsd/compatibility/voltage_regulation/voltageRegulation_V1_10.xsd
  iidm/iidm-serde/src/main/resources/xsd/compatibility/voltage_regulation/voltageRegulation_V1_11.xsd
  iidm/iidm-serde/src/main/resources/xsd/compatibility/voltage_regulation/voltageRegulation_V1_12.xsd
  iidm/iidm-serde/src/main/resources/xsd/compatibility/voltage_regulation/voltageRegulation_V1_2.xsd
  iidm/iidm-serde/src/main/resources/xsd/compatibility/voltage_regulation/voltageRegulation_V1_3.xsd
  iidm/iidm-serde/src/main/resources/xsd/compatibility/voltage_regulation/voltageRegulation_V1_4.xsd
  iidm/iidm-serde/src/main/resources/xsd/compatibility/voltage_regulation/voltageRegulation_V1_5.xsd
  iidm/iidm-serde/src/main/resources/xsd/compatibility/voltage_regulation/voltageRegulation_V1_6.xsd
  iidm/iidm-serde/src/main/resources/xsd/compatibility/voltage_regulation/voltageRegulation_V1_7.xsd
  iidm/iidm-serde/src/main/resources/xsd/compatibility/voltage_regulation/voltageRegulation_V1_8.xsd
  iidm/iidm-serde/src/main/resources/xsd/compatibility/voltage_regulation/voltageRegulation_V1_9.xsd
  iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/test/VoltageRegulationSerDeTest.java
  iidm/iidm-serde/src/test/resources/V1_12/voltageRegulationCompatibilityVersion.xml
Labels: PR: ready-to-be-merged, June release

#3061 Allow zero value for limits in loading limits
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ValidationUtil.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractLoadingLimitsAdder.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractCurrentLimitsTest.java
Labels: Breaking Change, PR: ready-to-be-merged, June release

#3084 `ActivePowerControl` extension: Rename optional fields min/maxPOverride -> min/maxTargetP
  docs/grid_model/extensions.md
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ActivePowerControl.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ActivePowerControlAdder.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ActivePowerControlAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ActivePowerControlImpl.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/extensions/ActivePowerControlSerDe.java
  iidm/iidm-serde/src/main/resources/xsd/activePowerControl_V1_2.xsd
  iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/extensions/ActivePowerControlXmlTest.java
  iidm/iidm-serde/src/test/resources/V1_13/activePowerControlWithLimitRoundTripRef.xml
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractActivePowerControlTest.java
Labels: Breaking Change, PR: ready-to-be-merged, June release

#3072 Add connect/disconnect on Tie Lines and HVDC Lines
  action-api/src/main/java/com/powsybl/action/TerminalsConnectionAction.java
  action-api/src/test/java/com/powsybl/action/ApplyActionToNetworkTest.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/HvdcLine.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/TieLine.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractConnectable.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ConnectDisconnectUtil.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/HvdcLineImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerVoltageLevel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TieLineImpl.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/AbstractDisconnection.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/ConnectableConnection.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/ConnectableConnectionBuilder.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/PlannedDisconnection.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/PlannedDisconnectionBuilder.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/UnplannedDisconnection.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/UnplannedDisconnectionBuilder.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/util/ModificationReports.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/ConnectionAndDisconnectionsTest.java
  iidm/iidm-modification/src/test/resources/reportNode/connectable-connected.txt
  iidm/iidm-modification/src/test/resources/reportNode/connectable-disconnected-planned.txt
  iidm/iidm-modification/src/test/resources/reportNode/connectable-disconnected-unplanned.txt
  iidm/iidm-modification/src/test/resources/reportNode/connectable-not-connected.txt
  iidm/iidm-modification/src/test/resources/reportNode/connectable-not-disconnected-planned.txt
  iidm/iidm-modification/src/test/resources/reportNode/connectable-not-disconnected-unplanned.txt
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractHvdcLineTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractTieLineTest.java
Labels: bug, Breaking Change, PR: ready-to-be-merged, June release

#3088 Fix regression on assert command for tool tests
  tools-test/src/main/java/com/powsybl/tools/test/AbstractToolTest.java
  tools-test/src/test/java/com/powsybl/tools/test/CommandLineToolsTest.java
Labels: bug, June release

#3089 Upgrade math native to 1.4.0
  pom.xml
Labels: June release

#3087 CGMES. Fix equivalent injection missing regulation target
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EquivalentInjectionConversion.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/EquivalentInjectionImportTest.java
  cgmes/cgmes-conversion/src/test/resources/issues/ei_regulation_EQ.xml
  cgmes/cgmes-conversion/src/test/resources/issues/ei_regulation_EQ_BD.xml
  cgmes/cgmes-conversion/src/test/resources/issues/ei_regulation_missing_target_SSH.xml
  cgmes/cgmes-conversion/src/test/resources/issues/ei_regulation_with_target_SSH.xml
  cgmes/cgmes-conversion/src/test/resources/issues/ei_regulation_with_target_zero_SSH.xml
Labels: bug, CGMES, June release
