Repository powsybl/powsybl-core, pull requests merged in 2024-07, with the labels that each got.

#3003 Matpower: fix pv buses
  matpower/matpower-converter/src/main/java/com/powsybl/matpower/converter/MatpowerExporter.java
  matpower/matpower-converter/src/test/resources/dangling-line-generation.json
  matpower/matpower-converter/src/test/resources/fourSubstationFactory.json
Labels: bug

#3094 Fix: Update TapChanger neutralPosition after using a stepsReplacer
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractTapChanger.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractTapChangerTest.java
Labels: bug, Breaking Change

#3098 Make method to compute hvdc line losses public
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/HvdcUtils.java
Labels: PR: ready-to-be-merged

#3093 CGMES export: report multiple model identifiers
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CommonGridModelExportTest.java
  commons/src/main/java/com/powsybl/commons/report/TypedValue.java
Labels: CGMES, June release

#3099 CGMES metadata models: allow clear of supersedes
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CommonGridModelExportTest.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesMetadataModel.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesMetadataModelImpl.java
Labels: bug, CGMES, Breaking Change, June release

#3104 Add special SVGs for dark mode
  docs/grid_exchange_formats/psse/img/dark_mode/three-winding-transformer-model.svg
  docs/grid_exchange_formats/psse/img/dark_mode/two-winding-transformer-model.svg
  docs/grid_exchange_formats/psse/img/three-winding-transformer-model.svg
  docs/grid_exchange_formats/psse/img/two-winding-transformer-model.svg
  docs/grid_exchange_formats/psse/import.md
  docs/grid_model/additional.md
  docs/grid_model/img/current-limits-example1.svg
  docs/grid_model/img/current-limits-example2.svg
  docs/grid_model/img/current-limits.svg
  docs/grid_model/img/dangling-line.svg
  docs/grid_model/img/dark_mode/current-limits-example1.svg
  docs/grid_model/img/dark_mode/current-limits-example2.svg
  docs/grid_model/img/dark_mode/current-limits.svg
  docs/grid_model/img/dark_mode/dangling-line.svg
  docs/grid_model/img/dark_mode/generator-sign-convention.svg
  docs/grid_model/img/dark_mode/line-model.svg
  docs/grid_model/img/dark_mode/three-winding-transformer-model.svg
  docs/grid_model/img/dark_mode/two-winding-transformer-model.svg
  docs/grid_model/img/dark_mode/voltage-level.svg
  docs/grid_model/img/three-winding-transformer-model.svg
  docs/grid_model/img/two-winding-transformer-model.svg
  docs/grid_model/network_subnetwork.md
Labels: PR: ready-to-be-merged

#3101 Datasources - Part 1: Rework datasource classes
  ampl-executor/src/main/java/com/powsybl/ampl/executor/AmplModelExecutionHandler.java
  cgmes/cgmes-completion/src/main/java/com/powsybl/cgmes/completion/CreateMissingContainersPreProcessor.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/ConversionTester.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/ImportExportPerformanceTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesNamingStrategyTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CommonGridModelExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/EquipmentExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/ExportToCimVersionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/SteadyStateHypothesisExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/TopologyExportCornerCasesTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/issues/SwitchExportTest.java
  commons/src/main/java/com/powsybl/commons/datasource/AbstractArchiveDataSource.java
  commons/src/main/java/com/powsybl/commons/datasource/AbstractFileSystemDataSource.java
  commons/src/main/java/com/powsybl/commons/datasource/ArchiveFormat.java
  commons/src/main/java/com/powsybl/commons/datasource/Bzip2DirectoryDataSource.java
  commons/src/main/java/com/powsybl/commons/datasource/DataSourceUtil.java
  commons/src/main/java/com/powsybl/commons/datasource/DirectoryDataSource.java
  commons/src/main/java/com/powsybl/commons/datasource/GenericReadOnlyDataSource.java
  commons/src/main/java/com/powsybl/commons/datasource/GzDirectoryDataSource.java
  commons/src/main/java/com/powsybl/commons/datasource/ReadOnlyDataSource.java
  commons/src/main/java/com/powsybl/commons/datasource/XZDirectoryDataSource.java
  commons/src/main/java/com/powsybl/commons/datasource/ZipArchiveDataSource.java
  commons/src/main/java/com/powsybl/commons/datasource/ZstdDirectoryDataSource.java
  commons/src/test/java/com/powsybl/commons/datasource/AbstractArchiveDataSourceTest.java
  commons/src/test/java/com/powsybl/commons/datasource/AbstractFileSystemDataSourceTest.java
  commons/src/test/java/com/powsybl/commons/datasource/ArchiveFormatTest.java
  commons/src/test/java/com/powsybl/commons/datasource/Bzip2DirectoryDataSourceTest.java
  commons/src/test/java/com/powsybl/commons/datasource/Bzip2FileDataSourceTest.java
  commons/src/test/java/com/powsybl/commons/datasource/DataSourceObserverTest.java
  commons/src/test/java/com/powsybl/commons/datasource/DataSourceTest.java
  commons/src/test/java/com/powsybl/commons/datasource/DataSourceUtilTest.java
  commons/src/test/java/com/powsybl/commons/datasource/DirectoryDataSourceTest.java
  commons/src/test/java/com/powsybl/commons/datasource/FileDataSourceTest.java
  commons/src/test/java/com/powsybl/commons/datasource/GzDirectoryDataSourceTest.java
  commons/src/test/java/com/powsybl/commons/datasource/GzFileDataSourceTest.java
  commons/src/test/java/com/powsybl/commons/datasource/MemDataSourceTest.java
  commons/src/test/java/com/powsybl/commons/datasource/MemFileDataSourceTest.java
  commons/src/test/java/com/powsybl/commons/datasource/MultipleReadOnlyDataSourceTest.java
  commons/src/test/java/com/powsybl/commons/datasource/XZDirectoryDataSourceTest.java
  commons/src/test/java/com/powsybl/commons/datasource/XZFileDataSourceTest.java
  commons/src/test/java/com/powsybl/commons/datasource/ZipArchiveDataSourceTest.java
  commons/src/test/java/com/powsybl/commons/datasource/ZipFileDataSourceTest.java
  commons/src/test/java/com/powsybl/commons/datasource/ZstdDirectoryDataSourceTest.java
  commons/src/test/java/com/powsybl/commons/datasource/ZstdFileDataSourceTest.java
  commons/src/test/resources/foo.iidm.zip
  ieee-cdf/ieee-cdf-converter/src/test/java/com/powsybl/ieeecdf/converter/IeeeCdfImporterTest.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Importers.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Network.java
  iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/XMLImporterTest.java
  matpower/matpower-converter/src/test/java/com/powsybl/matpower/converter/MatpowerExporterTest.java
  matpower/matpower-converter/src/test/java/com/powsybl/matpower/converter/MatpowerImporterTest.java
  matpower/matpower-converter/src/test/java/com/powsybl/matpower/converter/MatpowerRoundTripTest.java
  powerfactory/powerfactory-converter/src/test/java/com/powsybl/powerfactory/converter/PowerFactoryImporterTest.java
  psse/psse-converter/src/test/java/com/powsybl/psse/converter/PsseExporterTest.java
  psse/psse-model/src/test/java/com/powsybl/psse/model/PsseRawDataTest.java
  triple-store/triple-store-test/src/test/java/com/powsybl/triplestore/test/ExportTest.java
Labels: Breaking Change

#3096 [Short-circuit API] Add some javadoc.
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/BranchFault.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/BusFault.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/FailedFaultResult.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/Fault.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/FaultParameters.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/FaultResult.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/FeederResult.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/FortescueFaultResult.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/FortescueFeederResult.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/FortescueShortCircuitBusResults.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/FortescueValue.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/InitialVoltageProfileMode.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/MagnitudeFaultResult.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/MagnitudeFeederResult.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/MagnitudeShortCircuitBusResults.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/ShortCircuitBusResults.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/ShortCircuitConstants.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/ShortCircuitParameters.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/StudyType.java
Labels: Javadoc, Shortcircuits, Documentation

#3100 [Network modification] Modify log when no extension is created.
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AbstractCreateConnectableFeederBays.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/util/ModificationReports.java
  iidm/iidm-modification/src/test/resources/reportNode/create-line-NB-without-extensions-report.txt
  iidm/iidm-modification/src/test/resources/reportNode/create-load-NB-without-extensions-report.txt
Labels: Log

#2995 Cgmes active reactive regulating control
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/RegulatingControlEq.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/TapChangerEq.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/EquipmentExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/SteadyStateHypothesisExportTest.java
  docs/grid_exchange_formats/cgmes/export.md
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/EurostagTutorialExample1Factory.java
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/PhaseShifterTestCaseFactory.java
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/ShuntTestCaseFactory.java
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/SvcTestCaseFactory.java
Labels: PR: ready-to-be-merged
