Repository powsybl/powsybl-core, pull requests merged in 2024-11, with the labels that each got.

#3180 Rework missing voltage level test (remove conformity modified file)
  cgmes/cgmes-completion/src/test/java/com/powsybl/cgmes/completion/CgmesCompletionTest.java
  cgmes/cgmes-completion/src/test/resources/missing_voltagelevel.xml
  cgmes/cgmes-conformity/src/main/java/com/powsybl/cgmes/conformity/CgmesConformity1ModifiedCatalog.java
  cgmes/cgmes-conformity/src/main/resources/conformity-modified/cas-1.1.3-data-4.0.3/MiniGrid/NodeBreaker/BaseCase_Complete_v3_missing_voltage_level/MiniGridTestConfiguration_BC_EQ_v3.0.0.xml
Labels: Breaking Change

#3196 Refactor voltage level topology implementation
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractConnectable.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractTerminal.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractTopologyModel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BatteryAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusBreakerTopologyModel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusTerminal.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusbarSectionAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/CalculatedBusImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ConnectDisconnectUtil.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/DanglingLineAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/GeneratorAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/GroundAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/LccConverterStationAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/LineAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/LoadAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerTopologyModel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeTerminal.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ShuntCompensatorAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/StaticVarCompensatorAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SwitchImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ThreeWindingsTransformerAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TopologyModel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/TwoWindingsTransformerAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VoltageLevelAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VoltageLevelExt.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VoltageLevelImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VscConverterStationAdderImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/NodeBreakerConnectTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/TestAbstractTopologyModel.java
Labels: December 2024 release

#3176 fix: OverloadManagementSystem did not serialize to binary when a trip…
  commons/src/main/java/com/powsybl/commons/binary/BinReader.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/OverloadManagementSystemSerDe.java
  iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/OverloadManagementSystemSerDeTest.java
  iidm/iidm-serde/src/test/resources/V1_13/overloadManagementSystemRoundTripRef.xml
Labels: bug, PR: waiting-for-review

#3203 Add network events to IIDM API
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/DefaultNetworkListener.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/NetworkEventRecorder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/NetworkListener.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/events/CreationNetworkEvent.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/events/ExtensionCreationNetworkEvent.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/events/ExtensionRemovalNetworkEvent.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/events/ExtensionUpdateNetworkEvent.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/events/NetworkEvent.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/events/PropertiesUpdateNetworkEvent.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/events/RemovalNetworkEvent.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/events/UpdateNetworkEvent.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/events/VariantNetworkEvent.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractIdentifiable.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusBreakerTopologyModel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/BusTerminal.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkListenerList.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NodeBreakerTopologyModel.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/SubstationImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ActivePowerControlAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ActivePowerControlImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ControlUnitImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/PilotPointImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/OperationalLimitsGroupImplTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/tck/NetworkEventTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractConnectionNotificationTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractLineTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractLoadTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractMoveConnectableNotifTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNetworkEventTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNetworkTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractSubstationTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractTapChangerTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractTieLineTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractSecondaryVoltageControlTest.java
Labels: Breaking Change

#3170 Add tgz option to iTools packager Maven plugin
  distribution-core/pom.xml
  itools-packager/README.md
  itools-packager/pom.xml
  itools-packager/src/main/java/com/powsybl/itools/ItoolsPackagerMojo.java
  itools-packager/src/test/java/com/powsybl/itools/ItoolsPackagerMojoTest.java
  itools-packager/src/test/resources/test-maven-project/pom.xml
  pom.xml
Labels: PR: ready-to-be-merged, December 2024 release

#3183 CGMES: Support WindGeneratingUnit.windGenUnitType onshore/offshore
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SynchronousMachineConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/GeneratingUnitEq.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/GeneratorConversionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/EquipmentExportTest.java
  cgmes/cgmes-conversion/src/test/resources/GeneratingUnitTypes.xml
  cgmes/cgmes-model/src/main/resources/CIM100.sparql
  cgmes/cgmes-model/src/main/resources/CIM16.sparql
  docs/grid_exchange_formats/cgmes/import.md
Labels: CGMES, PR: waiting-for-review, December 2024 release

#3214 Fix CIM100 CGMES import regression issue on synchronous machine
  cgmes/cgmes-model/src/main/resources/CIM100.sparql
Labels: December 2024 release

#3209 Add area interchange target update action
  action-api/src/main/java/com/powsybl/action/AreaInterchangeTargetAction.java
  action-api/src/main/java/com/powsybl/action/AreaInterchangeTargetActionBuilder.java
  action-api/src/main/java/com/powsybl/action/json/ActionJsonModule.java
  action-api/src/main/java/com/powsybl/action/json/AreaInterchangeTargetActionDeserializer.java
  action-api/src/main/java/com/powsybl/action/json/AreaInterchangeTargetActionSerializer.java
  action-api/src/test/java/com/powsybl/action/EqualsActionTest.java
  action-api/src/test/java/com/powsybl/action/json/JsonActionTest.java
  action-api/src/test/resources/ActionFileTest.json
  action-api/src/test/resources/ActionFileTestV1.0.json
  docs/simulation/security/index.md
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/AreaInterchangeTargetModification.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/AreaInterchangeModificationTest.java
Labels: December 2024 release

#3189 Add percent change load action
  action-api/src/main/java/com/powsybl/action/PercentChangeLoadAction.java
  action-api/src/main/java/com/powsybl/action/PercentChangeLoadActionBuilder.java
  action-api/src/main/java/com/powsybl/action/json/ActionJsonModule.java
  action-api/src/main/java/com/powsybl/action/json/PercentChangeLoadActionBuilderDeserializer.java
  action-api/src/main/java/com/powsybl/action/json/PercentChangeLoadActionSerializer.java
  action-api/src/test/java/com/powsybl/action/ActionBuilderTest.java
  action-api/src/test/java/com/powsybl/action/ApplyActionToNetworkTest.java
  action-api/src/test/java/com/powsybl/action/EqualsActionTest.java
  action-api/src/test/java/com/powsybl/action/json/JsonActionTest.java
  action-api/src/test/resources/ActionFileTest.json
  action-api/src/test/resources/ActionFileTestV1.0.json
  docs/simulation/security/index.md
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/PercentChangeLoadModification.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/PercentChangeLoadModificationTest.java
Labels: PR: waiting-for-review, December 2024 release

#3192 Network modification to set generator regulation to local instead of remote
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/SetGeneratorToLocalRegulation.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/util/ModificationReports.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/SetGeneratorToLocalRegulationTest.java
Labels: December 2024 release

#3216 Add new matrix methods for DenseMatrix
  math/src/main/java/com/powsybl/math/matrix/DenseMatrix.java
  math/src/test/java/com/powsybl/math/matrix/DenseMatrixTest.java
Labels: December 2024 release

#3213 Add missing equipment types to Contingency DSL loader
  contingency/contingency-dsl/src/main/groovy/com/powsybl/contingency/dsl/ContingencyDslLoader.groovy
  contingency/contingency-dsl/src/test/java/com/powsybl/contingency/dsl/ContingencyElementTypesTest.java
  contingency/contingency-dsl/src/test/java/com/powsybl/contingency/dsl/DanglingLineContingencyScriptTest.java
  contingency/contingency-dsl/src/test/java/com/powsybl/contingency/dsl/ThreeWindingsTransformerContingencyScriptTest.java
  docs/simulation/security/contingency-dsl.md
  docs/simulation/security/index.md
Labels: Contingency, December 2024 release

#3198 CGMES export - Add a parameter to export generators in local regulation mode
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/EquipmentExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/SteadyStateHypothesisExportTest.java
  docs/grid_exchange_formats/cgmes/export.md
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/EurostagTutorialExample1Factory.java
Labels: CGMES, December 2024 release

#3226 [Shortcircuit] Add some documentation about the voltage attribute of voltage ranges.
  docs/simulation/shortcircuit/parameters.md
Labels: PR: ready-to-be-merged, Shortcircuits, Documentation, December 2024 release

#3168 Add getI() method to DanglingLine's boundary
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Boundary.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/DanglingLineBoundaryImpl.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/SV.java
  iidm/iidm-api/src/test/java/com/powsybl/iidm/network/util/SVTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/TieLineTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/util/SVTest.java
Labels: IIDM, Breaking Change, Feature, December 2024 release

#3229 Fix switch contingency support
  contingency/contingency-api/src/main/java/com/powsybl/contingency/Contingency.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/json/ContingencyElementDeserializer.java
  contingency/contingency-api/src/test/java/com/powsybl/contingency/SwitchContingencyTest.java
  contingency/contingency-api/src/test/java/com/powsybl/contingency/json/ContingencyJsonTest.java
  contingency/contingency-api/src/test/resources/contingenciesWith3wt.json
  contingency/contingency-api/src/test/resources/contingenciesWithDlAndTl.json
  contingency/contingency-api/src/test/resources/contingenciesWithSeveralElements.json
Labels: PR: ready-to-be-merged, December 2024 release

#3167 Network modification. Replace threeWindingsTransformers by 3 twoWindingsTransformers and vice versa
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/RemoteReactivePowerControl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/RemoteReactivePowerControlImpl.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/Replace3TwoWindingsTransformersByThreeWindingsTransformers.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/ReplaceThreeWindingsTransformersBy3TwoWindingsTransformers.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/util/ModificationReports.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/util/RegulatedTerminalControllers.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/util/TransformerUtils.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/ControlledRegulatingTerminalsTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/Replace3TwoWindingsTransformersByThreeWindingsTransformersTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/ReplaceThreeWindingsTransformersBy3TwoWindingsTransformersTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/TransformersTestUtils.java
Labels: Breaking Change, December 2024 release
