Repository powsybl/powsybl-core, pull requests merged in 2024-08, with the labels that each got.

#3114 Datasources - part 5: fixes
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/conformity/Cgmes3ConversionTest.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesOnDataSource.java
  cgmes/cgmes-model/src/test/java/com/powsybl/cgmes/model/CgmesOnDataSourceTest.java
Labels: Breaking Change

#3097 UCTE Importer: create IIDM Areas
  docs/grid_exchange_formats/ucte/import.md
  ucte/ucte-converter/src/main/java/com/powsybl/ucte/converter/UcteImporter.java
  ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/UcteImporterTest.java
Labels: UCTE

#3119 Documentation about limit reductions
  docs/simulation/security/index.md
  docs/simulation/security/limit-reductions.md
Labels: Documentation
