Repository powsybl/powsybl-core, pull requests merged in 2025-06, with the labels that each got.

#3454 Secondary voltage control extension variant support
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractMultiVariantIdentifiableExtension.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ControlUnitAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ControlUnitImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ControlZoneAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ControlZoneImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/PilotPointAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/PilotPointImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/SecondaryVoltageControlAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/SecondaryVoltageControlImpl.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractSecondaryVoltageControlTest.java
Labels: Release 06/2025

#3440 PSS/E errors with parsing PSS/E Files (Delimiters, Missing Q Record, Comments)
  psse/psse-converter/src/test/java/com/powsybl/psse/converter/PsseImporterIllinoisTest.java
  psse/psse-converter/src/test/java/com/powsybl/psse/converter/PsseImporterTest.java
  psse/psse-converter/src/test/resources/IEEE_14_bus_delimiter.raw
  psse/psse-converter/src/test/resources/IEEE_14_bus_delimiter.xiidm
  psse/psse-converter/src/test/resources/parallelTwoTerminalDcBetweenSameAcBuses_updated_exported.raw
  psse/psse-converter/src/test/resources/remoteControl_updated_exported.raw
  psse/psse-converter/src/test/resources/twoTerminalDc_updated_exported.raw
  psse/psse-model-test/src/main/resources/illinois/literature-based/IEEE 39 bus-fixed-mixed-delimiters.RAW
  psse/psse-model-test/src/main/resources/illinois/synthetic/Texas2000_June2016.RAW
  psse/psse-model/src/main/java/com/powsybl/psse/model/io/FileFormat.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/io/LegacyTextReader.java
  psse/psse-model/src/test/resources/IEEE_14_bus_whitespaceAsDelimiter_exported.raw
Labels: Release 06/2025

#3465 Prevent potential backtracking on PSS/E import
  psse/psse-model/src/main/java/com/powsybl/psse/model/io/LegacyTextReader.java
  psse/psse-model/src/test/java/com/powsybl/psse/model/io/LegacyTextReaderTest.java
Labels: Release 06/2025

#3464 Fix UCTE-DEF online reference link
  docs/grid_exchange_formats/ucte/format_specification.md
  entsoe-util/src/main/java/com/powsybl/entsoe/util/EntsoeGeographicalCode.java
Labels: PR: ready-to-be-merged, Release 06/2025

#3462 Improve iIDM battery documentation
  docs/grid_model/network_subnetwork.md
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Battery.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Branch.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/BusbarSection.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/DanglingLine.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Generator.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/HvdcLine.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/LccConverterStation.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Load.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Network.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ShuntCompensator.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/StaticVarCompensator.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Substation.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ThreeWindingsTransformer.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/TieLine.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/TwoWindingsTransformer.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VoltageLevel.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/VscConverterStation.java
Labels: PR: ready-to-be-merged, Release 06/2025

#3444 Hvdc adjustments
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/hvdc/CgmesDcConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/hvdc/DcLineSegmentConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/hvdc/Hvdc.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/hvdc/LossFactor.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/SteadyStateHypothesisExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/HvdcConversionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/ExportXmlCompare.java
Labels: CGMES, Release 06/2025

#3361 rdf4j dependency update
  pom.xml
  triple-store/triple-store-impl-rdf4j/src/main/java/com/powsybl/triplestore/impl/rdf4j/TripleStoreRDF4J.java
Labels: Release 06/2025

#3375 Drop support for CIM14
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMappingForTransformers.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/OperationalLimitConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/SynchronousMachineConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/AbstractTransformerConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/transformers/CgmesPhaseTapChangerBuilder.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/ImportExportPerformanceTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/cim14/Cim14SmallCasesConversionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/cim14/Cim14SmallCasesNetworkCatalog.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportContextTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesNamingStrategyTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/EquipmentExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/ExportToCimVersionTest.java
  cgmes/cgmes-conversion/src/test/resources/cim14/7buses.xiidm
  cgmes/cgmes-conversion/src/test/resources/cim14/ieee14.xiidm
  cgmes/cgmes-conversion/src/test/resources/cim14/tx-from-microBE-adapted.xiidm
  cgmes/cgmes-conversion/src/test/resources/cim14/vl_without_name.xml
  cgmes/cgmes-conversion/src/test/resources/nordic32.xiidm
  cgmes/cgmes-model-test/src/main/java/com/powsybl/cgmes/model/test/Cim14SmallCasesCatalog.java
  cgmes/cgmes-model-test/src/main/resources/cim14/ENTSO-E_Boundary_Set_EU_EQ.xml
  cgmes/cgmes-model-test/src/main/resources/cim14/ENTSO-E_Boundary_Set_EU_TP.xml
  cgmes/cgmes-model-test/src/main/resources/cim14/condenser/condenser_EQ.xml
  cgmes/cgmes-model-test/src/main/resources/cim14/condenser/condenser_TP.xml
  cgmes/cgmes-model-test/src/main/resources/cim14/ieee14/ieee14bus_EQ.xml
  cgmes/cgmes-model-test/src/main/resources/cim14/ieee14/ieee14bus_SV.xml
  cgmes/cgmes-model-test/src/main/resources/cim14/ieee14/ieee14bus_TP.xml
  cgmes/cgmes-model-test/src/main/resources/cim14/m7buses-no-sequenceNumbers/m7buses-no-sequenceNumbers_EQ.xml
  cgmes/cgmes-model-test/src/main/resources/cim14/m7buses/m7buses_EQ.xml
  cgmes/cgmes-model-test/src/main/resources/cim14/m7buses/m7buses_SV.xml
  cgmes/cgmes-model-test/src/main/resources/cim14/m7buses/m7buses_TP.xml
  cgmes/cgmes-model-test/src/main/resources/cim14/nordic32/Nordic32_EQ.xml
  cgmes/cgmes-model-test/src/main/resources/cim14/nordic32/Nordic32_SV.xml
  cgmes/cgmes-model-test/src/main/resources/cim14/nordic32/Nordic32_TP.xml
  cgmes/cgmes-model-test/src/main/resources/cim14/smallcase1/case1_EQ.xml
  cgmes/cgmes-model-test/src/main/resources/cim14/smallcase1/case1_SV.xml
  cgmes/cgmes-model-test/src/main/resources/cim14/smallcase1/case1_TP.xml
  cgmes/cgmes-model-test/src/main/resources/cim14/tx-from-microBE-adapted/tx-from-microBE-adapted_EQ.xml
  cgmes/cgmes-model-test/src/main/resources/cim14/tx-from-microBE-adapted/tx-from-microBE-adapted_SV.xml
  cgmes/cgmes-model-test/src/main/resources/cim14/tx-from-microBE-adapted/tx-from-microBE-adapted_TP.xml
  cgmes/cgmes-model-test/src/main/resources/validCim14InvalidContent_EQ.xml
  cgmes/cgmes-model-test/src/test/java/com/powsybl/cgmes/model/test/cim14/Cim14SmallCasesTest.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesModel.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesNamespace.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesOnDataSource.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/WindingType.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/triplestore/CgmesModelTripleStore.java
  cgmes/cgmes-model/src/main/resources/CIM14.sparql
  cgmes/cgmes-model/src/test/java/com/powsybl/cgmes/model/CgmesOnDataSourceTest.java
  cgmes/cgmes-model/src/test/java/com/powsybl/cgmes/model/WindingTypeTest.java
  cgmes/cgmes-model/src/test/resources/empty_cim14_SV.xml
  cgmes/cgmes-model/src/test/resources/empty_cim16_SV.xml
  cgmes/cgmes-model/src/test/resources/validCim14InvalidContent_EQ.xml
Labels: Breaking Change, Release 06/2025

#3484 Support properties on OperationalLimitsGroup
  docs/grid_model/additional.md
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Identifiable.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/OperationalLimitsGroup.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/PropertiesHolder.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractIdentifiable.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractPropertiesHolder.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/OperationalLimitsGroupImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/PropertiesContainer.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/ConnectableSerDeUtil.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/PropertiesSerDe.java
  iidm/iidm-serde/src/main/resources/xsd/iidm_V1_14.xsd
  iidm/iidm-serde/src/main/resources/xsd/iidm_equipment_V1_14.xsd
  iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/LoadingLimitsXmlTest.java
  iidm/iidm-serde/src/test/resources/V1_12/operational-limits-groups-with-properties.xml
  iidm/iidm-serde/src/test/resources/V1_13/operational-limits-groups-with-properties.xml
  iidm/iidm-serde/src/test/resources/V1_14/operational-limits-groups-with-properties.xml
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractOperationalLimitsGroupsTest.java
Labels: Breaking Change, new version XIIDM/JIIDM, Custom IIDM impl, Release 06/2025

#3442 iIDM v1.14: Solved values - Add solved tap position
  docs/grid_model/additional.md
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/TapChanger.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/TapChangerAdder.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractTapChanger.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractTapChangerAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/PhaseTapChangerAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/PhaseTapChangerImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/RatioTapChangerAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/RatioTapChangerImpl.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/AbstractTransformerSerDe.java
  iidm/iidm-serde/src/main/resources/xsd/iidm_V1_14.xsd
  iidm/iidm-serde/src/main/resources/xsd/iidm_equipment_V1_14.xsd
  iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/RatioTapChangerSerDeTest.java
  iidm/iidm-serde/src/test/resources/V1_14/ratioTapChangerReactivePowerControlRefWithSolvedTapPosition.xml
  iidm/iidm-serde/src/test/resources/V1_14/twoWindingsTransformerPhaseAndRatioTapWithExtensions.xml
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractTwoWindingsTransformerTest.java
Labels: IIDM, Breaking Change, new version XIIDM/JIIDM, Custom IIDM impl, Release 06/2025

#3398 Rename test resources bundle
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/CgmesReportsTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/FunctionalLogsTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/HvdcConversionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CommonGridModelExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/ExportProfilesConsistencyTest.java
  commons-test/src/main/java/com/powsybl/commons/test/PowsyblTestReportResourceBundle.java
  commons/src/test/java/com/powsybl/commons/report/CommonsTestReportResourceBundle.java
  commons/src/test/java/com/powsybl/commons/report/NoOpTest.java
  commons/src/test/java/com/powsybl/commons/report/ReportFormatterTest.java
  commons/src/test/java/com/powsybl/commons/report/ReportNodeTest.java
  commons/src/test/java/com/powsybl/commons/report/TypedValueTest.java
  iidm/iidm-api/src/test/java/com/powsybl/iidm/network/ExportersTest.java
  iidm/iidm-api/src/test/java/com/powsybl/iidm/network/ImportersTest.java
  iidm/iidm-api/src/test/java/com/powsybl/iidm/network/PostProcessorReportNodeTest.java
  iidm/iidm-api/src/test/java/com/powsybl/iidm/network/ReportNodeContextTest.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/ValidationLevelLogsTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/ConnectionAndDisconnectionsTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/NetworkModificationListTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/Replace3TwoWindingsTransformersByThreeWindingsTransformersTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/ReplaceThreeWindingsTransformersBy3TwoWindingsTransformersTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/SetGeneratorToLocalRegulationTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/ProportionalScalableTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/scalable/StackScalableTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/ConnectVoltageLevelOnLineTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateBranchFeederBaysTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateCouplingDeviceTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateFeederBayTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateLineOnLineTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateVoltageLevelTopologyTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/MoveFeederBayTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/RemoveFeederBayTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/RemoveHvdcLineTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/RemoveSubstationTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/RemoveVoltageLevelTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/ReplaceTeePointByVoltageLevelOnLineTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/RevertConnectVoltageLevelOnLineTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/RevertCreateLineOnLineTest.java
  iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/NetworkSerDeTest.java
  iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/XMLImporterTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractConnectableTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNetworkReportNodeTest.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractNetworkTest.java
  shortcircuit-api/src/test/java/com/powsybl/shortcircuit/ShortCircuitAnalysisTest.java
  time-series/time-series-api/src/test/java/com/powsybl/timeseries/TimeSeriesTest.java
  ucte/ucte-converter/src/test/java/com/powsybl/ucte/converter/UcteImporterReportNodeTest.java
Labels: Breaking Change, Release 06/2025

#3275 [Network modifications] Add boolean indicating whether position extensions must be created.
  commons/src/main/resources/com/powsybl/commons/reports.properties
  docs/grid_features/network_modifications.md
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AbstractCreateConnectableFeederBays.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateBranchFeederBays.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateBranchFeederBaysBuilder.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateFeederBay.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateFeederBayBuilder.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/util/ModificationReports.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateBranchFeederBaysTest.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateFeederBayTest.java
  iidm/iidm-modification/src/test/resources/reportNode/create-line-NB-without-extensions-report.txt
  iidm/iidm-modification/src/test/resources/reportNode/create-load-NB-without-extensions-report.txt
Labels: Release 06/2025

#3372 Rework nodes mapping to allow export of isolated nodes
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/NodeMappingTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/TopologyExportCornerCasesTest.java
Labels: bug, CGMES, Release 06/2025

#3422 Dynamic simulation specific parameters update
  dynamic-simulation/dynamic-simulation-api/src/main/java/com/powsybl/dynamicsimulation/DynamicSimulationProvider.java
  dynamic-simulation/dynamic-simulation-api/src/main/java/com/powsybl/dynamicsimulation/json/DynamicSimulationParametersDeserializer.java
  dynamic-simulation/dynamic-simulation-api/src/main/java/com/powsybl/dynamicsimulation/json/DynamicSimulationParametersSerializer.java
  dynamic-simulation/dynamic-simulation-api/src/main/java/com/powsybl/dynamicsimulation/json/JsonDynamicSimulationParameters.java
  dynamic-simulation/dynamic-simulation-api/src/test/java/com/powsybl/dynamicsimulation/AnotherDynamicSimulationProviderMock.java
  dynamic-simulation/dynamic-simulation-api/src/test/java/com/powsybl/dynamicsimulation/DummyExtension.java
  dynamic-simulation/dynamic-simulation-api/src/test/java/com/powsybl/dynamicsimulation/DummySpecificParametersSerializer.java
  dynamic-simulation/dynamic-simulation-api/src/test/java/com/powsybl/dynamicsimulation/DynamicSimulationProviderMock.java
  dynamic-simulation/dynamic-simulation-api/src/test/java/com/powsybl/dynamicsimulation/DynamicSimulationProviderTest.java
  dynamic-simulation/dynamic-simulation-api/src/test/java/com/powsybl/dynamicsimulation/json/JsonDynamicSimulationParametersTest.java
  dynamic-simulation/dynamic-simulation-api/src/test/resources/DynamicSimulationParametersWithExtension.json
  dynamic-simulation/dynamic-simulation-tool/src/test/java/com/powsybl/dynamicsimulation/tool/DynamicSimulationProviderMock.java
Labels: Breaking Change, Release 06/2025
