Repository powsybl/powsybl-core, pull requests merged in 2025-08, with the labels that each got.

#3513 Psse: Support substations with buses at the same nominal voltage in different areas
  ieee-cdf/ieee-cdf-converter/src/main/java/com/powsybl/ieeecdf/converter/IeeeCdfImporter.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/ContainersMapping.java
  matpower/matpower-converter/src/main/java/com/powsybl/matpower/converter/MatpowerImporter.java
  powerfactory/powerfactory-converter/src/main/java/com/powsybl/powerfactory/converter/ContainersMappingHelper.java
  psse/psse-converter/src/main/java/com/powsybl/psse/converter/PsseImporter.java
  psse/psse-converter/src/test/java/com/powsybl/psse/converter/PsseImporterTest.java
  psse/psse-converter/src/test/resources/SubstationWithThreeBusesAtTheSameNominalVoltageInTwoDifferentAreas.raw
  psse/psse-converter/src/test/resources/SubstationWithThreeBusesAtTheSameNominalVoltageInTwoDifferentAreas.xiidm
Labels: Breaking Change, Deprecated, Release 09/2025

#3544 Fix typos "can not" -> "cannot"
  action-api/src/main/java/com/powsybl/action/PhaseTapChangerRegulationAction.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMappingForStaticVarCompensators.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/BusbarSectionConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/NodeConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/TopologyTester.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesTopologyKindTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/issues/ExportNumberMaxValueTest.java
  computation/src/main/java/com/powsybl/computation/ComputationExceptionBuilder.java
  computation/src/main/java/com/powsybl/computation/ThreadInterruptedCompletableFuture.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/ContingencyElementFactory.java
  contingency/contingency-api/src/test/java/com/powsybl/contingency/CriterionContingencyListTest.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/identifiers/json/IdentifierDeserializer.java
  iidm/iidm-criteria/src/main/java/com/powsybl/iidm/criteria/PropertyCriterion.java
  iidm/iidm-criteria/src/main/java/com/powsybl/iidm/criteria/json/CriterionDeserializer.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/DiscreteMeasurement.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/Measurement.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/util/DiscreteMeasurementValidationUtil.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/util/MeasurementValidationUtil.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/MeasurementAdderImpl.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/Replace3TwoWindingsTransformersByThreeWindingsTransformers.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/ReplaceThreeWindingsTransformersBy3TwoWindingsTransformers.java
  psse/psse-converter/src/main/java/com/powsybl/psse/converter/AbstractConverter.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/PsseVersioned.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/io/RecordGroupIOJson.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/io/RecordGroupIOLegacyText.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/pf/io/CaseIdentificationData.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/PhaseTapChangerRegulationActionTest.java
Labels: Release 09/2025

#3501 Delete the default Security Analysis
  distribution-core/pom.xml
  docs/simulation/security/implementations.md
  security-analysis/pom.xml
  security-analysis/security-analysis-default/pom.xml
  security-analysis/security-analysis-default/src/main/java/com/powsybl/security/impl/DefaultSecurityAnalysis.java
  security-analysis/security-analysis-default/src/main/java/com/powsybl/security/impl/DefaultSecurityAnalysisProvider.java
  security-analysis/security-analysis-default/src/test/java/com/powsybl/security/impl/SecurityAnalysisProviderTest.java
  security-analysis/security-analysis-default/src/test/java/com/powsybl/security/impl/SecurityAnalysisTest.java
  security-analysis/security-analysis-default/src/test/java/com/powsybl/security/impl/interceptors/SecurityAnalysisInterceptorMock.java
  security-analysis/security-analysis-default/src/test/java/com/powsybl/security/impl/interceptors/SecurityAnalysisInterceptorMockExtension.java
  security-analysis/security-analysis-default/src/test/java/com/powsybl/security/impl/interceptors/SecurityAnalysisInterceptorTest.java
  security-analysis/security-analysis-default/src/test/java/com/powsybl/security/impl/mocks/LoadFlowProviderMock.java
  security-analysis/security-analysis-default/src/test/java/com/powsybl/security/impl/monitors/StateMonitorIndexTest.java
  security-analysis/security-analysis-default/src/test/java/com/powsybl/security/impl/results/BranchResultTest.java
  security-analysis/security-analysis-default/src/test/java/com/powsybl/security/impl/results/BusResultTest.java
  security-analysis/security-analysis-default/src/test/java/com/powsybl/security/impl/results/ThreeWindingsTransformerResultTest.java
  security-analysis/security-analysis-default/src/test/resources/com/powsybl/config/test/config.yml
  security-analysis/security-analysis-default/src/test/resources/com/powsybl/config/test/filelist.txt
Labels: Breaking Change, Release 09/2025

#3536 Add parameters to set the switches open in `CreateVoltageLevelSections`
  docs/grid_features/network_modifications.md
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateVoltageLevelSections.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateVoltageLevelSectionsBuilder.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateVoltageLevelSectionsTest.java
  iidm/iidm-modification/src/test/resources/create-vl-sections-insert-after-last-section-with-disconnectors.xiidm
  iidm/iidm-modification/src/test/resources/create-vl-sections-insert-before-first-section-with-breakers.xiidm
  iidm/iidm-modification/src/test/resources/create-vl-sections-insert-between-2-sections-with-breakers.xiidm
  iidm/iidm-modification/src/test/resources/create-vl-sections-insert-between-2-sections-with-disconnectors-on-left-side-and-breakers-on-right-side.xiidm
  iidm/iidm-modification/src/test/resources/create-vl-sections-insert-between-2-sections-with-disconnectors.xiidm
Labels: Release 09/2025

#3541 Apply principle of least privilege to fork-sonar workflow
  .github/workflows/fork-sonar.yml
Labels: CI, Release 09/2025
