Repository powsybl/powsybl-core, pull requests merged in 2025-09, with the labels that each got.

#3554 Ensure unicity on new busbarSection id for CreateVoltageLevelSections
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateVoltageLevelSections.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/CreateVoltageLevelSectionsTest.java
Labels: bug, Release 09/2025

#3546 [Network modifications] Enhance NamingStrategy interface with name creation
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ConnectVoltageLevelOnLine.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateCouplingDevice.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateVoltageLevelSections.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateVoltageLevelTopology.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/NamingStrategy.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/ReplaceTeePointByVoltageLevelOnLine.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/TopologyModificationUtils.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/DefaultNamingStrategyTest.java
Labels: Release 09/2025

#3563 Remove old deprecated code
  ampl-converter/src/test/java/com/powsybl/ampl/converter/AmplNetworkWriterTest.java
  ampl-converter/src/test/resources/inputs/current-limits-test-case.txt
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/TerminalMapping.java
  commons/src/main/java/com/powsybl/commons/compress/ZipHelper.java
  commons/src/main/java/com/powsybl/commons/config/ModuleConfigRepository.java
  computation-local/src/test/java/com/powsybl/computation/local/LocalComputationManagerTest.java
  computation/src/main/java/com/powsybl/computation/SimpleCommand.java
  computation/src/main/java/com/powsybl/computation/SimpleCommandBuilder.java
  computation/src/main/java/com/powsybl/computation/SimpleCommandImpl.java
  computation/src/test/java/com/powsybl/computation/SimpleCommandTest.java
  contingency/contingency-api/src/main/java/com/powsybl/contingency/Contingency.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Battery.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/BatteryAdder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Importer.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Line.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/NetworkFactory.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractMultiVariantConnectableExtension.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateBranchFeederBaysBuilder.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateCouplingDevice.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateCouplingDeviceBuilder.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateFeederBayBuilder.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/NetworkSerializerContext.java
  iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/extensions/GeneratorEntsoeCategoryXmlTest.java
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/EurostagTutorialExample1Factory.java
  loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java
  math/src/main/java/com/powsybl/math/matrix/DenseMatrix.java
  math/src/main/java/com/powsybl/math/matrix/Matrix.java
  math/src/test/java/com/powsybl/math/matrix/AbstractMatrixTest.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/SecurityAnalysisResultBuilderTest.java
  security-analysis/security-analysis-api/src/test/java/com/powsybl/security/SecurityTest.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/ShortCircuitParameters.java
Labels: Breaking Change, Release 09/2025

#3529 transform LegFortescue class to Interface
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/LegFortescue.java
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/ThreeWindingsTransformerFortescue.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/LegFortescueImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ThreeWindingsTransformerFortescueAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/ThreeWindingsTransformerFortescueImpl.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/util/TransformerUtils.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/TransformersTestUtils.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/extensions/ThreeWindingsTransformerFortescueSerDe.java
Labels: Breaking Change, Custom IIDM impl, Release 09/2025

#3538 Improve loadflow run parameters
  loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlow.java
  loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowProviderMock.java
  loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowTest.java
  loadflow/loadflow-api/src/test/resources/i18n/reports.properties
Labels: Release 09/2025

#3443 Add Third-party licenses
  THIRD-PARTY.properties
  THIRD-PARTY.txt
  itools-packager/src/main/java/com/powsybl/itools/ItoolsPackagerMojo.java
  itools-packager/src/test/java/com/powsybl/itools/ItoolsPackagerMojoTest.java
  itools-packager/src/test/resources/test-maven-project-2/LICENSE.txt
  itools-packager/src/test/resources/test-maven-project-2/pom.xml
  itools-packager/src/test/resources/test-maven-project/LICENSE.txt
  itools-packager/src/test/resources/test-maven-project/THIRD-PARTY.txt
Labels: PR: ready-to-be-merged, Release 09/2025

#3278 Cgmes import update. Import EQ and SSH separately. ShuntCompensators
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Conversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/RegulatingControlMappingForShuntCompensators.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/Update.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/AbstractConductingEquipmentConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/EquivalentShuntConversion.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/elements/ShuntConversion.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/ShuntCompensatorUpdateTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/EquipmentExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/ExportXmlCompare.java
  cgmes/cgmes-conversion/src/test/resources/functional-logs/microGridBaseCaseBE-invalid-voltage-bus.txt
  cgmes/cgmes-conversion/src/test/resources/functional-logs/microGridBaseCaseBE-target-deadband.txt
  cgmes/cgmes-conversion/src/test/resources/functional-logs/microGridBaseCaseBE.txt
  cgmes/cgmes-conversion/src/test/resources/functional-logs/miniGridNodeBreaker.txt
  cgmes/cgmes-conversion/src/test/resources/nordic32.xiidm
  cgmes/cgmes-conversion/src/test/resources/update/shunt-compensator/shuntCompensator_EQ.xml
  cgmes/cgmes-conversion/src/test/resources/update/shunt-compensator/shuntCompensator_SSH.xml
  cgmes/cgmes-conversion/src/test/resources/update/shunt-compensator/shuntCompensator_SSH_1.xml
  cgmes/cgmes-conversion/src/test/resources/update/shunt-compensator/shuntCompensator_SV.xml
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesNames.java
  cgmes/cgmes-model/src/main/resources/CIM16-update.sparql
  cgmes/cgmes-model/src/main/resources/CIM16.sparql
Labels: Breaking Change, Release 09/2025, 1EQ 24SSH
