Repository powsybl/powsybl-core, pull requests merged in 2025-05, with the labels that each got.

#3432 Dynamic security analysis tool models load
  dynamic-security-analysis/src/main/java/com/powsybl/security/dynamic/tools/DynamicSecurityAnalysisTool.java
  dynamic-security-analysis/src/test/java/com/powsybl/security/dynamic/tools/DynamicSecurityAnalysisToolTest.java
Labels: bug

#3428 Refactor AbstractThreeWindingsTransformerTest
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/AbstractThreeWindingsTransformerTest.java
Labels: Release 06/2025

#3399 Use all resources bundles in dynamic simulation tool report node
  dynamic-simulation/dynamic-simulation-dsl/src/main/java/com/powsybl/dynamicsimulation/groovy/DynamicSimulationReports.java
Labels: Release 06/2025

#3396 Implement move feederbay network modification
  commons/src/main/resources/com/powsybl/commons/reports.properties
  docs/grid_features/network_modifications.md
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/AbstractCreateConnectableFeederBays.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/MoveFeederBay.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/MoveFeederBayBuilder.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/RemoveFeederBay.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/TopologyModificationUtils.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/util/ModificationReports.java
  iidm/iidm-modification/src/test/java/com/powsybl/iidm/modification/topology/MoveFeederBayTest.java
  iidm/iidm-modification/src/test/resources/i18n/reports.properties
Labels: PR: ready-to-be-merged, Release 06/2025

#3446 Add a handy combined setter for value and validity of a Measurement
  iidm/iidm-extensions/src/main/java/com/powsybl/iidm/network/extensions/Measurement.java
  iidm/iidm-extensions/src/test/java/com/powsybl/iidm/network/extensions/MeasurementTest.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/extensions/MeasurementImpl.java
  iidm/iidm-tck/src/test/java/com/powsybl/iidm/network/tck/extensions/AbstractMeasurementsTest.java
Labels: Release 06/2025

#3273 IIDM ValidationLevel: Add a silent option.
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ValidationUtil.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractTapChanger.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/AbstractTapChangerAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/NetworkImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ShuntCompensatorImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/ValidationLevelLogsTest.java
  iidm/iidm-impl/src/test/resources/i18n/iidm-test-reports.properties
Labels: Breaking Change, Release 06/2025, 1EQ 24SSH

#3330 Triple store queries: replace subqueries with LIMIT 1 by proper subqueries using GROUP BY
  cgmes/cgmes-model/src/main/resources/CIM16.sparql
  triple-store/triple-store-api/src/main/java/com/powsybl/triplestore/api/PropertyBags.java
  triple-store/triple-store-test/src/test/java/com/powsybl/triplestore/test/CgmesRatioTapChangerTest.java
  triple-store/triple-store-test/src/test/java/com/powsybl/triplestore/test/FoafGraphsTest.java
  triple-store/triple-store-test/src/test/java/com/powsybl/triplestore/test/FoafOptionalsTest.java
  triple-store/triple-store-test/src/test/java/com/powsybl/triplestore/test/TripleStoreClearTest.java
  triple-store/triple-store-test/src/test/java/com/powsybl/triplestore/test/TripleStoreCopyTest.java
  triple-store/triple-store-test/src/test/java/com/powsybl/triplestore/test/TripleStoreSubqueryLimit1Test.java
  triple-store/triple-store-test/src/test/java/com/powsybl/triplestore/test/TripleStoreTester.java
  triple-store/triple-store-test/src/test/java/com/powsybl/triplestore/test/TripleStoreUpdateTest.java
  triple-store/triple-store-test/src/test/resources/foaf/abc-multiple-projects.ttl
  triple-store/triple-store-test/src/test/resources/foaf/foaf.sparql
Labels: bug, CGMES, Release 06/2025

#3448 Fix logs on "CreateCouplingDevice" network modification
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/topology/CreateCouplingDevice.java
Labels: Release 06/2025

#3359 Update dependencies
  commons/src/main/java/com/powsybl/commons/compress/ZipPackager.java
  computation/src/main/java/com/powsybl/computation/ComputationExceptionBuilder.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Importer.java
  pom.xml
  security-analysis/security-analysis-api/src/main/java/com/powsybl/security/LimitViolation.java
  security-analysis/security-analysis-default/src/main/java/com/powsybl/security/impl/DefaultSecurityAnalysis.java
  shortcircuit-api/src/main/java/com/powsybl/shortcircuit/FeederResult.java
Labels: Release 06/2025
