Repository powsybl/powsybl-core, pull requests merged in 2025-03, with the labels that each got.

#3269 Sort curves and fsv results in DynamicSimulationResultDeserializer
  dynamic-simulation/dynamic-simulation-api/src/main/java/com/powsybl/dynamicsimulation/json/DynamicSimulationResultDeserializer.java
  dynamic-simulation/dynamic-simulation-api/src/test/java/com/powsybl/dynamicsimulation/json/DynamicSimulationResultJsonTest.java
  dynamic-simulation/dynamic-simulation-api/src/test/resources/DynamicSimulationResult.json
Labels: Release 03/2025

#3339 Remove dead code in UndirectedGraphImpl::removeIsolatedVertices
  math/src/main/java/com/powsybl/math/graph/UndirectedGraphImpl.java
Labels: Release 03/2025

#3250 Extrapolation of getMinQ and getMaxQ for reactive capability curves
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/ReactiveCapabilityCurve.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/util/ReactiveCapabilityCurveUtil.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ReactiveCapabilityCurveAdderImpl.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ReactiveCapabilityCurveImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/ReactiveCapabilityCurveImplTest.java
Labels: Breaking Change, Release 03/2025, Custom IIDM impl

#3307 Refactor `CgmesNamespace` interface
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/GeneratingUnitEq.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/LoadingLimitEq.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/OperationalLimitTypeEq.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/TapChangerEq.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesNamespace.java
Labels: CGMES, Breaking Change, Release 03/2025

#3282 Different extension's serialization names depending on the version
  commons/src/main/java/com/powsybl/commons/extensions/AbstractExtensionSerDe.java
  commons/src/main/java/com/powsybl/commons/extensions/DefaultExtensionProvidersLoader.java
  commons/src/main/java/com/powsybl/commons/extensions/ExtensionProviders.java
  commons/src/main/java/com/powsybl/commons/extensions/ExtensionProvidersLoader.java
  commons/src/main/java/com/powsybl/commons/extensions/ExtensionSerDe.java
  commons/src/main/java/com/powsybl/commons/xml/XmlReader.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/ExportOptions.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/NetworkSerDe.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/extensions/AbstractVersionableNetworkExtensionSerDe.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/extensions/util/DefaultExtensionsSupplier.java
  iidm/iidm-serde/src/main/java/com/powsybl/iidm/serde/extensions/util/ExtensionsSupplier.java
  iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/LoadFooSerDe.java
  iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/LoadMockSerDe.java
  iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/VoltageLevelFooSerDe.java
  iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/XMLExporterTest.java
  iidm/iidm-serde/src/test/java/com/powsybl/iidm/serde/extensions/SerializationNamesTest.java
  iidm/iidm-serde/src/test/resources/V1_0/xsd/loadMock_V0_1.xsd
  iidm/iidm-serde/src/test/resources/V1_0/xsd/loadMock_V0_2.xsd
  iidm/iidm-serde/src/test/resources/extensionName_0_1.xml
  iidm/iidm-serde/src/test/resources/extensionName_0_1_otherPrefix.xml
  iidm/iidm-serde/src/test/resources/extensionName_0_2.xml
  iidm/iidm-serde/src/test/resources/extensionName_1_2.xml
  iidm/iidm-serde/src/test/resources/namespace-prefix-collision.xml
  iidm/iidm-serde/src/test/resources/xsd/voltageLevelFoo.xsd
  iidm/iidm-test/src/main/java/com/powsybl/iidm/network/test/VoltageLevelFooExt.java
Labels: Release 03/2025

#3337 Clean bus/breaker view getConnectableBus() usages
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/TopologyExport.java
  iidm/iidm-api/src/main/java/com/powsybl/iidm/network/Equipments.java
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/VoltageLevelImpl.java
Labels: Deprecated, Release 03/2025

#3301 ReportNode: change timestamp feature
  commons/src/main/java/com/powsybl/commons/report/AbstractReportNodeAdderOrBuilder.java
  commons/src/main/java/com/powsybl/commons/report/ReportConstants.java
  commons/src/main/java/com/powsybl/commons/report/ReportNodeAdderOrBuilder.java
  commons/src/main/java/com/powsybl/commons/report/ReportNodeBuilder.java
  commons/src/main/java/com/powsybl/commons/report/ReportNodeChildAdderImpl.java
  commons/src/main/java/com/powsybl/commons/report/ReportNodeImpl.java
  commons/src/main/java/com/powsybl/commons/report/ReportNodeNoOp.java
  commons/src/main/java/com/powsybl/commons/report/ReportNodeRootBuilderImpl.java
  commons/src/main/java/com/powsybl/commons/report/TreeContext.java
  commons/src/main/java/com/powsybl/commons/report/TreeContextImpl.java
  commons/src/main/java/com/powsybl/commons/report/TreeContextNoOp.java
  commons/src/test/java/com/powsybl/commons/report/NoOpTest.java
  commons/src/test/java/com/powsybl/commons/report/ReportNodeTest.java
Labels: Breaking Change, Release 03/2025

#3299 ReportNode i18n
  commons/src/main/java/com/powsybl/commons/report/AbstractReportNodeAdderOrBuilder.java
  commons/src/main/java/com/powsybl/commons/report/ReportNodeAdderOrBuilder.java
  commons/src/main/java/com/powsybl/commons/report/ReportNodeChildAdderImpl.java
  commons/src/main/java/com/powsybl/commons/report/ReportNodeNoOp.java
  commons/src/main/java/com/powsybl/commons/report/ReportNodeRootBuilderImpl.java
  commons/src/main/java/com/powsybl/commons/report/TreeContextNoOp.java
  commons/src/main/resources/com/powsybl/commons/reports.properties
  commons/src/main/resources/com/powsybl/commons/reports_en_US.properties
  commons/src/main/resources/com/powsybl/commons/reports_fr.properties
  commons/src/main/resources/com/powsybl/commons/reports_fr_FR.properties
  commons/src/test/java/com/powsybl/commons/report/NoOpTest.java
  commons/src/test/java/com/powsybl/commons/report/ReportNodeTest.java
  commons/src/test/resources/i18n/reports.properties
  commons/src/test/resources/i18n/reports_en_US.properties
  commons/src/test/resources/i18n/reports_fr.properties
  commons/src/test/resources/i18n/reports_fr_FR.properties
  ucte/ucte-network/src/main/java/com/powsybl/ucte/network/UcteNetworkImpl.java
  ucte/ucte-network/src/main/java/com/powsybl/ucte/network/UcteValidation.java
  ucte/ucte-network/src/main/java/com/powsybl/ucte/network/util/UcteReports.java
Labels: Deprecated, Release 03/2025

#3309 CGMES loading from zipped profiles inside a folder
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesImport.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/LoadZippedProfilesTest.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/CgmesOnDataSource.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/NamespaceReader.java
  commons/src/main/java/com/powsybl/commons/compress/SafeZipInputStream.java
  commons/src/main/java/com/powsybl/commons/io/ForwardingInputStream.java
  commons/src/test/java/com/powsybl/commons/compress/SafeZipInputStreamTest.java
  docs/grid_exchange_formats/cgmes/import.md
Labels: PR: do-not-merge, Release 03/2025

#3357 Handle negative zero case in reactive capability curves
  iidm/iidm-impl/src/main/java/com/powsybl/iidm/network/impl/ReactiveCapabilityCurveImpl.java
  iidm/iidm-impl/src/test/java/com/powsybl/iidm/network/impl/ReactiveCapabilityCurveImplTest.java
Labels: bug, Release 03/2025

#3347 Psse: fix the export process
  psse/psse-converter/src/test/resources/ExampleVersion32_exported.raw
  psse/psse-converter/src/test/resources/IEEE_118_bus_updated_exported.raw
  psse/psse-converter/src/test/resources/IEEE_14_bus_nodeBreaker_rev35_exported.raw
  psse/psse-converter/src/test/resources/IEEE_14_bus_nodeBreaker_rev35_split_bus_exported.raw
  psse/psse-converter/src/test/resources/IEEE_24_bus_updated_exported.raw
  psse/psse-converter/src/test/resources/IEEE_30_bus_updated_exported.raw
  psse/psse-converter/src/test/resources/IEEE_57_bus_updated_exported.raw
  psse/psse-converter/src/test/resources/RawCaseWithSpecialCharacters_exported.raw
  psse/psse-converter/src/test/resources/SwitchedShunt_exported.raw
  psse/psse-converter/src/test/resources/ThreeMIB_T3W_modified_exported.raw
  psse/psse-converter/src/test/resources/ThreeMIB_T3W_phase_exported.raw
  psse/psse-converter/src/test/resources/TwoWindingsTransformerPhase_exported.raw
  psse/psse-converter/src/test/resources/five_bus_nodeBreaker_rev35_exported.raw
  psse/psse-converter/src/test/resources/five_bus_nodeBreaker_rev35_split_buses_exported.raw
  psse/psse-converter/src/test/resources/parallelTwoTerminalDcBetweenSameAcBuses_updated_exported.raw
  psse/psse-converter/src/test/resources/remoteControl_updated_exported.raw
  psse/psse-converter/src/test/resources/twoTerminalDc_updated_exported.raw
  psse/psse-model-test/src/main/resources/IEEE_14_bus_completed.raw
  psse/psse-model-test/src/main/resources/IEEE_14_bus_completed_exported.raw
  psse/psse-model-test/src/main/resources/IEEE_14_bus_exported.raw
  psse/psse-model-test/src/main/resources/IEEE_14_bus_rev35_exported.raw
  psse/psse-model-test/src/main/resources/IEEE_14_bus_rev35_exported.rawx
  psse/psse-model/src/main/java/com/powsybl/psse/model/pf/PsseCaseIdentification.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/pf/PsseFacts.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/pf/io/FactsDeviceData.java
  psse/psse-model/src/main/java/com/powsybl/psse/model/pf/io/SubstationData.java
  psse/psse-model/src/test/resources/ExampleVersion32_exported.raw
  psse/psse-model/src/test/resources/IEEE_14_bus_completed.json
  psse/psse-model/src/test/resources/IEEE_14_bus_completed_rev35.json
  psse/psse-model/src/test/resources/IEEE_14_bus_completed_rev35.raw
  psse/psse-model/src/test/resources/IEEE_14_bus_completed_rev35.rawx
  psse/psse-model/src/test/resources/IEEE_14_bus_completed_rev35_exported.raw
  psse/psse-model/src/test/resources/IEEE_14_bus_completed_rev35_exported.rawx
  psse/psse-model/src/test/resources/IEEE_14_bus_nodeBreaker_rev35_exported.raw
  psse/psse-model/src/test/resources/IEEE_14_bus_nodeBreaker_rev35_exported.rawx
  psse/psse-model/src/test/resources/IEEE_14_bus_whitespaceAsDelimiter_exported.raw
  psse/psse-model/src/test/resources/IEEE_14_isolated_buses_exported.raw
  psse/psse-model/src/test/resources/IEEE_24_bus_exported.raw
  psse/psse-model/src/test/resources/IEEE_24_bus_rev35_exported.raw
  psse/psse-model/src/test/resources/IEEE_24_bus_rev35_exported.rawx
Labels: Release 03/2025

#3360 Restore missing constructor in `LoadFlowParameters`
  loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java
  loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowDefaultParametersLoaderTest.java
Labels: bug, Release 03/2025

#3328 Dynamic simulation mappings renaming
  docs/simulation/dynamic/index.md
  docs/simulation/dynamic_security/index.md
  docs/user/itools/dynamic-security-analysis.md
  docs/user/itools/dynamic-simulation.md
Labels: Release 03/2025

#3306 Add documentation about the available topology NetworkModification
  docs/grid_features/network_modifications.md
  docs/grid_model/extensions.md
Labels: Documentation, Release 03/2025

#3366 Fix LoadFlowParameters selection when 'load-flow' module is defined
  loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java
  loadflow/loadflow-api/src/test/java/com/powsybl/loadflow/LoadFlowDefaultParametersLoaderTest.java
Labels: Release 03/2025

#3338 Scalable access
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/GeneratorScalable.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/LoadScalable.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/ProportionalScalable.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/StackScalable.java
  iidm/iidm-modification/src/main/java/com/powsybl/iidm/modification/scalable/UpDownScalable.java
Labels: Release 03/2025

#3326 Doc update: New behavior for BalanceType PROPORTIONAL_TO_REMAINING_MARGIN
  docs/simulation/loadflow/configuration.md
  loadflow/loadflow-api/src/main/java/com/powsybl/loadflow/LoadFlowParameters.java
Labels: Breaking Change, Release 03/2025

#3315 CGMES export: Add a parameter to export as bus branch
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/CgmesExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportContext.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/EquipmentExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/StateVariablesExport.java
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/elements/ControlAreaEq.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/ConversionUtil.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportContextTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesTopologyKindTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/ExportToCimVersionTest.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/TopologyExportCornerCasesTest.java
  cgmes/cgmes-model/src/main/java/com/powsybl/cgmes/model/triplestore/CgmesModelTripleStore.java
  docs/grid_exchange_formats/cgmes/export.md
Labels: CGMES, Breaking Change, Feature, Release 03/2025

#3363 Fix duplicate EquipmentOperation profile in header
  cgmes/cgmes-conversion/src/main/java/com/powsybl/cgmes/conversion/export/CgmesExportUtil.java
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesExportTest.java
Labels: bug, Release 03/2025

#3373 Fix documentation about ReportNode
  docs/user/functional_logs/import.md
  docs/user/functional_logs/index.md
Labels: Release 03/2025

#3370 CGMES export as bus/branch: unit test to clarify behaviour with non-retained open switches
  cgmes/cgmes-conversion/src/test/java/com/powsybl/cgmes/conversion/test/export/CgmesTopologyKindTest.java
  docs/grid_exchange_formats/cgmes/export.md
Labels: CGMES, Release 03/2025
